### ISSUE TITLE
Storyboard Form Release

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1061]
Create a Storyboard for the AUTHORIZATION FOR RELEASE OF INFORMATION section in the legacy SF-86

Acceptance Criteria
- Use legacy SF-86 to derive content
  - [ ] Authorization text (see form)
  - [ ] Signature (Sign in ink)
  - [ ] Full name (Type or print legibly)
  - [ ] Date signed (mm/dd/yyyy)
  - [ ] Other names used
  - [ ] Date of birth
  - [ ] Social Security Number
  - [ ] Current street address Apt. #
  - [ ] City (Country)
  - [ ] State
  - [ ] ZIP Code
  - [ ] Telephone number
- Reviewed and Approved by 18f PMO
- Reviewed and Approved by Product Owner

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-form-release](https://cloud.githubusercontent.com/assets/19935974/25580878/2b86a8d2-2e52-11e7-8467-c732ec5b997a.jpg)

**Comment by billy22g** [comment]
LGTM!

**Comment by Jay-Neighbours-I72** [comment]
2 additional options as discussed during sprint review:

Adding individual buttons for each sections. (Recommend against this as it clutters the space and increased visual burden on the user.)
![e-app-comp-form-release-option-2](https://cloud.githubusercontent.com/assets/19935974/25951625/3ee899bc-362c-11e7-848d-63014dbe1244.jpg)

-

Single button link back to Information about you 
![e-app-comp-form-release-option-3](https://cloud.githubusercontent.com/assets/19935974/25951624/3ee5a86a-362c-11e7-9fcc-8b6dc34cc32f.jpg)

**Comment by lauraponce** [comment]
Agreed with @Jay-Neighbours-I72 that this clutters the space, and it seems to also draw attention away from the main call to action of signing their digital signature. One thought is maybe move the "If you need to change any information..." to under the fields they are verifying. 

So the flow could be, they see "Verify your information is correct", then they read their info and verify it, then they see the "If you need to change any information..." underneath where the telephone number is rather than at the top where they might skim over.

**Comment by Jay-Neighbours-I72** [comment]
I like that flow a lot, something like this? @lauraponce 

![Uploading e-APP-comp-form-release-option-3.jpg…]()

**Comment by billy22g** [comment]
This looks great!

**Comment by billy22g** [comment]
@lauraponce When you're 👍 would you mind closing and shifting this to complete?

cc: @DBrenenborg and @Sheldon1013 for visibility.

**Comment by lauraponce** [comment]
I like this style a lot for the info verification! The one thing I'm wondering about is the "If everything looks good sign below" because they _are_ signing if their info looks okay, but the other point is that they are signing to say they agree to the authorization for releasing their information.

I don't think we can add in a standard "I have read this and authorize" type text because I'm sure that would involve some major legal approvals, but what if, instead, the flow was flip flopped and so first they verify their info, then they read all that text and then immediately sign under it where it's clear they are signing because they understand what they read and authorize it? Thoughts? @Jay-Neighbours-I72 @billy22g

**Comment by billy22g** [comment]
Great point @lauraponce. Seems like it'd weird to verify your info *outside* the context of signing it though.

**Comment by Jay-Neighbours-I72** [comment]
Yeah really good point @lauraponce , that flow makes much more sense....

![e-app-comp-form-release-option-4](https://cloud.githubusercontent.com/assets/19935974/26009714/06c6da70-3718-11e7-8f9b-c8d988ea6102.jpg)
 @billy22g

**Comment by billy22g** [comment]
Not nearly as confusing as I pictured it in my head. LGTM.

**Comment by lauraponce** [comment]
Looks perfect!
