### ISSUE TITLE
Applicant Alcohol Use Negative Impact Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1190]
As an eApp applicant I want to see a summary listing of all instances in the last seven years that I have entered where alcohol use has had a negative impact on my professional and personal life so that I can see a listing of all personal negative impacts of alcohol use I've had in the past 7 years, reopen and edit specific impact instance entries, or remove an instance.

Acceptance Criteria
- Summary of alcohol use impacts 
  - [ ] Shown only if alcohol use impacts have been provided
  - [ ] Listing of each alcohol use impact entry the applicant has entered
  - [ ] For each alcohol use impact entry show the following summary fields: 
    - [ ] Date (M/Y): Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to alcohol use impact entry section
      - [ ] Delete - Removes the alcohol use impact information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
