### ISSUE TITLE
Storyboard Sticky header

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1197]
As an eApp user I would like relevant headers at the top of the form and form sections\accordion controls to stay visible as I scroll down the form and enter data so that I can keep the context of what section of the form I am filling out.

Acceptance Criteria
- [ ] Have a sticky header on screens down to tablet size. 
- [ ] Header would shrink to a smaller size and keep Section title visible 
- [ ] Accordion controls should also have stick headers and should work with the form's sticky header

**Comment by Jay-Neighbours-I72** [comment]
Before user scrolls.
![e-app-sticky-header-1](https://user-images.githubusercontent.com/19935974/27440751-b0ef3f60-5739-11e7-9e6a-f57ff8c287d2.jpg)

-
User scrolls:
- Top header shrinks and stick
- Headline (Military History in this example) drops in size
- Accordion sticky header> height will shrink slightly and we animate close and delete buttons out
- Also add a subtle drop shadow, accordion content will scroll behind this

![e-app-sticky-header-2](https://user-images.githubusercontent.com/19935974/27440752-b0ef917c-5739-11e7-8fab-88e8b1cfb6cb.jpg)

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Looking awesome! Thoughts on making the accordion item they're in collapsable when they're scrolled down somewhat as shown in the above screenshot? Seems like the remove can drop, but the close might be nice.

**Comment by Jay-Neighbours-I72** [comment]
I think that can work, let me comp something up. Will likely want to lose the close icon so we can keep the smaller height.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g 
![e-app-sticky-header-3-w-close](https://user-images.githubusercontent.com/19935974/27540297-b3b3cbc8-5a4d-11e7-96d7-4085d27b2d5f.jpg)

**Comment by billy22g** [comment]
Looks great! Thanks!

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @floresj To clarify on the top header (Military History).. This shouldn't shift to the left, that was a mistake in the comp.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 the top header you are referring to is the "Military history" text?

**Comment by Jay-Neighbours-I72** [comment]
Yep.
