### ISSUE TITLE
Confusion around address validation text

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1202]
- [x] Add remove icon (svg in drive folder)
- [x] Change "Use this address instead" text to "Keep original address"
- [x] Make it so clicking outside the dialogue box also closes overlay

Close icon style:
<img width="910" alt="screen shot 2017-05-10 at 2 28 05 pm" src="https://cloud.githubusercontent.com/assets/19935974/25914615/ea691f82-358c-11e7-996d-581d2f8fffc5.png">

**Comment by bmallred** [comment]
## Preview
![close-icon](https://cloud.githubusercontent.com/assets/697855/25919541/08709748-359d-11e7-90be-65fa6781db5a.png)

**Comment by Jay-Neighbours-I72** [comment]
looks great

**Comment by lauraponce** [comment]
In the case that more information is required (e.g. they left out a unit number), should we make the more obvious call to action about adding the unit number? @Jay-Neighbours-I72 

![screen shot 2017-05-16 at 11 24 56 am](https://cloud.githubusercontent.com/assets/21222704/26114046/50754bb0-3a2a-11e7-8ea0-c7e06a0920c2.png)

**Comment by Jay-Neighbours-I72** [comment]
I like that a lot, much more clear for the user. Maybe something like this @lauraponce.

<img width="843" alt="screen shot 2017-05-22 at 9 56 06 am" src="https://cloud.githubusercontent.com/assets/19935974/26312314/2a46ce3c-3ed5-11e7-8c37-178cf5eba21e.png">

**Comment by bmallred** [comment]
Moved this back to **In Progress** to accommodate the new changes.

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28031590-c4c127ac-6575-11e7-9a89-359500595b20.png)

**Comment by billy22g** [comment]
LGTM
