### ISSUE TITLE
Time delay with address validation modal

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1203]
As an eApp user I want an immediate address verification notice to prevent me from moving to another field before the address I entered is validated so that I am not interrupted several seconds after I've left the address field.  

Acceptance Criteria
- [x] Immediately take over screen with modal overlay once user tabs out of complete address
- [x] Add verification animation/icon + verified icon (Jay to style)
- [x] Set timeout for 5 seconds

**Comment by Jay-Neighbours-I72** [comment]
Loading style: (green piece will animate around circle)
<img width="546" alt="screen shot 2017-05-11 at 9 58 19 am" src="https://cloud.githubusercontent.com/assets/19935974/25953091/622c65b2-3630-11e7-9360-a66c45132ab5.png">


-
Verified style: (loading will shrink and check will grow then address suggestion will pop up or window will close)
<img width="456" alt="screen shot 2017-05-11 at 9 58 22 am" src="https://cloud.githubusercontent.com/assets/19935974/25953121/768de8aa-3630-11e7-99e5-8df107704044.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 Looks good! This pops up inside the modal vertically and horizontally centered?

**Comment by Jay-Neighbours-I72** [comment]
yeah exactly, center of the screen

**Comment by billy22g** [comment]
Typo in the "Verifying you address"

**Comment by billy22g** [comment]
This is awesome @bmallred! 

However, there's some goofiness with it that we need to address. If I've just verified my address and then click into a different field, it does the verification again. 

A possible suggestion is: if blur and there's a change in any of the fields then validate, otherwise do nothing. If they haven't changed anything, the previous validation should still be appropriate.

**Comment by bmallred** [comment]
Ah, good catch!

**Comment by billy22g** [comment]
@bmallred Think there's still a bug here:

1. I enter an address. It validates.
2. I change something in that address that pops up the validation again.
3. I click the blue "Use this address" button.
4. It takes two clicks of the button to get back to the form.

**Comment by billy22g** [comment]
Still same behavior as my last comment.

**Comment by bmallred** [comment]
@floresj can you verify this? Not happening locally.

**Comment by bmallred** [comment]
!ping @floresj

**Comment by bmallred** [comment]
!ping @floresj

**Comment by floresj** [comment]
@bmallred Sorry about that. I just ran it and I didn't experience the double clicking behavior.

**Comment by colinpmacarthur** [comment]
I'm not able to replicate the issue @billy22g described above, but am hesitant to move this to done until he's seen it. Billy, can you take a look?

**Comment by billy22g** [comment]
This looks good now. Thanks folks!
