### ISSUE TITLE
Hesitation in adding street name

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1204]
- [x] Add second address input line
- [x] Change label to Street address
- [x] Remove all placeholder text except for apt

Comp:
<img width="1223" alt="screen shot 2017-05-10 at 2 40 11 pm" src="https://cloud.githubusercontent.com/assets/19935974/25915426/69a75104-358f-11e7-9b6d-255722c95223.png">

**Comment by floresj** [comment]
Is this just for full addresses or any place we ask for a street address? 

cc: @Jay-Neighbours-I72 @bmallred

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @pjsumm and I discussed via hangout

**Comment by Jay-Neighbours-I72** [comment]
This looks good, let's change the Apt, suite... line to label instead of placeholder.

Better UX because it won't go away when user is in that box.

**Comment by floresj** [comment]
![selection_236](https://user-images.githubusercontent.com/5938731/27542269-b81102a6-5a54-11e7-9d0b-1b7299dac9c3.png)

Validation
![selection_237](https://user-images.githubusercontent.com/5938731/27542275-bd7f8758-5a54-11e7-8293-be8938c590f8.png)

**Comment by Jay-Neighbours-I72** [comment]
Just realized we need to make the second line Optional @floresj

**Comment by floresj** [comment]
@Jay-Neighbours-I72 It's optional. We're not enforcing that field be required.

**Comment by Jay-Neighbours-I72** [comment]
Can we thrown in the "optional" text to make sure users know?

example:
<img width="815" alt="screen shot 2017-06-27 at 9 43 33 am" src="https://user-images.githubusercontent.com/19935974/27590562-1a778aaa-5b1d-11e7-941c-bc2bf6eeb580.png">

**Comment by bmallred** [comment]
Sure can!

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/27599286-43f99db4-5b36-11e7-9de8-b0a5b348a904.png)

**Comment by Jay-Neighbours-I72** [comment]
Pefecto

**Comment by billy22g** [comment]
LGTM!
