### ISSUE TITLE
Month field confusion

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1206]
Month inputs:

- [x] Accept numbers only (no month names)
- [x] Remove auto tabbing

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Reducing the width of the month results in the following:
![selection_102](https://cloud.githubusercontent.com/assets/5938731/26077417/f3065f8c-3989-11e7-8940-f502dd7fc2e0.png)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Possible solution
![selection_103](https://cloud.githubusercontent.com/assets/5938731/26077696/f61a7252-398a-11e7-8162-d5fd90ead75a.png)

**Comment by Jay-Neighbours-I72** [comment]
@floresj For a temporary solution let's try to keep the width of the input the same as "Day" but have the typeahead suggestions width wider to to accommodate month names

**Comment by bmallred** [comment]
## Preview
![selection_105](https://cloud.githubusercontent.com/assets/697855/26079498/fe5580dc-3990-11e7-91dd-c47430d76988.png)

What we ended up doing was allowing the controls rendering to be overridden but to still maintain the current value via local state.

**Comment by lauraponce** [comment]
This is looking good, two small things:

- [ ] Update the input to accept anything from 1-12 – currently it accepts 0 and 00 to 12.
- [ ] Update the month results to show up if they type 04 the same as if they just type 4 (since the placeholder text shows the two zeros, it makes it seem like if your month is April, you should type it as 04)

**Comment by billy22g** [comment]
@lauraponce I'll leave this for you. Not sure if current implementation satisfies your concerns above.

**Comment by lauraponce** [comment]
Looks good to me! Entering in something like "04" works as expected, and it's fine that it accepts 00 because all the numeric fields are consistent in that behavior.
