### ISSUE TITLE
Verify Foreign Business Interests

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1302]
Verify foreign activities section (section 20a in SF-86 PDF). Equates to one page of the SF-86.

Acceptance Criteria:
Included the following sections
  - [x] Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children **EVER** had any foreign financial interests that someone controlled on your behalf?
  - [x] Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children **EVER** owned, or do you anticipate owning, or plan to purchase real estate in a foreign country?
  - [x] As a U.S. citizen, have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children received **in the last seven (7) years**, or are eligible to receive in the future, any educational, medical, retirement, social welfare, or other such benefit from a foreign country?
- Write/audit help text
- Write/audit error text
- Compare against validation matrix

**Comment by Jay-Neighbours-I72** [comment]
Indirect control:
PR submitted for help text - no error text needed (small content tweaks included)

Validation issue made #1327

**Comment by Jay-Neighbours-I72** [comment]
Real estate:
PR submitted for help and error text

Validation issue #1341

**Comment by Jay-Neighbours-I72** [comment]
Foreign benefits:
PR submitted for help text (no error text needed)

Validation issue #1366 

Will review when on staging

**Comment by Jay-Neighbours-I72** [comment]
Found a few unused help, removed in a new PR.

**Comment by Jay-Neighbours-I72** [comment]
All done

**Comment by billy22g** [comment]
LGTM
