### ISSUE TITLE
Verify Foreign Business Support

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1303]
Verify the remainder of foreign activities and the beginning of foreign business, professional activities, and foreign government contacts  (section 20b in SF-86 PDF).  Equates to one page of the SF-86.

Include these sections in the verification:
  - [x] Have you **EVER** provided financial support for any foreign national?
  - [x] Have you **in the last seven (7) years** provided advice or support to any individual associated with a foreign business or other foreign organization that you have not previously listed as a former employer? (Answer “No” if all your advice or support was authorized pursuant to official U.S. Government business.)
  - [x] For this question, “Immediate Family” means your spouse or legally recognized civil union/domestic partner, parents, step-parents, siblings, half and step-siblings, children, step-children, and cohabitant. Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or any member of your immediate family **in the last seven (7) years** been asked to provide advice or serve as a consultant, even informally, by any foreign government official or agency? (Answer “No’ if all the advice or support was authorized pursuant to official U.S. Government business.)
  - [x] Has any foreign national **in the last seven (7) years** offered you a job, asked you to work as a consultant, or consider employment with them?

-Adding on:

- [x] **Other business ventures** - Have you in the last seven (7) years been involved in any other type of business venture with a foreign national not described above?

- [x] **Event participation** - Have you in the last seven (7) years attended or participated in any conferences, trade shows, seminars, or meetings outside the U.S.?
Do not include those you attended or participated in on official business for the U.S. government.

- [x] **Immediate family contact** - Have you or any member of your immediate family in the last seven (7) years had any contact with a foreign government, its establishment or its representatives, whether inside or outside the U.S.?

**Comment by Jay-Neighbours-I72** [comment]
Foreign national support
Help text in branch, will make PR today
No error text needed
Content verified
Validation issue #1401

**Comment by Jay-Neighbours-I72** [comment]
Support provided:
Help text in branch
No error text needed
Content verified
Validation issue #1403

**Comment by Jay-Neighbours-I72** [comment]
Immediate family foreign support:
Help text in branch
No error text needed
Content verified
No validation errors

**Comment by Jay-Neighbours-I72** [comment]
Employment:
Help text in branch - PR submitted
No error text needed
Content verified - issues added #1420 #1421 
No validation errors - validation issue #1423

**Comment by Jay-Neighbours-I72** [comment]
Other business ventures:
Help text in branch
No error text needed
Content verified
Validation issues #1442

**Comment by Jay-Neighbours-I72** [comment]
Event participation
Help text in branch
No error text needed
Content verified
Validation issues

**Comment by Jay-Neighbours-I72** [comment]
Immediate family contact
Help text in branch
No error text needed
Content verified
Validation issues #1451

**Comment by billy22g** [comment]
LGTM
