### ISSUE TITLE
Verify Foreign Business Professional Activities

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1304]
Verify the foreign business, professional activities, government contacts portion of the (section 20b in SF-86 PDF). Equates to one page of the SF-86.

Include these sections in the verification:
  - [x] Have you in the last seven (7) years been involved in any other type of business venture with a foreign national not described above (own, co-own, serve as business consultant, provide financial support, etc.)?
  - [x] Have you in the last seven (7) years attended or participated in any conferences, trade shows, seminars, or meetings outside the U.S.? (Do not include those you attended or participated in on official business for the U.S. government.)
  - [x] For Section 20b, “Immediate Family” means your spouse, parents, step-parents, siblings, half and step-siblings, children, step-children, and cohabitant. Have you or any member of your immediate family in the last seven (7) years had any contact with a foreign government, its establishment (such as embassy, consulate, agency, military service, intelligence or security service, etc.) or its representatives, whether inside or outside the U.S.? (Answer ‘No’ if the contact was for routine visa applications and border crossings related to either official U.S. Government travel, foreign travel on a U.S. passport, or as a U.S. military service member in conjunction with a U.S. Government military duty.)
  - [x] Have you in the last seven (7) years sponsored any foreign national to come to the U.S. as a student, for work, or for permanent residence?

**Comment by Jay-Neighbours-I72** [comment]
The first 3 were added on to this issue during a previous sprint:
https://github.com/truetandem/e-QIP-prototype/issues/1303

**Comment by billy22g** [comment]
LGTM
