### ISSUE TITLE
Verify Foriegn Countries Visited

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1305]
Verify foreign countries visited section (section 20c in SF-86 PDF) and the remaining foreign business, professional activities, government contacts portion of the (section 20b in SF-86 PDF). Equates to one page of the SF-86.

Include these sections in the verification:
  - [x] Have you in the last seven (7) years sponsored any foreign national to come to the U.S. as a student, for work, or for permanent residence?
  - [x] Have you EVER held political office in a foreign country?
  - [x] Have you EVER voted in the election of a foreign country?
  - [x] Has your travel in the last seven (7) years been solely for U.S. Government business/military overseas assignment on official government orders (i.e., no personal trips in conjunction with the official U.S. Government business)?

**Comment by floresj** [comment]
@pjsumm  Are we just verifying these sections are complete? I see links for these in the app.

cc: @bmallred

**Comment by bmallred** [comment]
@floresj I think this one is for @Jay-Neighbours-I72 for his analysis. I may be wrong on that.

**Comment by Jay-Neighbours-I72** [comment]
yeah it is for me

**Comment by Jay-Neighbours-I72** [comment]
Foreign national sponsorship:
Content verified: Issues= #1553 #1554 
Validation issue: #1556 
Help text updated
No error text needed, some error text not showing: #1557

**Comment by Jay-Neighbours-I72** [comment]
Political office:
Content verified
Validation issue #1558
Help text updated
No error text needed.

**Comment by Jay-Neighbours-I72** [comment]
Voting:
Content verifired
Validation issue #1561 
Help text updated
No error text needed

**Comment by Jay-Neighbours-I72** [comment]
Foreign countries visited:
Content verified
Validation issue #1562
Help text updated
No error text needed

**Comment by Jay-Neighbours-I72** [comment]
PR submitted. Will review when live.

**Comment by billy22g** [comment]
LGTM
