### ISSUE TITLE
Round 7 Usability Testing sessions and results

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1316]
Round 7 Usability Testing sessions and results

 - **Military history section**
   - Selective service record
   - U.S. military
   - Disciplinary procedures
   - Foreign military
 - **Relationships**
   - People who know you well

## TODO

- [x] Conduct testing
- [x] Combine notes
- [x] Synthesize findings
- [x] Identify bugs, usability issues, etc and provide recommendations
- [x] Put together research report
- [x] Put together research presentation
