### ISSUE TITLE
Round 8 Usability Testing - planning, sessions and results

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1462]
Round 8 Usability Testing session planning and results
Wed. 6/28/2017

 - **Substance use**
   - Illegal use of drugs and drug activity
   - Usage
   - Purchase
   - Security clearance position
   - Public safety position
   - Misuse
   - Mandatory counseling or treatment
   - Voluntary counseling or treatment
   - Use of alcohol
   - Negative impact
   - Mandatory counseling or treatment
   - Voluntary counseling or treatment
   - Additional instances
 - **Citizenship**
   - Citizenship status
   - Dual/multiple citizenship status
- **Information about you**
   - Your contact information -> Your phone numbers (instructions)

## TODO

PLANNING
- [x] Create schedule
- [x] Book room
- [x] Recruit participants
- [x] Pre-testing bug pass
- [x] Apply any bug-fixes pre-testing
- [x] Usability test plan
- [x] Conduct testing

RESULTS
- [x] Combine notes
- [x] Synthesize findings
- [x] Identify bugs, usability issues, etc and provide recommendations
- [x] Put together research report
- [x] Put together research presentation

**Comment by lauraponce** [comment]
The room is booked and the participants have all been recruited. We will have 2 DoL users and 2 DoD users for this round of testing. The calendar invite has been updated with the details

**Comment by Jay-Neighbours-I72** [comment]
This has been complete for a while. Closing now.
