### ISSUE TITLE
Implement Sticky Headers

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1519]
As an eApp user I would like relevant headers at the top of the form and form sections\accordion controls to stay visible as I scroll down the form and enter data so that I can keep the context of what section of the form I am filling out.

Acceptance Criteria
- Have a sticky header on screens down to tablet size.
- Header would shrink to a smaller size and keep Section title visible
- Accordion controls should also have stick headers and should work with the form's sticky header

**Comment by floresj** [comment]
- [ ] Styles to main header when `sticky` is applied
- [ ] Styles to accordion row when `sticky` is applied
- [ ] Behavior that adds `sticky` to main header
- [ ] Behavior that adds `sticky` to accordion headers

I think the sticky main header and accordion headers can be independent of one another since there are instances where only the main header will be stickable (Review screens).

From #1197 
![e-app-sticky-header-3-w-close](https://user-images.githubusercontent.com/19935974/27540297-b3b3cbc8-5a4d-11e7-96d7-4085d27b2d5f.jpg)

**Comment by bmallred** [comment]
> I think the sticky main header and accordion headers can be independent of one another since there are instances where only the main header will be stickable (Review screens).

Agreed

**Comment by floresj** [comment]
I'm stealing Bryan's idea of demonstrating stuff with a video.

https://drive.google.com/file/d/0B6esg5ooWEjQY2ZoSlNCZmxKeU0/view?usp=sharing

**Comment by floresj** [comment]
Update of look and feel with compressed fixed accordion row.

![selection_315](https://user-images.githubusercontent.com/5938731/28123750-ca2dfa96-66ef-11e7-94c7-e42d839fc31e.png)

cc: @Jay-Neighbours-I72

**Comment by bmallred** [comment]
I think the **Close** button is missing the dotted underline from the comp. And should it be over to the right more?

**Comment by Jay-Neighbours-I72** [comment]
^Good eye

**Comment by floresj** [comment]
I love linux.

![output](https://user-images.githubusercontent.com/5938731/28132812-ed6a2b12-670b-11e7-8847-bd10c5bb97f0.gif)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 What should the mobile view look like?

**Comment by Jay-Neighbours-I72** [comment]
I'd like to play with that one in browser.

Have to make sure it can be made small enough that it isn't killing too much real estate.

**Comment by billy22g** [comment]
LGTM
