### ISSUE TITLE
Storyboard print/save

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1523]
As an eApp designer I want to create a storyboard that illustrates the design and flow for how will view and sign the certification and release forms.

As an eApp designer I want to create a storyboard that illustrates the design and flow for how users might be able to print and/or save their form data.

Acceptance criteria: 
- [ ] User review and sign certification and release forms
- [ ] User submit their form
- [ ] User print/save results

**Comment by Jay-Neighbours-I72** [comment]
Note: Include a list of pages with missing content

**Comment by Jay-Neighbours-I72** [comment]
Walkthrough:

1. User lands on submit page
2. Verification in progress
3. All inputs complete, releases are loaded, first one (Certifications is open)
4. User Signed and clicked "Next release" button opening and centering them on the next release. The Release of Info will always be present, HIPAA will only be there when a certain question in the Psychological section is answered.
5. All releases are signed, Submit button is now available.
6. User has submit, thank you/verification message is loaded as well as save/print button
7. Showing what a user sees when navigating to the Submit page before all sections are complete

[e-APP-comp-submit.pdf](https://github.com/truetandem/e-QIP-prototype/files/1139822/e-APP-comp-submit.pdf)

**Comment by Jay-Neighbours-I72** [comment]
jpgs:
![e-app-comp-submit-1](https://user-images.githubusercontent.com/19935974/28082961-f7f9b0ae-6641-11e7-85e3-8d87022fe770.jpg)
![e-app-comp-submit-2](https://user-images.githubusercontent.com/19935974/28082963-f7fdbf8c-6641-11e7-93b7-7d2ab1e7612a.jpg)
![e-app-comp-submit-3](https://user-images.githubusercontent.com/19935974/28082965-f8c64b32-6641-11e7-8f1f-bc170a1c27fe.jpg)
![e-app-comp-submit-4](https://user-images.githubusercontent.com/19935974/28082960-f7f8f510-6641-11e7-9c0d-ead5b27cb391.jpg)
![e-app-comp-submit-5](https://user-images.githubusercontent.com/19935974/28082959-f7f7747e-6641-11e7-89cf-5d23c8b12130.jpg)
![e-app-comp-submit-6](https://user-images.githubusercontent.com/19935974/28082962-f7f9f488-6641-11e7-8106-917cf13df016.jpg)
![e-app-comp-submit-7](https://user-images.githubusercontent.com/19935974/28082964-f805fd3c-6641-11e7-9444-e2b96960fa99.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Note: update storyboard to show credit release open

**Comment by Jay-Neighbours-I72** [comment]
storyboards updated

**Comment by Jay-Neighbours-I72** [comment]
Updated print/save screen:
![e-app-comp-submit-7](https://user-images.githubusercontent.com/19935974/28386043-5e2aba56-6c98-11e7-8c84-93bfc437ed54.jpg)


Thinking to center the text, icon and button to make it stand out even more and feel like the final step of the full process.

Thoughts?

**Comment by billy22g** [comment]
Much better in terms of the signal we're giving them! I'll let @colinpmacarthur take a look and offer any feedback as well.

**Comment by colinpmacarthur** [comment]
@Jay-Neighbours-I72 I like this! Much clearer.

A couple minor things:
- [ ] "Thanks for submitting your SF86" needs a period at the end.
- [ ] I wonder whether "Save/Print" is confusing. Are they saving or printing? What happens when they click that button?

**Comment by Jay-Neighbours-I72** [comment]
@colinpmacarthur 

In a previous GH issue #1313 we decided to not use punctuation on headlines. My preference is to keep not using punctuation but I can live with it either way. Which do you prefer?


When clicking the Save/Print button they will get the standard dialog to download the PDF, then they can print from that PDF. Does that text seem ok or would you prefer something else?

**Comment by colinpmacarthur** [comment]
Hmm. OK. Let me think a little more about the period thing in general, but don't let that be a road block here.

Let's also leave "Save/Print" for now. 

Moving this issue to done.

**Comment by Jay-Neighbours-I72** [comment]
Got it, feel free to re-open #1313 if you need to.

**Comment by pjsumm** [comment]
this should be closed
