### ISSUE TITLE
Re-verify user before signature

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1577]
As an eApp user I would like the SF-86 form to re-verify my identity after my login and before I digitally sign my form so that I can provide validation that I am the one signing the document

Acceptance Criteria 
- [ ] Use storyboard from #1596 as style guideline 
- [ ] When the user goes to digitally sign/verify the SF-86, prompt them to re-authenticate
- [ ] Use the same two-factor authentication token as the original login (if possible)

**Comment by pjsumm** [comment]
closing this per discussion with PO and 18f PMO. decided if the user is currently logged in, and their session is active, no need to re-authenticate.
