### ISSUE TITLE
eApp relational data model

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1591]
As an eApp developer I want to create a relational data model in a database so that an eApp applicant can persist their data entered into the eApp form to a database 

Acceptance Criteria
- [x] data saved is associated to the user
- [x] user can view their saved data on their next login
- [x] relational data model developed in PostgreSQL
- [x] data is converted to and from JSON
- [x] the database design is documented

**Comment by bmallred** [comment]
Just throwing out some structure ideas!

Table: payload
---
| Name | Type |
|-|-|
| id | int |
| type | string |
| account | int |
| parent | id |
| section | bool |

Table: props
---
| Name | Type |
|-|-|
| id | int |
| payload | int |
| name | string |
| value | string or binary or something |

cc: @floresj

**Comment by bmallred** [comment]
# Idea 2

Table: section
---
| Name | Type |
|-|-|
| id | int |
| account | int |
| name | string |

Table: payload
---
| Name | Type |
|-|-|
| id | int |
| type | string |
| parent | int |

Table: props
---
| Name | Type |
|-|-|
| id | int |
| payload | int |
| name | string |
| value | string or binary or something |
| index | int |

**Comment by bmallred** [comment]
# Idea 3

Table: foreign.business.family
---
| Name | Type |
|-|-|
| id | int |
| account | int |
| hasforeignfamily | bool |


Table: foreign.business.family.list
---
| Name | Type | Description |
|-|-|-|
| id | int | |
| index | int | |
| name | int | Reference to name table |
| agency | int | Reference to agency table |
...

Table: name
---
| Name | Type |
|-|-|
| id | int |
| first | string |
| firstInitialOnly | bool |
| last | string |
| lastInitialOnly | bool |
| middle | string |
| noMiddleName | bool |
| middleInitialOnly | bool |
| suffix | string |
| suffixOther | string |

**Comment by billy22g** [comment]
LGTM
