### ISSUE TITLE
eApp form data persistence service

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1592]
As an eApp developer I want to create a server side service for **brokering data** between the eApp form and a database so that I can easily support data storage/retrieval to a database so I can save data from the eApp form to an database and retrieve data from the database to put into the eApp form. 

Acceptance Criteria
- [x] http endpoint(s) to save/retrieve data
- [x] service endpoints are documented
- [x] handle server side errors and translate them appropriately to front end
- [x] utilize an object-relational mapper
