### ISSUE TITLE
Add login messages

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1593]
As an eApp applicant I want to see the legal warnings for accessing a government system so that I can I can accept the stipulations for accessing a government website. 

Acceptance Criteria
- [x] follow the design in #265
- [x] have message regarding wifi connections (confirm with Product Owner)
- [x] have message regarding

**Comment by bmallred** [comment]
Storyboard has changed/evolved! See #1878

![e-qip-register-2](https://user-images.githubusercontent.com/19935974/30755062-279cb308-9f93-11e7-9686-1f3c88f18a08.jpg)

**Comment by bmallred** [comment]
@pjsumm did we ever get a hard confirmation on the **wifi** consent?

**Comment by floresj** [comment]
There seems to be some markdown weirdness on some of the bullet points:

![selection_475](https://user-images.githubusercontent.com/5938731/31136329-e547e922-a835-11e7-887d-fbcd5ac418c3.png)

**Comment by bmallred** [comment]
Original WiFi warning:

![image](https://user-images.githubusercontent.com/697855/31140714-3def5616-a843-11e7-9f1b-f9ef56cbe126.png)

**Comment by pjsumm** [comment]
received confirmation from Product Owner in #2017

**Comment by billy22g** [comment]
LGTM
