### ISSUE TITLE
Verify citizenship status content

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1594]
Verify the citizenship status portion of the eApp form (section 10 in SF-86 PDF). Equates to 3/4 of a page in the SF-86.

Include these sections in the verification:
- [x] Provide your current citizenship status...
- [x] You answered that you are a U.S. citizen or national by birth, born to U.S. parent(s) in a foreign country
- [x] You answered that you are a naturalized U.S. citizen
- [x] You answered that you are a derived U.S. citizen.
- [x] Not a U.S. Citizen

**Comment by Jay-Neighbours-I72** [comment]
Citizenship status:
Content verified - issues - #1657 #1658 #1659

**Comment by billy22g** [comment]
LGTM
