### ISSUE TITLE
Storyboard re-verify user before signature

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1596]
As an eApp designer I want to create a storyboard showing how users will be re-verified before they digitally sign the eApp form so that the development team can use the storyboard to prototype the form.

Acceptance Criteria
- [ ] utilize existing styles and design concepts
- [ ] show two-factor authentication form again
- [ ] Approval from 18f PMO
- [ ] Approval from Stakeholders

**Comment by pjsumm** [comment]
closing this per discussion with PO and 18f PMO.  decided if the user is currently logged in, and their session is active, no need to re-authenticate.
