### ISSUE TITLE
Verify Form Instructions

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1655]
Verify the form instructions portion of the eApp form (form instructions are found in the introduction on the SF-86 PDF form pages 3 and 4) 

Acceptance Criteria
- Include the following information sections from the 2016 SF-86 PDF content guide
  - [ ] Questionnaire for National Security Positions
  - [ ] Purpose of this Form
  - [ ] Authority to Request this Information
  - [ ] The Investigative Process
  - [ ] Your Personal Interview
  - [ ] Instructions for Completing this Form
  - [ ] Final Determination on Your Eligibility
  - [ ] Penalties for Inaccurate or False Statements
  - [ ] Disclosure Information
  - [ ] Office of Personnel Management (OPM) Routine Uses
  - [ ] Public Burden Information

**Comment by Jay-Neighbours-I72** [comment]
working file:
https://docs.google.com/document/d/12gGiKzcBGP7R5vGTQjichaKVWhUr_HJSRtz4peDOAZU/edit

**Comment by Jay-Neighbours-I72** [comment]
Email sent to Sheldon and Drew to outline the suggested changes in the "Instructions for Completing this Form" section.

PR for one typo change found: #1708 

All other sections look good.

**Comment by Jay-Neighbours-I72** [comment]
Per email - Sheldon & Drew ok with proposed changes. Drew sent to Donna for approval.

Waiting on response.

**Comment by Jay-Neighbours-I72** [comment]
A piece that I missed my first pass on the instructions:

Any time we are calling out specific question numbers that have changed on the prototype, should we change these to the full section name?

<img width="1093" alt="screen shot 2017-09-22 at 12 46 14 pm" src="https://user-images.githubusercontent.com/19935974/30755295-110029da-9f94-11e7-9b9b-8c9dc42b9e07.png">

**Comment by Jay-Neighbours-I72** [comment]
Per Sheldon/Billy. Good to run with the refined instructions.

**Comment by billy22g** [comment]
LGTM
