### ISSUE TITLE
Verify substance use drugs

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1672]
Verify the Illegal use of drugs and drug activity portion of the eApp form (section 23 in SF-86 PDF). Equates to 2 pages of content in the legacy SF-86.

Include these sections in the verification:
- [x] Usage
- [x] Purchase
- [x] Security clearance position
- [x] Public safety position
- [x] Misuse
- [x] Mandatory counseling or treatment
- [x] Voluntary counseling or treatment

**Comment by Jay-Neighbours-I72** [comment]
Usage:
No content issues, 1 Bug #1677 
No help/error text updates needed
Validation #1678

**Comment by Jay-Neighbours-I72** [comment]
Purchase:
No content issues, 1 Bug #1682 
No help/error text updates needed
Validation #1683

**Comment by Jay-Neighbours-I72** [comment]
Security clearance position:
No content issues
No help/error text updates needed
Validation #1684

**Comment by Jay-Neighbours-I72** [comment]
Public safety position:
No content issues
No help/error text updates needed
Validation #1685

**Comment by Jay-Neighbours-I72** [comment]
Mandatory counseling or treatment:
Content issue #1689 , 1 Bug #1688
No help/error text updates needed
Validation #1690

**Comment by Jay-Neighbours-I72** [comment]
Voluntary counseling or treatment:
No content issues, 1 bug #1691
No help/error text updates needed
Validation #1692
