### ISSUE TITLE
Reuse previously used address

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1674]
As an eApp applicant I would like to reuse address that I have used elsewhere in the eApp form so that I can avoid re-typing the same address and avoid possible mistakes

Acceptance Criteria
- [x] Follows the design established in Storyboard #773 
- [x] There is a link to a listing of previously entered addresses
- [x] The list contains address only from approved sources (not all possible address from the form)
- [x] The user chooses from the list of can exit the list and enter the address manually
- [x] Address is re-verified

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @colinpmacarthur Given the size and importance of this one, I'd like us all to check it in a couple different areas prior to moving to complete.

**Comment by colinpmacarthur** [comment]
Playing around with this a little bit, one question that comes to mind: Should we warn users that changing the originally-entered address won't change the others? If I enter 123 Elm Street in one location, use it in others and then change it, they won't stay matching.

**Comment by colinpmacarthur** [comment]
Another related question: What should happen if I delete an accordion segment containing a previously used address? As it stands, that address still persists in the list.

**Comment by colinpmacarthur** [comment]
I can verify that, minus the above questions, this works as intended in these sections: 
- Your history > Where you have lived
- Your history > Employment activities 
- Your history > Former federal service

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @lauraponce Did you have thoughts on Colin's two primary questions above. This seems pretty important to get right, so just want to make sure we're aligned on the expected behavior.

**Comment by lauraponce** [comment]
Great questions from Colin as per usual! To Colin's first question, for when they update the original address, I can see it being useful to have an 'update in all instances' button or 'update just this one instance' (not sure of the proper wording of that though, but it would essentially do that).

To the second question, I think that would be okay that the address persists in the list because the person entered it at one point and they might have just put it in the wrong location of the form but might need it later. I don't see it getting in the way of people to have one additional address in the list to scroll through and it could be really useful for the people that do need it later. 

Thoughts @Jay-Neighbours-I72?

**Comment by billy22g** [comment]
I like your proposed direction @lauraponce. If we're going to do that, it could get pretty messy, so we want to make sure we build in sufficient time to implement and check that it's working as expected under a variety of use cases and shared fields. I wonder if Colin's suggested approach is worthwhile as an incremental step, or if it's worth it to just go all the way. @bmallred @floresj can you give us a sense of the lift on Laura's suggestion?

For the second question about deletion, I would think it would persist if the address is still present in another location. If it's not, it seems like it should go away. But maybe I'm wrong.

**Comment by bmallred** [comment]
At the moment the address book does not apply an identifier for each entry. This can be changed but without it we would need to track the state of the address to determine which one would need to be updated. Likewise, and this applies to the second question as well, tracking down every usage of where the address would be difficult with its current implementation.

**Comment by Jay-Neighbours-I72** [comment]
My thoughts:

**1. Changing one or all instances of address**
I like Laura's solution. 
A lighter lift solution could be Colin's where we "warn" the user they will need to change in multiple places. (Maybe in the shared address suggestion itself)

**2.Address deleted**
I am thinking these addresses stay in case user needs them again even if they are not being used in another location. I agree with Laura they might need it later and don't think the address books will become overwhelming.

**Comment by billy22g** [comment]
1. I think before we proceed on the solution Laura proposed, we should discuss with @Sheldon1013 and @DBrenenborg for a decision, given that it's a pretty significant change in how it's implemented.

Colin's proposed solution does seem like the least messy incremental step to me.

2. I think I'm 👍 on leaving it as is as well.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @lauraponce Are you ok with the above direction?

**Comment by bmallred** [comment]
Do we have a verdict on this?

cc: @billy22g @Jay-Neighbours-I72 @lauraponce

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @lauraponce Bump

**Comment by lauraponce** [comment]
Sorry I've missed the last few tags on this! It sounds like there are two options here for updating an address:

1. Warn people if they are changing an address that's also used in other places that they might need to update it in multiple places. When they change it, some text could come up saying "This address is also being used in other places on the form. If you need to update the address for other sections of the form, you will need to update it in each instance the address is being used." 

2. Have an 'update in all instances' button or 'update just this one instance' if someone is making a change to one of the previously used addresses.

I think either option would work and if 1 is a much lighter lift to implement, that might be best. Either option informs the user about what's going on and what they can do, so I'm good with either one.

@Jay-Neighbours-I72 thoughts?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @pjsumm @bmallred @floresj Let's bring this up in sprint planning for Sheldon.

**Comment by billy22g** [comment]
Reopening so we'll talk about it in this morning's meeting to resolve open questions. It should evolve into a new user story after that, and this one can be closed.

**Comment by billy22g** [comment]
Two additional user stories to come, option 1 which will be implemented immediately, and option 2, which will be prioritized in the backlog and estimated. cc: @bmallred @pjsumm

**Comment by pjsumm** [comment]
User Stories #2444 and #2445 created for review/implementation
