### ISSUE TITLE
Form data final confirmation

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1699]
As an eApp applicant, when I have completed adding information to the eApp web form I would like a final verification to occur so I know that all required information has been provided so that it is less likely my form submission will not be returned to me for additional information. 

Acceptance Criteria
- [ ] Follow design from storyboard #1523 
  - [ ] Show verification progress meter
  - [ ] Clearly denote the verification has passed/failed
  - [ ] Display verification errors in a list and reflect in navigation, where the errors can be addressed
  - [ ] Easily navigate to sections to correct errors

**Comment by billy22g** [comment]
This works so much nicer now! Love the grey bar until it's red or green. LGTM.
