### ISSUE TITLE
Applicant Contact Information Telephone

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#173]
As an eApp applicant I want to specify a valid phone number, either work, home, or cellular, so that investigators can easily contact me via telephone number at the correct hour.

Acceptance Criteria:
- Field Information
  - [x] Labels: "telephone number" , "Number", "Extension", "Time", "Add Optional Comment"
  - [x] Each phone number is comprised of "Number" (10 numbers), "Extension" (free text); "Time" (Pick: Day, Night, Both)
  - [x] Designate if Home, Work, Mobile, (other?)
  - [x] Must have at least 1 phone number
  - [x] Show 2 phone number entry fields with ability to add more
  - [x] Allow many phone numbers (add)
  - [x] Allow international and standard format (choose)
  - [x] Comment field is optional and multi-line text and has in-line help: "Note: If you need to provide any additional comments about this information, enter them below."
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@pjsumm this should probably carry over to [Sprint 6](https://github.com/truetandem/e-QIP-prototype/milestone/7) because we need to sync it with the design comps which where recently update.

**Comment by bmallred** [comment]
Pending PR #459
