### ISSUE TITLE
Applicant Passport Number

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#174]
As an eApp applicant I want to specify whether I have a passport, what the passport number is, and any additional comments I have on the matter so that my passport status is clear.

Acceptance Criteria:
- Field Information
  - [x] Labels: "Do you possess a U.S. passport (current or expired)?", "Provide the following information for the most recent U.S. passport you currently possess.", "Provide your U.S. passport number:", "Click HERE for U.S. State Department passport help", "Add Optional Comment", "Note: If you need to provide any additional comments about this information, enter them below."
  - [x] The do you have a passport field is a Y/N choice, required 
  - [x] Passport Number field is free text - letters and numbers, unlimited, required 
  - [x] There is inline help text and a link for information regarding Passport number that goes to: 
https://travel.state.gov/content/travel/en.html
  - [x] The comments field is free text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why
