### ISSUE TITLE
Verify Association Record

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1767]
Verify the Association Record portion of the eApp form (section 29 in SF-86 PDF). Equates to one page in the legacy SF-86.

Include these sections in the verification:
- [x] Association record
- [x] Terrorist organization
- [x] Engaged in terrorism
- [x] Advocating
- [x] Membership - overthrow
- [x] Membership - violence or force
- [x] Activities to overthrow
- [x] Terrorism association

**Comment by Jay-Neighbours-I72** [comment]
All sections content reviewed.
Spelling errors fixed in PR
Issue #1849

**Comment by Jay-Neighbours-I72** [comment]
Association record:
Help text tweaked
No error text needed

**Comment by Jay-Neighbours-I72** [comment]
Engaged in terrorism:
Help text tweaked
No error text needed
Validation #1851

**Comment by Jay-Neighbours-I72** [comment]
Advocating:
Help text tweaked
No error text needed
Validation #1852

**Comment by Jay-Neighbours-I72** [comment]
Membership - overthrow:
Help text tweaked
No error text needed
Validation #1854

**Comment by Jay-Neighbours-I72** [comment]
Membership - violence or force:
Help text tweaked
No error text needed
Validation #1855

**Comment by Jay-Neighbours-I72** [comment]
Activities to overthrow:
Help text tweaked
No error text needed
Validation #1856

**Comment by Jay-Neighbours-I72** [comment]
Terrorism association:
No help text changes needed
No error text needed
No additional validation needed

**Comment by Jay-Neighbours-I72** [comment]
PR for help text tweaks #1857

**Comment by billy22g** [comment]
LGTM
