### ISSUE TITLE
Verify employment activities employment record

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1867]
Verify the Employment Activities – Employment & Unemployment Record portion of the eApp form (section 13a in SF-86 PDF). Equates to 2 pages in the legacy SF-86.

Include these sections in the verification:
- [x] If Employment Type is Active Duty, National Guard/Reserve, or USPHS Commissioned Corps
- [x] If Employment Type is Other Federal employment, State Government, Federal Contractor, Non-government employment, or Other
- [x] If Employment Type is Self-Employment
- [x] If Employment Type is Unemployment
- [x] If Employment Type is Active Duty, National Guard/Reserve, USPHS Commissioned Corps, Other Federal employment, State Government, Federal Contractor, Non-government employment, Self-Employment, Unemployment, or Other

**Comment by Jay-Neighbours-I72** [comment]
These were wrapped into this issue - #1869

**Comment by lauraponce** [comment]
Closing this one since it's included in #1869
