### ISSUE TITLE
Storyboard help refinement

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1871]
As a user when I'm confused about a word, I want to be able to find more information about the word so I can confidently answer the related question. 

Acceptance Criteria
- [x] Rethinking help placement
- [x] Derive a design for term definitions
- [x] Ensure designs work together in one storyboard

**Comment by Jay-Neighbours-I72** [comment]
Help icon revision ideas:
![e-app-comp-help-v3-icon-1](https://user-images.githubusercontent.com/19935974/30080148-915165b4-9250-11e7-90ef-ea428d5f8e65.jpg)
![e-app-comp-help-v3-icon-2](https://user-images.githubusercontent.com/19935974/30080150-91577c10-9250-11e7-8066-f14e9eff98e7.jpg)
![e-app-comp-help-v3-icon-3](https://user-images.githubusercontent.com/19935974/30080151-915bf8d0-9250-11e7-8093-8d4a7f7352a9.jpg)
![e-app-comp-help-v3-icon-4](https://user-images.githubusercontent.com/19935974/30080149-91553090-9250-11e7-91e9-a016ce27e1fc.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Definition ideas - Light option:
![e-app-comp-help-v3-definition-light-1](https://user-images.githubusercontent.com/19935974/30080172-a229a6b2-9250-11e7-8a96-9a9265c5e364.jpg)
![e-app-comp-help-v3-definition-light-2](https://user-images.githubusercontent.com/19935974/30080171-a224d1e6-9250-11e7-8163-7fe8e5d446dc.jpg)
![e-app-comp-help-v3-definition-light-3](https://user-images.githubusercontent.com/19935974/30080170-a2248f24-9250-11e7-8ceb-6e315d8a59de.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Mid option:
![e-app-comp-help-v3-definition-mid-1](https://user-images.githubusercontent.com/19935974/30080190-b2ad3206-9250-11e7-84d5-b9538c631550.jpg)
![e-app-comp-help-v3-definition-mid-2](https://user-images.githubusercontent.com/19935974/30080191-b2b1bce0-9250-11e7-8735-da681baf4466.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Heavy option:
![e-app-comp-help-v3-definition-heavy-1](https://user-images.githubusercontent.com/19935974/30080205-bfbd12fe-9250-11e7-80d3-4f4073645a92.jpg)
![e-app-comp-help-v3-definition-heavy-2](https://user-images.githubusercontent.com/19935974/30080204-bfb927de-9250-11e7-8dc3-6e85046d70ed.jpg)
![e-app-comp-help-v3-definition-heavy-3](https://user-images.githubusercontent.com/19935974/30080206-bfc1cba0-9250-11e7-933d-33c1f40d13ed.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-APP-comp-help-definitions-comps.pdf](https://github.com/truetandem/e-QIP-prototype/files/1278671/e-APP-comp-help-definitions-comps.pdf)

**Comment by floresj** [comment]
That's pretty slick.

**Comment by Jay-Neighbours-I72** [comment]
Per hangout/call:

- Help icon location is approved.
- Condensing of help text where it makes sense is approved. Take this on a case by case basis, won't make sense to combine everywhere

- All options of definitions are approved.
- Start with the light option and text with users

**Comment by Jay-Neighbours-I72** [comment]
@porta-antiporta Here is the new help icon style with the light definition style.

![e-app-comp-help-v3-definition-light-1](https://user-images.githubusercontent.com/19935974/30170612-9d0935ee-93bd-11e7-9a12-0484fb23ece7.jpg)
![e-app-comp-help-v3-definition-light-2](https://user-images.githubusercontent.com/19935974/30170613-9d0e15a0-93bd-11e7-9776-4172e5821748.jpg)
![e-app-comp-help-v3-definition-light-3](https://user-images.githubusercontent.com/19935974/30170611-9d096ce4-93bd-11e7-84db-05fa88c6d221.jpg)

**Comment by billy22g** [comment]
LGTM
