### ISSUE TITLE
Storyboard comment field placements

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1872]
As an eApp applicant I want to add comments to certain questions and fields so that I can supplement my answer on the form with additional information.  

Acceptance Criteria
- [x] Validate that a comment field is present after Yes/No branch questions in legacy eQIP
- [x] Use the existing add comments design in comp
- [x] Provide 3 examples of how comments can be added to a field/question

**Comment by Jay-Neighbours-I72** [comment]
According to the validation matrix sections do have "Optional Comments" at the end of each section

**Comment by Jay-Neighbours-I72** [comment]
Section when user answers "No"

![e-app-comp-section-comments-1-1](https://user-images.githubusercontent.com/19935974/29926260-ec5d0ee6-8e30-11e7-8942-d3fb392096d8.jpg)
![e-app-comp-section-comments-1-2](https://user-images.githubusercontent.com/19935974/29926261-ec5f325c-8e30-11e7-85ec-15311e480815.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Section when user has answered "Yes"

![e-app-comp-section-comments-2-1](https://user-images.githubusercontent.com/19935974/29926290-0148f680-8e31-11e7-88c8-6be6032905da.jpg)
![e-app-comp-section-comments-2-2](https://user-images.githubusercontent.com/19935974/29926291-014c3f7a-8e31-11e7-81e3-7d7e0383430f.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Section with accordions closed

![e-app-comp-section-comments-3-1](https://user-images.githubusercontent.com/19935974/29926329-20152278-8e31-11e7-9414-d668f971f427.jpg)
![e-app-comp-section-comments-3-2](https://user-images.githubusercontent.com/19935974/29926330-2016cb8c-8e31-11e7-9e05-c9c83cf6059b.jpg)

**Comment by Jay-Neighbours-I72** [comment]
This is the current "Add comment" style.

Thoughts @lauraponce @colinpmacarthur @billy22g ?

**Comment by billy22g** [comment]
My hangup here is that the comments are related to each *section* and not to any particular input, so to me that's pretty confusing as to what the comment is supposed to relate to.

**Comment by lauraponce** [comment]
I think the style you have ^ @Jay-Neighbours-I72 works nicely! To @billy22g's point, maybe the comment stuff could slide down to go underneath the dividing line and above the back/next buttons at the bottom to give the idea that it's about the whole section and not just the last question? Thoughts?

I also think playing up the fact that it's optional would help with reducing nonessential comments in there too, maybe along the lines of:
"Would you like to add a comment about any of your responses relating to real estate purchases? _(Optional)_"

**Comment by billy22g** [comment]
Good stuff @lauraponce, and thanks @Jay-Neighbours-I72. As discussed, let's discuss with Sheldon and Drew either during a standup or setting up some time (especially if there are multiple things that need a decision). cc: @porta-antiporta

**Comment by Jay-Neighbours-I72** [comment]
Good points @lauraponce I like that wording much better, way more clear as to what the comment is tied to.

Will re-work now.

**Comment by Jay-Neighbours-I72** [comment]
Worked through some ideas with @lauraponce  and settled on this:

- Keep the comment above the grey line so it is associated with the page content instead of the Prev/Next buttons.
- The more conversational headline lent itself more to the regular input style using a smaller headline to separate it from the regular section questions.
- Input height could be either single or multiline style either across the form or dependent on section.

![e-app-comp-section-comments-v2-1](https://user-images.githubusercontent.com/19935974/29942173-ed0292d0-8e62-11e7-98c0-4a9e59682871.jpg)
![e-app-comp-section-comments-v2-2](https://user-images.githubusercontent.com/19935974/29942172-ed01f9b0-8e62-11e7-858d-9b4eaa3f22af.jpg)
![e-app-comp-section-comments-v2-3](https://user-images.githubusercontent.com/19935974/29942171-ecfdd010-8e62-11e7-93f0-18f2a8cc7dee.jpg)

Thoughts @billy22g @porta-antiporta

**Comment by porta-antiporta** [comment]
re: @billy22g's input that comments are at the `section` level and not `page` level.

Is the section in this case `7. Foreign Activities` (numbered item in left hand nav)? or is it `Real estate purchase` (any item on left hand nav)? 

One thought is to tie the text of the question to be the Section title to make it more explicit that it's tied to the section and not the page within a section.
  
> Would you like to add a comment about any of your responses relating to `<Section title>`

Also, in earlier mockups there was a `Remove comment` control.  I assuming that's been deprecated in the later design (an empty field imho suffices as an indicator there's no comment).

**Comment by Jay-Neighbours-I72** [comment]
Correct about empty field = no comment.

Per the validation matrix/legacy form it looks like the Optional comments are Subsection/page related. Meaning the comp would be correct, "...add comment to direct control"
<img width="1004" alt="screen shot 2017-08-31 at 4 14 07 pm" src="https://user-images.githubusercontent.com/19935974/29943467-91f07ec0-8e67-11e7-8e75-2b22020728ae.png">

That seems to make more sense to me, allowing the user to give these comments right after they finish that subsection. That way it is fresh in their mind.

My concern with an overall (top level) section comment are:
Could be further removed from context (specific question they want to comment on)

This style is really flexible though and like you said @porta-antiporta we can drop the <Section title> or <Subsection title> in. If we thought a full Section (top level) comment was needed I think it makes the most sense at the bottom of that sections review page.

**Comment by Jay-Neighbours-I72** [comment]
Per hangout/call:

- Style is approved.
- Preference is to have comments on top level (numbered) sections only 
- Comp to come showing these comments on the review screen

**Comment by Jay-Neighbours-I72** [comment]
Top level section comment on review screen:

![e-app-comp-section-comments-v3-review-screen](https://user-images.githubusercontent.com/19935974/30177064-8f737722-93d2-11e7-873a-e4a2d1f69fb5.jpg)

**Comment by billy22g** [comment]
Moving this to complete because we implemented what we wanted. I did ask a clarifying question about the language in a different issue, however, and we can address that there.
