### ISSUE TITLE
Research PIV 2FA options

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1877]
As a developer I want to research mechanisms for 2-Factor Authentication for applicants who are existing government employees that have CAC/PIV cards, so that they can use their CAC/PIV card when logging into the eApp form to satisfy the 2-factors of authentication requirement (something they have, and something they know. 

Acceptance Criteria: 
- [ ] time-box research time period to 3 days
- [ ] First look into max.gov (determine difficult to produce prototype)
- [ ] After 5-days research meet with 18f to review findings and determine path forward

**Comment by pjsumm** [comment]
eApp will leverage NBIS platform IdAM solution for all login requirements: CAC/PIV, 2FA.
