### ISSUE TITLE
Storyboard applicant registration

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1878]
As an eApp designer I want to create a storyboard to show the process for a user registering their eApp account so that the development team can use the design to create the forms and prompts required in the process. 

Acceptance Criteria
- [x] User receives email containing confirmation
- [x] User accesses registration form via URL from their email
- [x] User is prompted that they are accessing a government site
- [x] User receives invalid registration error and directions for obtaining registration code
- [x] User is prompted with registration guidance for user Id/password creation and constraints
- [x] User enters user ID and password and confirms password
- [x] User submits form results and receives registration confirmation

**Comment by Jay-Neighbours-I72** [comment]
@pjsumm want to run through these with you first before pushing to the QA column.

![e-qip-register-1](https://user-images.githubusercontent.com/19935974/30755066-27a263ac-9f93-11e7-96c2-9b8e9a2884ce.jpg)
![e-qip-register-2](https://user-images.githubusercontent.com/19935974/30755062-279cb308-9f93-11e7-9686-1f3c88f18a08.jpg)
![e-qip-register-3](https://user-images.githubusercontent.com/19935974/30755064-279f4f14-9f93-11e7-92c4-f31fe1e69985.jpg)
![e-qip-register-4](https://user-images.githubusercontent.com/19935974/30755065-279ff720-9f93-11e7-9598-d9e727fcd53b.jpg)
![e-qip-register-5](https://user-images.githubusercontent.com/19935974/30755061-27984692-9f93-11e7-875f-a660c0deb61d.jpg)
![e-qip-register-6](https://user-images.githubusercontent.com/19935974/30755068-27a3a0a0-9f93-11e7-8f6a-6902ec2f984c.jpg)
![e-qip-register-7](https://user-images.githubusercontent.com/19935974/30755067-27a3195a-9f93-11e7-8844-7987b8f66720.jpg)

**Comment by billy22g** [comment]
LGTM
