### ISSUE TITLE
Ensure front and back end data structures match

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1940]
As an eApp developer I want to update the eApp form's JSON data structure to match the data model implemented in the database so that data can be easily brokered between the two. 

Acceptance Criteria
 - [x] JSON structure of components matches payload signatures
 - [x] Accordions (and other collections) converted to match expected backend structure
 - [x] Update component unit tests
 - [x] Update validation logic and tests

**Comment by billy22g** [comment]
@ctro Do you mind checking this one please and moving to done when you're 👍 ?

**Comment by ctro** [comment]
@billy22g :+1: :100: LGTM, Done!
