### ISSUE TITLE
Ensure data persistence

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1941]
As an eApp tester I want to test the sections of the eApp form adding data to each field, saving the section, then returning to the form so that I can validate that data is stored and retrieved properly for each field on the SF86 eApp form.

Acceptance Criteria
 - [x] Send frontend structure (by subsection) to backend
 - [x] Backend can apply additional validations on data
 - [x] Backend stores data appropriately
 - [x] Frontend can retrieve data after leaving active session

**Comment by billy22g** [comment]
LGTM
