### ISSUE TITLE
Demonstration Video

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1944]
As an eApp designer I want to create a demonstration video that highlights features of the eApp SF86 form so that stakeholders can be informed of the progress that the project team has made in implementing the form. 

Acceptance Criteria
- [x] video highlights features from a list approved by 18f
- [x] video is reviewed by stakeholders
- [x] the video is distributed to key stakeholders

**Comment by Jay-Neighbours-I72** [comment]
Video sent to team

**Comment by lauraponce** [comment]
The video turned out great! Moving this into current sprint completed.
