### ISSUE TITLE
Verify Military History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1986]
Confirm the Selective Service Record Record and Military History portion of the eApp form (sections 14 and 15 in SF-86 PDF). Equates to 1 page in the legacy SF-86.

Include these sections in the verification:
- [x] Were you born a male after December 31, 1959?/Have you registered with the Selective Service System (SSS)?
- [x] Have you EVER served in the U.S. Military?
- [x] Have you EVER served, as a civilian or military member in a foreign country’s military, intelligence, diplomatic, security forces, militia, other defense force, or government agency?

**Comment by Jay-Neighbours-I72** [comment]
Selective service:
No changes

U.S. Military:
Bug  #1990 

Foreign Military:
#1991

**Comment by Jay-Neighbours-I72** [comment]
Content verified, content and help tweaks here #1992

**Comment by lauraponce** [comment]
LGTM!
