### ISSUE TITLE
Verify Marital/Relationship Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1988]
Confirm the Marital/Relationship Statusl portion of the eApp form (sections 17 in SF-86 PDF). Equates to over a page in the legacy SF-86.

Include these sections in the verification:
- [x] Provide your current marital/relationship status with regard to civil marriage, legally recognized civil union, or legally recognized domestic partnership
  - [x] Branch - If In A Marriage, Civil Union, or Domestic Partnership or Separated
  - [x] Branch - If Widowed, Divorced/Dissolved, or Annulled
- [x] Do you presently reside with a person, other than a spouse or legally recognized civil union/domestic partner, with whom you share bonds of affection, obligation, or other commitment, as opposed to a person with whom you live for reasons of convenience (e.g. a roommate)?
  - [x] Branch - If Yes to Residing With a Cohabitant
  - [x] Branch - If Cohabitant is Foreign Born

**Comment by Jay-Neighbours-I72** [comment]
Bug #2007 #2008

**Comment by Jay-Neighbours-I72** [comment]
Cohabitant:
Content verified
Bug #2030

**Comment by billy22g** [comment]
LGTM
