### ISSUE TITLE
Integration with IDAM using SAML

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2064]
As a developer I want to research mechanisms for SAML for applicants who have existing accounts on an IDAM server may log into the eApp form to satisfy the 2-factors of authentication requirement.

Acceptance Criteria:

 - [x] Evaluate and select SAML library(ies)
 - [x] Backend server endpoints for issuing and receiving authentication workflow
 - [x] Allow configuration by environment variables similar to OAuth authentication

**Comment by billy22g** [comment]
@ctro Would you mind being the one to verify this is 👍 based on what you expect and move the card to "Current Sprint Complete" in the Projects Board?

**Comment by ctro** [comment]
Sure thing. AFAIK we're still just waiting to test the integration w/ Fred's system.  Once we can see that in action we can check the last box.

Also, this issue is closed -- should it be re-opened?

**Comment by billy22g** [comment]
Seems like it to me. cc: @bmallred

**Comment by bmallred** [comment]
Yeah I think it was closed auto-magically by GH via the PR being merged.

**Comment by bmallred** [comment]
Closing since remaining items are tracked at #2289

**Comment by billy22g** [comment]
@ctro When you're back can you please verify this one and move to the complete column when you're 👍 ?
