### ISSUE TITLE
Initiate eApp applicant access design

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2125]
As an eApp developer I want to research and plan designs for allowing users to register for eApp access so that I can create a set of User Stories to plan and execute the design.

Acceptance Criteria
- [x] High-level, informal workflow/design for facilitating user access to eApp
- [ ] Design approval by 18f PMO
- [ ] User Stories for implementing the design

**Comment by Jay-Neighbours-I72** [comment]
Pilot user flow:
![screen shot 2017-11-14 at 9 02 10 am](https://user-images.githubusercontent.com/19935974/32783677-90ab665e-c91a-11e7-8885-220f86d78f45.jpg)


Updated log in screen:
![e-qip-comp-log-in-page-v4](https://user-images.githubusercontent.com/19935974/32783569-3c0f8d78-c91a-11e7-8a13-2d7355011dc2.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Per email feedback we will be removing the username/pw log in for the Pilot.

**Comment by Jay-Neighbours-I72** [comment]
Updated headline and return to log in button. Headline still TBD

![e-qip-comp-log-in-page-v4-error](https://user-images.githubusercontent.com/19935974/33396203-d212520e-d515-11e7-9f30-48891e38131a.jpg)

**Comment by Jay-Neighbours-I72** [comment]
User story for implementing #2254
