### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2260]
Perform the following usability enhancements from usability test session 13 results: 

- [x] Remove the Back/Next buttons on top of the Review section page because their presence is confusing users.

- [x] Make login and instruction hyperlinks in the header part of the sticky header view as users scroll down, so they are always visible in the header

- [x] Relocate the other names used section so it occurs directly after the user enters their name information

Acceptance criteria
- [ ] usability enhancements are approved by test team 
- [ ] results are retested by users

**Comment by bmallred** [comment]
Associated PR #2250

**Comment by billy22g** [comment]
LGTM
