### ISSUE TITLE
Applicant Mental Health Competency Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#232]
As an applicant I want to see a summary listing of all incompetency declaration data I've entered so that I can see all related incompetency declaration data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of competency issues
  - [ ] Shown only if incompetency declaration information has been provided
  - [ ] Listing of each incompetency declaration entry the applicant has entered
  - [ ] For each incompetency declaration entry show the following summary fields: 
    - [ ] Agency or court name: Read-Only label
    - [ ] Date occurred: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to incompetency declaration information entry section
      - [ ] Delete - Removes the incompetency declaration information entry
- Easily toggle between high-level summary data and detail data
