### ISSUE TITLE
Applicant Mental Health Consult

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#233]
As an eApp applicant I want to specify whether I have ever been ordered to consult with a mental health professional by a court or administrative agency and provide the details of the entity who order me to consult with a mental health professional, when and where it happened, and what was the result so that I can provide the information surrounding the request for mental health consultation and my investigator can check into the incident(s).

Acceptance Criteria
- Fields (all required unless specified otherwise)
  - Has a court or administrative agency EVER ordered you to consult with a mental health professional?
  - **For example, a psychiatrist, psychologist, licensed clinical social worker, etc.**
  - An order to a military member by a superior officer is not within the scope of this question, and therefore would not require an affirmative response. An order by a military court would be within the scope of the question and would require an affirmative response.
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the next form section 
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date this occurred
  - Provide the date this occurred.
    - [ ] Date (Month/Year) (Estimated)
  - Provide the name of the court or administrative agency that declared you mentally incompetent.
    - [ ] Free Text
  - Provide the address of the court or administrative agency.
    - [ ] Street address and city
    - [ ] State and Zip Code or Country
  - Provide the final disposition.
    - [ ] Free Text
  - Was this matter appealed to a higher court or administrative agency?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the part of the section 
      - [ ] Yes - Fields are added 
        - [ ] Since you answered yes we need more information
        - Provide the name of the court or administrative agency.
          - [ ] Free Text
        - Provide the address of the court or administrative agency
          - [ ] Street address and city
          - [ ] State and Zip Code or Country
        - Provide the final disposition.
          - [ ] Free Text
        - Do you have an additional instance where this matter was appealed to a higher court or administrative agency?
          - [ ] Yes\No Option
          - [ ] **Branch**
            - [ ] No - move on to the part of the section
            - [ ] Yes - add another set of court/adminstrative agency fields
  - Do you have an additional instance where a court or administrative agency EVER ordered you to consult with a mental health professional?
  - **For example, a psychiatrist, psychologist, licensed clinical social worker, etc.**
  - An order to a military member by a superior officer is not within the scope of this question, and therefore would not require an affirmative response. An order by a military court would be within the scope of the question and would require an affirmative response.
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another required consultation detail section
      - [ ] If no, user continues to next form section
