### ISSUE TITLE
Applicant Mental Health Consult Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#234]
As an applicant I want to see a summary listing of all required mental health consultation data I've entered so that I can see all related required mental health consultation data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of required consultations
  - [ ] Shown only if required mental health consultation information has been provided
  - [ ] Listing of each required mental health consultation entry the applicant has entered
  - [ ] For each required mental health consultation entry show the following summary fields: 
    - [ ] Agency or court name: Read-Only label
    - [ ] Date occurred: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to required mental health consultation information entry section
      - [ ] Delete - Removes the required mental health consultation information entry
- Easily toggle between high-level summary data and detail data
