### ISSUE TITLE
Sprint 29 usability updates

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2347]
- [x] Update the "Submit" section navigation to make it more clear that the user will be able to review/print the form before clicking "Submit"

- [x] Update the text at the end of the education subsection of the form that currently prompts the applicant to  add "Another degree", but does not make it clear that it is asking for additional degrees for the current school context.

- [x] Provide clearer separation in the Your History review section between the places lived, employment history, and education history sections

**Comment by Jay-Neighbours-I72** [comment]
Submit section nav style:
https://github.com/truetandem/e-QIP-prototype/issues/2286

**Comment by Jay-Neighbours-I72** [comment]
I have a few ideas for the more clear separation in the Your history review section, @bmallred @floresj let me know when you have time to walk through them.

**Comment by Jay-Neighbours-I72** [comment]
Degree text update: #2351

**Comment by Jay-Neighbours-I72** [comment]
Your history review tweaks:

![e-app-your-histroy-review-tweaks](https://user-images.githubusercontent.com/19935974/34622349-dd4a8d4a-f21a-11e7-9065-b72905e2f975.jpg)

**Comment by billy22g** [comment]
LGTM
