### ISSUE TITLE
Applicant Mental Health Hospitalization

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#235]
As an eApp applicant I want to specify whether I have ever been hospitalized with mental health condition and provide the details of my admission, including how and why I was addmitted, the dates or treatment, and where it occurred so that I can provide the information surrounding my mental health hospitalization and my investigator can review the circumstance of my treatment.

Acceptance Criteria
- Fields (all required unless specified otherwise)
    -  Have you EVER been hospitalized for a mental health condition?
      - [ ] Yes/No Option
      - [ ] **Branch** 
        - [ ] No - move on to the next form section
        - [ ] Yes - An entry is created in the summary section, go to: Was the admission voluntary or involuntary
    - Was the admission voluntary or involuntary?
      - [ ] Voluntary Involuntary: choice buttons
        - [ ] Free text
    - Provide the dates of treatment.
      - [ ] Date Range (Month/Year) (Estimated)
    - Provide the name and address of the facility where treatment was provided.
      - [ ] Free Text
    - Provide the address of the facility where treatment was provided.
      - [ ] Street address and city
      - [ ] State and Zip Code or Country
    - Do you have an additional instance where you have EVER been hospitalized for a mental health condition?
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another instance" - button adds another hospitalization detail section
        - [ ] If no, user continues to next form section
