### ISSUE TITLE
Applicant Mental Health Hospitalization Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#236]
As an applicant I want to see a summary listing of all mental health hospitalization data I've entered so that I can see all related mental health hospitalization data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of mental health hospitalizations
  - [ ] Shown only if mental health hospitalization information has been provided
  - [ ] Listing of each mental health hospitalization entry the applicant has entered
  - [ ] For each required mental health hospitalization entry show the following summary fields: 
    - [ ] Facility name: Read-Only label
    - [ ] Date of treatment: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to mental health hospitalization information entry section
      - [ ] Delete - Removes the mental health hospitalization information entry
- Easily toggle between high-level summary data and detail data
