### ISSUE TITLE
Applicant Mental Health Diagnosis

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#237]
As an eApp applicant I want to specify whether I have ever been diagnosed with a mental health disorder and provide the details of my diagnosis and treatment, including condition, date of diagnosis, information for the professional who diagnosed, and treatment details so that I can provide the information surrounding my mental health diagnosis and my investigator can review the information.

Acceptance Criteria
- Fields (all required unless specified otherwise)
  - The following question asks whether you have been diagnosed with a specified mental health condition that may, particularly if untreated, impact your judgment, reliability, or trustworthiness. If you answer in the affirmative, we will seek additional information about the seriousness and symptoms of the condition, as well as any applicable course of treatment. It is important to note that any such diagnosis, in and of itself, is not a reason to revoke or deny eligibility/or access to classified information or for holding a sensitive position, suitability or fitness to obtain or retain Federal or contract employment, or eligibility for physical or logical access to federally controlled facilities or information systems.
  - Have you EVER been diagnosed by a physician or other health professional (for example, a psychiatrist, psychologist, licensed clinical social worker, or nurse practitioner) with psychotic disorder, schizophrenia, schizoaffective disorder, delusional disorder, bipolar mood disorder, borderline personality disorder, or antisocial personality disorder?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the next form section 
      - [ ] Yes - An entry is created in the summary section, go to: Identify the diagnosis or health condition
  - Identify the diagnosis or health condition.
    - [ ] Free Text
  - Provide the dates of diagnosis.
    - [ ] Date Range (Month/Year) (Estimated/Present)
  - Health care professional info
  - Provide the name, address, and telephone number of the health care professional who diagnosed you, or is currently treating you for such diagnosis, or with whom you have discussed such condition.
    - [ ] Free Text
    - [ ] Telephone Number block
  - Provide the address of the health care professional who diagnosed you, or is currently treating you for such diagnosis, or with whom you have discussed such condition.
    - [ ] Street address and city
    - [ ] State and Zip Code or Country
  - Agency/organization/facility info
  - Provide the name, address, and telephone number of any agency/organization/facility where counseling/treatment was provided
    - [ ] Free Text 
      - [ ] Check - Same as above (when checked, field optional)
    - [ ] Telephone Number Block
      - [ ] Check - Same as above (when checked, field optional)
  - Provide the address of any agency/organization/facility where counseling/treatment was provided
    - [ ] Street address and city
    - [ ] State and Zip Code or Country
      - [ ] Check - Same as above (when checked, field optional)
  - Was the counseling/treatment effective in managing your symptoms? Provide explanation.
    - [ ] Yes/No Option
    - [ ] Free text (must provide explanation regardless of yes or no answer)
  - Do you have an additional instance where you EVER had been diagnosed by a physician or other health professional (for example, a psychiatrist, psychologist, licensed clinical social worker, or nurse practitioner) with psychotic disorder, schizophrenia, schizoaffective disorder, delusional disorder, bipolar mood disorder, borderline personality disorder, or antisocial personality disorder?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another diagnosis"- button adds another diagnosis detail section
      - [ ] If no, user continues to next form section
  - In the last seven years, have there been any occasions when you did not consult with a medical professional before altering or discontinuing, or failing to start a prescribed course of treatment for any of the listed diagnoses?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the next form section 
      - [ ] Yes - An entry is created in the treatment summary section, go to: Are you currently in treatment
  - Are you currently in treatment?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the next form section 
      - [ ] Yes - An entry is created in the summary section, go to: Provide the name and telephone number...
  - Provide the name, address, and telephone number of the healthcare professional providing such treatment.
Name
    - [ ] Free Text
    - [ ] Telephone Number Block
  - Provide the address of the healthcare professional providing such treatment.
    - [ ] Street address and city
    - [ ] State and Zip Code or Country
  - Do you have an additional instance where you are currently in treatment?
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another treatment" - button adds another treatment detail section
        - [ ] If no, user continues to next form section

**Comment by floresj** [comment]
I'm really glad you typed out those paragraphs.
