### ISSUE TITLE
Correctly label output from system

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2472]
As an eApp applicant I want my print/saved output from my eApp application to be marked with the appropriate sensitivity level so that my output is correctly marked as For Official Use Only.

Acceptance Criteria
- [ ] Ensure print output is properly marked with “FOR OFFICIAL USE ONLY”
- [ ] Ensure saved output (save as PDF) is properly marked with “FOR OFFICIAL USE ONLY”
- [ ] Follow government guidelines for labeling sensitive content "FOR OFFICIAL USE ONLY”

**Comment by pjsumm** [comment]
Looks good to me.
