### ISSUE TITLE
Applicant Finances Bankruptcy Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#252]
As an applicant I want to state whether I have filed for bankruptcy or not so that I can be directed to enter to additional information regarding the bankrupty or move on to the next form section

Acceptance Criteria
- Form Fields
	- [x] In the last seven (7) years have you filed a petition under any chapter of the bankruptcy code?
		- Required
		- Yes\No Option	
		- Yes: When selected goes to bankruptcy to enter bankruptcy information
		- No: Move on to next financial form section
	- [x] Add Optional Comment
		- Optional - show only if needed
		- Help - "Note: If you need to provide any additional comments about this information, enter them below."
		- Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why
