### ISSUE TITLE
Applicant  Finances Bankruptcy Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#253]
As an applicant I want to enter my bankruptcy information if I have any so that I can specify the details and circumstances surrounding my bankruptcy and my investigators can review the information

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
	- Select the applicable bankruptcy petition type
		- [x] Select list
		- [x] Options: Chapter 7, Chapter 11, Chapter 12, Chapter 13
		- [x] If Chapter 13 is selected, must provide additional information
			- [x] Provide the name of the trustee for this bankruptcy. Free-Text
			- [x] Provide the address of the trustee for this bankruptcy. Address (With Country Option)
				- [x] Must provide Street and City
				- [x] State and Zip - or - Country are required
	- Provide the bankruptcy court docket/account number.	
		- [x] Free-text		
	- Provide the date bankruptcy was filed	
		- [x] Date type: M/Y Est
		- [x] Month and Year and specify if the date is an Estimate	
	- Provide the date bankruptcy was filed
		- [x] Date type: M/Y Est
		- [x] Month and Year and specify if the date is an Estimate
	- Provide the total amount (in U.S. dollars) involved in the bankruptcy.	
		- [x] Amount		
	- Provide the name debt is recorded under.
		- [x] Name Block (standared name block fields: First, Middle (i/o or no), Last(i/o), Suffix)
	- Provide the name of the court involved.
		- [x] Free-text
	- Provide the address of the court involved.
		- [x] Address - With Country Option
		- [x] Provide Street and City
		- [x] State and Zip - or - Country are required		
	- Add Optional Comment
		- [x] Optional - show only if needed
		- [x] Help - "Note: If you need to provide any additional comments about this information, enter them below."
		- [x] Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why
