### ISSUE TITLE
Applicant  Finances Gambling Debt Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#254]
As an applicant I want to state whether I have had financial problems due to gambling or not so that I can be directed to enter to additional information regarding the gambling debt or move on to the next form section

Acceptance Criteria
- Form Fields
	- [x] Have you EVER experienced financial problems due to gambling?	
		- Required
		- Yes/No Checkboxes
		- Yes: When selected goes to Gambling Debt details to enter gambling debt
 information
		- No: Move on to next financial form section
	- [x] Add Optional Comment
		- Optional - show only if needed
		- Help - "Note: If you need to provide any additional comments about this information, enter them below."
		- Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![screen shot 2017-01-18 at 2 12 36 pm](https://cloud.githubusercontent.com/assets/5938731/22079013/4a850bb8-dd88-11e6-8094-98f702dd61b0.png)
![screen shot 2017-01-18 at 2 12 22 pm](https://cloud.githubusercontent.com/assets/5938731/22079016/4ed9af52-dd88-11e6-8f15-ae99d229026f.png)
