### ISSUE TITLE
Applicant Finances Gambling Debt Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#255]
As an applicant I want to enter my gambling debt information if I have any so that I can specify the details and circumstances surrounding my gambling debt and my investigators can review the information

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
	- [x] Provide the date range of your financial problems due to gambling.	
		- Date Range - Est/Present		
	- [x] Provide an estimate of the amount (in U.S. dollars) of gambling losses incurred.
		- Amount	
	- [x] Provide a description of your financial problems due to gambling.
		- Multiline free-text	
	- [x] If you have taken any action(s) to rectify your financial problems due to gambling, provide a description of your actions. If you have not taken any action(s) provide explanation.
		- Multiline free-text		
	- [x] Add Optional Comment
		- Optional - show only if needed
		- Help - "Note: If you need to provide any additional comments about this information, enter them below."
		- Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![screen shot 2017-01-18 at 2 12 22 pm](https://cloud.githubusercontent.com/assets/5938731/22079016/4ed9af52-dd88-11e6-8f15-ae99d229026f.png)
