### ISSUE TITLE
Applicant Finances Tax Filing/Payment Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#256]
As an applicant I want to state whether I have failed to file or pay taxes so that I can be directed to enter to additional information regarding my failure to file or pay taxes or move on to the next form section.

Acceptance Criteria
- Form Fields
  - In the last seven (7) years have you failed to file or pay Federal, state, or other taxes when required by law or ordinance?	
    - [x] Required
    - [x] Yes/No Checkboxes
      - [x] **Branch**  
        - [x] Yes: Goes to tax [filing issue information entry ](https://github.com/truetandem/e-QIP-prototype/issues/257)
        - [x] No: Move on to next financial form section
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
