### ISSUE TITLE
Help text refinement - 3 - Your History

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2569]
Refining help text, shifting critical information to the headline, simplifying and making more clear.

- [x] Where you have lived
- [x] Employment activities
- [x] Where you went to school
- [x] Former federal service

**Comment by Jay-Neighbours-I72** [comment]
First pass done, PR https://github.com/truetandem/e-QIP-prototype/pull/2593

Will review when live.

**Comment by Jay-Neighbours-I72** [comment]
Review and wrapped changes into this PR https://github.com/truetandem/e-QIP-prototype/pull/2606
