### ISSUE TITLE
Applicant Finances Tax Filing/Payment Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#257]
As an applicant I want to enter details on when and why I did not file or pay my taxes and to which agency i was\am delinquent so that I can specify the details and circumstances surrounding my tax situation and my investigators can review the information.

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
  - Did you fail to file, pay as required, or both?
    - [x] Select list
    - [x] Options: File, Pay, Both
  - Provide the year you failed to file or pay your Federal, state or other taxes. (Estimated)
    - [x] Year
    - [x] Est - checkbox 
  - Provide the reason(s) for your failure to file or pay required taxes.	
    - [x] Free-text
  - Provide the Federal, state or other agency to which you failed to file or pay taxes.	
    - [x] Multi-line free-text
  - Provide the type of taxes you failed to file or pay (such as property, income, sales, etc.).
    - [x] Multi-line free text
  - Provide the amount (in U.S. dollars) of the taxes.
    - [x] Amount
    - [x] Estimated - Checkbox
  - Provide date satisfied.
    - [x] Date - M/Y Est
    - [x] Required unless "Not Applicable" has been selected
    - [x] Not applicable - Checkbox	
  - Provide a description of any action(s) you have taken to satisfy this debt (such as withholdings, frequency and amount of payments, etc.). If you have not taken any action(s) provide explanation.	
    - [x] Multi-line free text
  - Are there any other instances in the last seven (7) years where you failed to file or pay Federal, state or other taxes when required by law or ordinance?
    - If yes use the button below to add another tax filing/payment detail
       - [x] "Add another tax filing/payment issue" button - adds another tax filing/payment issue section
    - If no select no below and continue
       - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
