### ISSUE TITLE
Help text refinement - 6 - Foreign activities

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2572]
Refining help text, shifting critical information to the headline, simplifying and making more clear.

- [x] U.S. passport information
- [x] Foreign contacts

_
Foreign activities
- [x] Direct control
- [x] Indirect control
- [x] Real estate purchase
- [x] Foreign benefits
- [x] Foreign national support

_
Foreign business, professional activities, and government contacts
- [x] Support provided
- [x] Immediate family foreign support
- [x] Employment
- [x] Other business ventures
- [x] Event participation
- [x] Immediate family contact
- [x] Foreign national sponsorship
- [x] Held political office
- [x] Voting

_
- [x] Foreign countries you have visited

**Comment by Jay-Neighbours-I72** [comment]
Changes made.
