### ISSUE TITLE
Help text refinement - 9 - Investigative and criminal history

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2575]
Refining help text, shifting critical information to the headline, simplifying and making more clear.

 Police record
- [x] Offenses
- [x] Additional offenses
- [x] Domestic violence

_

Investigations and clearance record
- [x] Ever been investigated
- [x] Denied
- [x] Debarment

_
- [x] Involvement in non-criminal court actions

_

 Use of information technology systems
- [x] Unauthorized access
- [x] Manipulating access
- [ ] Unlawful use

_

Association record
- [x] Terrorist organization
- [x] Engaged in terrorism
- [x] Advocating
- [x] Membership - overthrow
- [x] Membership - violence or force
- [x] Activities to overthrow
- [x] Terrorism association

**Comment by Jay-Neighbours-I72** [comment]
PR: #2676

Will review when live.

**Comment by Jay-Neighbours-I72** [comment]
Reviewed and PR for fixes: #2691

**Comment by Jay-Neighbours-I72** [comment]
@bpdesigns Whoops, this means i forgot to drag it to complete
