### ISSUE TITLE
Applicant Finances Employer Card Abuse Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#258]
As an applicant I want to state whether I have been counseled for abusing an employer travel or credit card so that I can be directed to enter to additional information regarding my counseling for abusing an employer travel or credit card or move on to the next form section.

- Form Fields
  - In the last seven (7) years have you been counseled, warned, or disciplined for violating the terms of agreement for a travel or credit card provided by your employer?	
    - [x] Required
    - [x] Yes/No Checkboxes
    - [x] **Branch**
      - [x] Yes: When selected goes to [employer credit counseling information entry](https://github.com/truetandem/e-QIP-prototype/issues/259)
      - [x] No: Move on to next financial form section
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
