### ISSUE TITLE
Category II STIG Findings POAM

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2585]
Review open findings from the eApp Category II STIG checklist and create plan of action and milestones for open items.

Acceptance Criteria
- [x] Review all open Category II findings
- [x] Add POAM information to the eApp STIG checklist
- [x] Submit to customer stakeholders for review

**Comment by pjsumm** [comment]
POAMs were added to STIG checklist and submitted to DISA
