### ISSUE TITLE
Applicant Finances Employer Card Abuse Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#259]
As an applicant I want to enter details on my counseling for abusing an employer travel or credit card so that I can specify the details and circumstances surrounding my counseling for employer card abuse and my investigators can review the information.

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
  - Provide the name of the agency or company.	
    - [x] Free-text		
  - Provide the address of the agency or company.
    - [x] Address - With Country Option
    - [x] Provide Street and City
    - [x] State and Zip - or - Country are required
  - Provide the date of your counseling, warning, or disciplinary action.	
    - [x] Date - M/Y Est			
  - Provide the reason(s) for the counseling, warning or disciplinary action.
    - [x] Multi free-text	
  - Provide the amount (in U.S. dollars) of violation.
    - [x] Amount
    - [x] Estimated - Checkbox	
  - Provide a description of any action(s) you have taken to rectify this situation. If you have not taken any action(s) provide explanation.	
    - [x] Multi free-text		
  - Are there any other instances in the last seven (7) years where you have been counseled, warned, or disciplined for violating the terms of agreement for a travel or credit card provided by your employer?
    - [x] If yes use the button below to add another card abuse/counseling detail
      - [x] "Add another card abuse/counseling issue" button - adds another card abuse/cuseling issue section
    - [x] If no select no below and continue
       - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
