### ISSUE TITLE
Address verification timing

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2590]
As an eApp designer I want to work with stakeholders and team members to derive a design for how and when to perform data verification on addresses so that the user's flow through the form is not interrupted when the address verification takes place. 

Acceptance Criteria
- [x] Meet with team and stakeholders to come up with design concepts 
- [x] Create a design comp for the proposed solution(s)
- [ ] Customer approval of design concept(s) to be prototyped

**Comment by Jay-Neighbours-I72** [comment]
Bryan and I chatted about this an have some ideas to run by the team tomorrow in sprint review.

**Comment by Jay-Neighbours-I72** [comment]
Updated idea details:

![screen shot 2018-02-26 at 10 13 23 am](https://user-images.githubusercontent.com/19935974/36678256-40bee894-1ade-11e8-97ea-cfbdea720343.jpg)

Thoughts?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I think this covers quite a bit and looks great!

**Comment by Jay-Neighbours-I72** [comment]
Per Sheldon - All good with moving forward with this.

**Comment by pjsumm** [comment]
verified in dev and stage, behaves as advertised.
