### ISSUE TITLE
Continuous Integration container verification

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2634]
As an eApp developer I want to create a hash/checksum for files and containers produced in my build environment so that I can ensure containers and files transferred from build to government infrastructure during the CI process can be verified. 

Acceptance Criteria
- [x] Identify (or create) hash/checksum values to identify items produced by the current build process 
- [x] Approve process/method for obtaining hash/checksum with 18f PMO
- [x] Method conveyed to eApp infrastructure team for incorporation into CI process

**Comment by bmallred** [comment]
Resolved with #2874
