### ISSUE TITLE
Applicant Finances Credit Counseling Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#266]
As an applicant I want to provide information on any credit counseling services I may be seeking or using to resolve my financial difficulties so that I can specify the information on the services I am using and my investigators can review the information.

Acceptance Criteria
- Form Fields
  - Are you currently utilizing, or seeking assistance from, a credit counseling service or other similar resource to resolve your financial difficulties?	
    - [ ] Yes/No Checkboxes
    - [ ] **Branch**
      - [ ] Yes: When selected goes to [credit counceling service information entry](https://github.com/truetandem/e-QIP-prototype/issues/267)
      - [ ] No: Move on to next financial form section
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
