### ISSUE TITLE
Applicant Finances Credit Counseling Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#267]
As an applicant I want to enter details on any credit counseling services I am using, have used to resolve financial difficulties so that my investigator can review the information.

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
  - Provide explanation
    - [x] Multiline free-text		
  - Provide the name of the credit counseling organization or resource.
    - [x] Free-text		
  - Provide the phone number of the credit counseling organization.
    - [x] Telephone/Ext - Time		
  - Provide the location of the credit counseling organization.	
    - [x] Address - City/State		
  - As a result of this counseling provide a description of any action(s) you have taken to resolve your financial difficulties. If you have not taken any action(s) provide explanation.	
    - [x] Multi free-text
  - Are you currently utilizing, or seeking assistance from any other credit counseling service or other similar resource to resolve your financial difficulties?		
    - [x] If yes use the button below to add another credit counseling detail
       - [x] "Add another credit counseling entry" button - adds another credit counseling detail section
     - [x] If no select no below and continue
       - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
Questions:

 - Standardize address
 - Telephone includes international and DSN on current form

**Comment by floresj** [comment]
![screen shot 2017-01-18 at 12 36 25 pm](https://cloud.githubusercontent.com/assets/5938731/22075619/c87fdc18-dd7a-11e6-8f4f-c712d3f7ef50.png)
