### ISSUE TITLE
Summarize content issues with eApp form

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2706]
As an eApp stakeholder I want to understand what issues remain with the content of the SF86 form so that I can understand the work remaining to make the form more usable and easier to understand.

Acceptance Criteria
- [x] Aggregate usability test results from test sessions and videos, include comments regarding content issues
- [x] Create visual/info graphic depicting data aggregation summary
- [x] Review results with stakeholders for approval

**Comment by Jay-Neighbours-I72** [comment]
Content related feedback totals from usability testing sessions and usertesting.com
![screen shot 2018-03-20 at 12 47 14 pm](https://user-images.githubusercontent.com/19935974/37669386-165f5848-2c3d-11e8-9571-a342f95b8519.png)

**Comment by Jay-Neighbours-I72** [comment]
Here is the organized feedback. One long scroll infographic:
[content-feedback.pdf](https://github.com/truetandem/e-QIP-prototype/files/1838284/content-feedback.pdf)

Also broke it out into individual images if needed for a presentation:
![content-feedback-individual-images-01](https://user-images.githubusercontent.com/19935974/37782258-d9bad290-2dc8-11e8-9742-b4a40c872ec6.jpg)
![content-feedback-individual-images-02](https://user-images.githubusercontent.com/19935974/37782259-d9c8ecc2-2dc8-11e8-8333-148c5244e1cc.jpg)
![content-feedback-individual-images-03](https://user-images.githubusercontent.com/19935974/37782260-d9d6775c-2dc8-11e8-92ca-3053be24e348.jpg)
![content-feedback-individual-images-04](https://user-images.githubusercontent.com/19935974/37782261-d9e1d11a-2dc8-11e8-86b0-c542e58abd2e.jpg)
![content-feedback-individual-images-05](https://user-images.githubusercontent.com/19935974/37782262-d9ed1c1e-2dc8-11e8-88b5-f5bb35ae8a0e.jpg)


@billygriffin Note that we left out any mention of the OPA document. The 2 big issues that are also noted (in more detail) in the OPA doc are form length and form language. It felt awkward shoving that in but we can figure a place for it if needed.

**Comment by billygriffin** [comment]
Wow, this is awesome @Jay-Neighbours-I72! Looks amazing and very clear. A few minor pieces of feedback.

Slide 1: The first sentence seems to be missing a "with" between lines 1 and 2 under How we collected this feedback

Slide 2: I might consider adding a third suggestion that's something to the effect of "Provide examples that make it obvious what the question is getting at without leading the applicant."

Slide 3: Consider putting the "Initial only" in quotes in "People assumed the Initial only checkbox..."

Slide 4: Maybe "overwhelmed by" instead of "overwhelmed with."

**Comment by Jay-Neighbours-I72** [comment]
Updated PDF and jpgs with tweaks and specific examples added. @billygriffin 

[content-feedback.pdf](https://github.com/truetandem/e-QIP-prototype/files/1856178/content-feedback.pdf)

![content-feedback-individual-images-01](https://user-images.githubusercontent.com/19935974/38032731-5b69491e-326c-11e8-98df-daeb5e2fff9c.jpg)
![content-feedback-individual-images-02](https://user-images.githubusercontent.com/19935974/38032732-5b785b98-326c-11e8-846c-6173681f4fe1.jpg)
![content-feedback-individual-images-03](https://user-images.githubusercontent.com/19935974/38032733-5b83af16-326c-11e8-858d-0c64f39e56e9.jpg)
![content-feedback-individual-images-04](https://user-images.githubusercontent.com/19935974/38032734-5b9348d6-326c-11e8-8b6c-e6b7ab052ba5.jpg)
![content-feedback-individual-images-05](https://user-images.githubusercontent.com/19935974/38032735-5ba5f904-326c-11e8-82ad-7f17b8156e54.jpg)
![content-feedback-individual-images-06](https://user-images.githubusercontent.com/19935974/38032736-5bb113fc-326c-11e8-869f-089d07f89dd7.jpg)

**Comment by Jay-Neighbours-I72** [comment]
@billygriffin ^Updated with section locations.

**Comment by Jay-Neighbours-I72** [comment]
submitted for final review
