### ISSUE TITLE
Applicant Finances Delinquent Payments Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#276]
As an applicant I want to enter my delinquent payment information if I have any so that I can specify the details and circumstances surrounding my delinquent payments and my investigators can review the information

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
  - Provide the name of agency/organization/individual to which debt is/was owed.
    - [x] Free-text		
  - Provide the associated loan / account number(s) involved.	
    - [x] Free-text		
  - Identify/describe the type of property involved (if any).	
    - [x] Multi-line free text
  - Provide the amount (in U.S. dollars) of the financial issue.
    - [x] Amount		
    - [x] Estimated - Check		
  - Provide the reason(s) for the financial issue.
    - [x] Multi-line free text
  - Provide the current status of the financial issue.
    - [x] Multi-line free text
  - Provide the date the financial issue began.
    - [x] Date - M/Y Est
    - [x] Month and Year and specify if the date is an Estimate			
  - Provide date the financial issue was resolved.	
    - [x] Date - M/Y Est Free-text
    - [x] Month and Year and specify if the date is an Estimate	
    - [x] Not Resolved - Check	
    - [x] Must enter a date unless "not resolved" is checked
  - Provide the name of the court involved.
    - [x] Free-text		
  - Provide the address of the court involved.
    - [x] Address - With Country Option
    - [x] Provide Street and City
    - [x] State and Zip - or - Country are required
  - Provide a description of any action(s) you have taken to satisfy this debt (such as withholdings, frequency and amount of payments, etc.). If you have not taken any provide explanation.
    - [x] Multi-line free text
  - Other than previously listed, are there any other instances of the following occurrences?
    - **In the last seven (7) years** you have been delinquent on alimony or child support payments.
    - **In the last seven (7) years** you had a judgment entered against you. (Include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - **In the last seven (7) years** you had a lien placed against your property for failing to pay taxes or other debts. (Include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - You are currently delinquent on any Federal debt. (Include financial obligations for which you are the sole debtor, as well as those for which you are a cosigner or guarantor).
      - If yes use the button below to add another delinquent payment detail
        - [x] "Add another payment issue" button - adds another payment issue section - [Add Payment Issue](https://github.com/truetandem/e-QIP-prototype/issues/276) 
      - If no select no below and continue
        - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![screen shot 2017-01-18 at 12 39 29 pm](https://cloud.githubusercontent.com/assets/5938731/22075765/50a809bc-dd7b-11e6-8dec-e25e920407e1.png)
