### ISSUE TITLE
Applicant Finances Non-Payment Consequence Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#278]
As an applicant I want to enter my non-payment or excessive late payment information if I have any so that I can specify the details and circumstances surrounding my non-payment or excessive late payment information can review the information. 

Acceptance Criteria
- Form Fields (all fields required unless specified otherwise)
	- Provide the name of agency/organization/individual to which debt is/was owed.
		- [x] Free-text
	- Provide the associated loan/account number(s) involved.
		- [x] Free-text
	- Identify/describe the type of property involved (if any).
		- [x] Multi-line free-text	
	- Provide the amount (in U.S. dollars) of the financial issue.
		- [x] Amount	
		- [x] Estimated - Check - Optional
	- Provide the reason(s) for the financial issue.
		- [x] Multi-line free-text	
	- Provide the current status of the financial issue.
		- [x] Multi-line free-text	
	- Provide date the financial issue was resolved.
		- [x] Date - M/Y Est
		- [x] Month and Year and specify if the date is an Estimate
		- [x] Not resolved - Check - Optional
	- Provide the date the financial issue began
		- [x] Date - M/Y Est
		- [x] Month and Year and specify if the date is an Estimate
	- Provide a description of any action(s) you have taken to satisfy this debt (such as withholdings, frequency and amount of payments, etc.). If you have not taken any action(s) provide explanation.
		- [x] Multi-line free-text	
  - Other than previously listed, are there any other instances of the following occurrences?
    - **In the last seven (7) years** you had any possessions or property voluntarily or involuntarily repossessed or foreclosed. (include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - **In the last seven (7) years** you defaulted on any type of loan, (Include financial obligations for which you were the sole debtor,as well as those for which you were a cosigner or guarantor).
    - **In the last seven (7) years** you had bills or debts turned over to a collection agency. (Include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - **In the last seven (7) years** you had any account or credit card suspended, charged off, or cancelled for failing to pay as agreed.(Include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - **In the last seven (7) years** you have been evicted for non-payment.
    - **In the last seven (7) years** you had your wages, benefits, or assets garnished or attached for any reason.
    - **In the last seven (7) years** you have been over 120 days delinquent on any debt not previously entered. (Include financial obligations for which you were the sole debtor, as well as those for which you were a cosigner or guarantor).
    - You are currently over 120 days delinquent on any debt. (Include financial obligations for which you are the sole debtor, as well as those for which you are a cosigner or guarantor).
      - If yes use the button below to add another non-payment or excessive late payment payment detail
        - [x] "Add another non-payment or excessive late payment" button - adds another payment issue section - [Add Payment Issue](https://github.com/truetandem/e-QIP-prototype/issues/278) 
      - If no select no below and continue
        - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
