### ISSUE TITLE
Country list drop down - enhancement 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2797]
A few users have expected to type US for (United States), England, etc.

Can we append a few things to United States and United Kingdom in the list?

Desired would be:
 - [x] United States (~~US~~, USA)
 - [x] United Kingdom (UK)
 - [x] United Arab Emirates (UAE) 

That way when users type US the United States option will be a suggestion etc.

cc @bpdesigns

**Comment by bmallred** [comment]
Removing the **US** option since typing the "US" will also hit on the **USA** code

**Comment by Jay-Neighbours-I72** [comment]
Per email with Donna:
This update is approved.

**Comment by Jay-Neighbours-I72** [comment]
lgtm!
