### ISSUE TITLE
Test form submissions to eQIP test/integration

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2827]
As a eApp developer I want to test submitting data in all fields of the eApp online application form to the eQIP test/integration site via web service so that I can validate that the data submits without error.

Acceptance Criteria
- [x] Create basic write-up explaining the test process (e.g. put data in form, run script to extract JSON, submit package to eQIP, etc.).  See #2850 
- [x] Show Sections/sub-sections that have been tested.  See #2850 
- [ ] ~~Verify all form data submits without error~~*

**Note: remaining fields will need to be pushed to new sprint/issue*

**Comment by pjsumm** [comment]
Issue #2850 Webservice eQIP Integration, provides insight into the test procedures in use and the sections that have been implemented/tested.

**Comment by pjsumm** [comment]
Remaining work will be tracked against #2876
