### ISSUE TITLE
Timeout Warning

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2830]
As an eApp applicant I want to see a warning message letting me know that my session is about to timeout so that I can keep my session alive if I'm in the middle of a lengthy task.

Acceptance Criteria
- [ ] Implement warning message notifying users session is about to timeout.  
- [ ] Show message 1 minutes before time out (confirm timing)
- [ ] Work with design team in-browser to derive a usable design
- [ ] Approve design with 18f design team

**Comment by Jay-Neighbours-I72** [comment]
Notes:
Notification will come in at 14 minutes and save will be forced.
Notification will take over full screen and user must acknowledge they are still working.
If they acknowledge the 15 minute timeout timer is reset.

**Comment by Jay-Neighbours-I72** [comment]
Notification style:
![timeout-warning](https://user-images.githubusercontent.com/19935974/38390274-d15e5f14-38ee-11e8-9db6-8e559db92b42.jpg)

Logout message update:
![screen shot 2018-04-05 at 2 03 02 pm](https://user-images.githubusercontent.com/19935974/38390293-e14f6846-38ee-11e8-86b6-1fafa39fcbef.jpg)

@bpdesigns thoughts on the logout message text?

**Comment by bpdesigns** [comment]
Like the notification page. 

On the logout screen:
- I would remove the sentence welcoming people to the survey in the banner and make "1 minute" and "xx:xx" stand out in some way, maybe be bold and/or blue.

**Comment by Jay-Neighbours-I72** [comment]
Rework of logged out screen:
![screen shot 2018-04-06 at 10 56 58 am](https://user-images.githubusercontent.com/19935974/38428593-27e4337c-398a-11e8-9260-2be2936238fe.jpg)
