### ISSUE TITLE
Data loading message

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2831]
As an eApp applicant when I access the eApp form that already contains data I want to see a data loading message to inform me that my data is there, but needs to load, so that I do not get confused or concerned when I access the form and my data is not initially shown.

Acceptance Criteria
- [x] Create a data loading message/form state so it is evident to users that their data is loading in the form and not missing
- [x] Work with the design team to derive an accessible/usable design
- [x] Approve design with the 18f design team

**Comment by bpdesigns** [comment]
@Jay-Neighbours-I72 can you post the mockup or screenshot for this design here?

**Comment by bmallred** [comment]
@bpdesigns @Jay-Neighbours-I72 this was in-browser mock-up wasn't it? @bpdesigns would you like us to post screenshots here?

**Comment by bpdesigns** [comment]
That would be great. Thanks

**Comment by bpdesigns** [comment]
thanks @bmallred
