### ISSUE TITLE
Data persistence automated verification

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2877]
As an eApp developer I want to write automated test procedures to ensure that data submitted via eApp is properly persisted in the PostgreSQL database so that I have confidence that users can return to their form and see all data they previously entered. 

Acceptance Criteria:
- [ ] There should be at least one Selenium-driven test that populates the most commonly used sections of the form, saves data repeatedly.
- [ ] There should be a Selenium-driven test that forces a read back data from db after logout and log back in, and verifies each field is what was expected. 
- [ ] Automated tests should be run against IE11, Chrome, and Edge.
