### ISSUE TITLE
Address verification workshop

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2880]
As an eApp designer I want to address issues with the address verification timing that occur when users make changes to the address so that users do not interact with other parts of the form before verification occurs.

Acceptance Criteria
- [ ] Hold workshops with design and dev teams to derive solution(s) to verification timing
- [ ] Solution(s) prevent users from moving on to other components 
- [ ] Approve rework with 18f and Product Owner

**Comment by bmallred** [comment]
A good suggestion by @Jay-Neighbours-I72 was to potentially treat addresses which **can** be validated but **are not** validated as errors. This issue does not track that but is **strongly** encouraged.
