### ISSUE TITLE
Applicant Finances Bankruptcy Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#297]
As an applicant I want to see a summary listing of bankrupty data I've entered so that I can see all related bankruptcy data entries, reopen and edit specific entries, or remove an entry. 

Acceptance Criteria
- Summary of Bankruptcies
	- [x] Shown only if data has been entered on the Bankruptcy details form
	- [x] Dates of bankruptcy: Read-Only label
	- [x] Court Location: Read-Only label
	- [x] Action: Edit - Goes to the bankruptcy data entry section
	- [x] Action: Delete - Removes the summarized bankruptcy entry
- [x] Easily toggle between high-level summary data and detail data
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why
