### ISSUE TITLE
Applicant Finances Gambling Debt Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#298]
As an applicant I want to see a summary listing of gambling debt data I've entered so that I can see all related gambling debt data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of gambling debt
	- [x] Shown only if data has been entered on the gambling debt details form
	- [x] Amount of losses: Read-Only label
	- [x] Dates of problem: Read-Only label
	- [x] Action: Edit - Goes to the gambling debt data entry section
	- [x] Action: Delete - Removes the summarized gambling debt entry
- [x] Easily toggle between high-level summary data and detail data
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why
