### ISSUE TITLE
Applicant Finances Tax Filing/Payment Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#299]
As an applicant I want to see a summary listing of tax filing/payment issue data I've entered so that I can see all related tax filing/payment issue data entires, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of Failure to File or Pay Taxes
  - [x] Shown only if a tax issues has been entered
  - [x] Listing of each tax issue that has been provided
  - [x] For each tax/filing payment summary provide:
    - [x] Year taxes not paid: Read-Only label
    - [x] Agency: Read Only label
    - [x] Action: 
      - [x] Edit - goes to tax filing issue information data entry section
      - [x] Delete - Removes the tax filing issue entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
