### ISSUE TITLE
Feature Spec Testing

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#302]
As an eApp developer I want to research feature spec testing options so the I can create an example utilizing a framework to facilitate feature testing.

Acceptance Criteria
- [x] Select a feature spec framework
- [x] Determine the syntax to use in feature specs
- [x] Create an example utilizing the framework and specs from a User Story
- [x] Review example framework and syntax with the 18f PMO
- [x] Receive approval for planned direction and syntax from 18f PMO
