### ISSUE TITLE
Applicant Finances Employer Card Abuse Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#305]
As an applicant I want to see a summary listing of corporate credit card abuse issues I've entered so that I can see all related corporate credit card abuse data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of Employer Travel or Credit Card Violations
  - [x] Shown only if a credit card abuse/violation entry has been provided
  - [x] Listing of each credit card abuse/violation has entered
    - [x] Date of violation: Read-Only label 
    - [x] Name of employer: Read-Only label
      - [x] Actions:
        - [x] Edit - goes to employer credit card abuse/violation entry section
        - [x] Delete - Removes the credit card abuse/violation entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
