### ISSUE TITLE
Applicant Finances Credit Counseling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#306]
As an applicant I want to see a summary listing of all personal credit counseling data I've entered so that I can see all related personal credit counseling data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of Financial Assistance
  - [x] Shown only if counseling service entry has been provided
  - [x] Listing of each credit counseling service entry the applicant has entered
  - [x] For each credit counseling service entry show the following summary fields: 
    - [x] Name of Service: Read-Only label
    - [ ] ~~Date of Service: Read-Only label~~
    - [x] Actions:
      - [x] Edit - goes to personal credit counseling information entry section
      - [x] Delete - Removes the personal credit counseling information entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
