### ISSUE TITLE
Applicant Places Lived Add Address

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#325]
As an eApp applicant I want to add an address to the SF-86 form so that I can show places where I have lived over the past 10 years. 

Acceptance Criteria
- Add Address 
	- [ ]  Provide Field Help: 
List the places where you have lived beginning with your present residence and working back 10 years. Residences for the entire period must be accounted for without breaks. Indicate the actual physical location of your residence, not a Post Office box or a permanent residence when you
were not physically located there. If you split your time between one or more residences during a time period, you must list all residences. Do not list residence before your 18th birthday unless to provide a minimum of 2 years residence history.
You are not required to list temporary locations of less than 90 days that did not serve as your permanent or mailing address.
For any address in the last 3 years, provide a person who knew you at that address, and who preferably still lives in that area. Do not list people who knew you for residences completely outside this 3 year period, and do not list your spouse, cohabitant or other relatives as the verifier for periods of residence.
	- [ ] Action: Add Address - navigates the user to the Address Details form section
- Add Optional Comment
	- [ ] Optional - show only if needed
	- [ ] Help - "Note: If you need to provide any additional comments about this information, enter them below."
	- [ ] Multiline free-text
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Legacy view

![selection_225](https://cloud.githubusercontent.com/assets/5938731/22299640/eaf60114-e2f2-11e6-9ae8-9264dc5ba160.png)
