### ISSUE TITLE
Applicant Places Lived Address Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#327]
As an eApp applicant I want to enter the address of a place I've lived along with the dates I lived there and whether I owned, rented, was there for military, or other reason so that I can complete the places I've lived.

Acceptance Criteria
- Fields
	- Provide dates of residence. (date range with Present)
		- [x] Date Range - Est/Present
		- [x] Validation - For an Address within the last 3 years 
			- [x]  **Branch** to add someone who knows you at that location
	- Is/was this residence: 
		- [x] Selection: "Owned by you", "Rented or leased by you", "Military housing", "Other (Provide explanation)"
		- [x] Explanation - Free-Text
	- Provide the street address.
		- [x] Address - With Country Option
		- [x] Provide Street and City
		- [x] State and Zip - or - Country are required
    		- [x] Validation - For an APO/FPO Address 
			- [x] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [x] **Branch** to APO/FPO Location Details
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Legacy
![selection_246](https://cloud.githubusercontent.com/assets/5938731/22552210/f5159b80-e925-11e6-8c3d-352e1f21cf7b.png)

**Comment by floresj** [comment]
![selection_247](https://cloud.githubusercontent.com/assets/5938731/22552264/29a199da-e926-11e6-8341-5fec7e340795.png)

**Comment by pjsumm** [comment]
Spoke with Billy G. and he agreed we should remove the **Optional Comments** field references from the acceptance criteria and create and issue to track the design discussion: Issue [#460](https://github.com/truetandem/e-QIP-prototype/issues/460)
