### ISSUE TITLE
Applicant Places Lived APO/FPO Address Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#328]
As an eApp applicant I want to enter an APO/FPO address so that I can provide a street address, base, post, embassy, unit, and country location or home port/fleet headquarter.

Acceptance Criteria
- Form Section Help: You have indicated an APO/FPO address. Provide physical location data with street address, base, post, embassy, unit, and country location or home port/fleet headquarter.
- Fields
	- Provide physical location data 
		- [ ]  Street Address/Unit/Duty Location  
		- [ ]  City or Post Name   
		- [ ]  Provide State for ports in United States, or Country location.  
		- [ ]  State
		- [ ]  Zip Code 
		- [ ]  Country
	- Add Optional Comment
		- [ ]  Optional - show only if needed
		- [ ]  Help - "Note: If you need to provide any additional comments about this information, enter them below."
		- [ ]  Multiline free-text
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
