### ISSUE TITLE
Applicant Places Lived People Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#329]
As an eApp applicant for places I've lived in the last 3 years I want to enter the name and contact information for someone who knows I lived at that location so that my investigator can reach out to this people for verification and character reference. 

Acceptance Criteria
- Form Section Label: Person Who Knew you (if address dates within last 3 years)
- Fields
	- Provide the name of a neighbor, landlord (if rental), or other person who knows you at this address.
		- [x] Provide the full name - Name block
	- Provide date of last contact:
		- [x] Date - Est
	- Provide your relationship to this person (check all that apply)
		- [x] Select: "Neighbor", "Friend", "Landlord", "Business associate", "Other (Provide explanation)" 
		- [x] Explanation: Multiline Free Text
	- Provide the following contact information for this person :
		- [x] Telephone block - evening, daytime, cell/mobile 
	- Provide e-mail address for this person:
		- [x] Email (Free Text) I don’t know 
	- Provide street address for this person (including apartment number).
		- [x]  Address - With Country Option
 			- [x] Provide Street and City
 			- [x] State and Zip - or - Country are required
		- [x] Validation - For an APO/FPO Address
 			- [x] If State = AA, AE, or AP Then City must be = APO or FPO
 			- [x] **Branch** to APO/FPO Location Details
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@pjsumm the design comps do not have the optional comment(s) per item. Should this be amended or just part of the discussion on #403?

**Comment by pjsumm** [comment]
Spoke with Billy G. and he agreed we should remove the **Optional Comments** field references from the acceptance criteria and create and issue to track the design discussion: Issue [#460](https://github.com/truetandem/e-QIP-prototype/issues/460)
