### ISSUE TITLE
Applicant Places Lived Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#330]
As an eApp Applicant I want to see a summary of the addresses that I have entered so that I can easily see all related places I've lived, identify any gaps in places I've lived for the last 10 years, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Show how many years have been covered
	- [ ] Validation: ensure at least 10 years of residence covered without gaps
- Summary of where you have lived
	- Shown only if there are places entered. For each place\address show the following summary fields: 
		- [ ] Time period: Read-Only label
		- [ ] Street: Read-Only label
		- [ ] City: Read-Only label
		- [ ] Action: Edit - go to place address information entry section
		- [ ] Action: Delete - remove an address entry from the list
- Add Optional Comment
	- [ ] Optional - show only if needed
	- [ ] Help - "Note: If you need to provide any additional comments about this information, enter them below."
	- [ ] Multiline free-text
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![selection_248](https://cloud.githubusercontent.com/assets/5938731/22552655/d79642f6-e927-11e6-8e6f-bb521365b8f5.png)
