### ISSUE TITLE
Applicant Education History Add School

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#333]
As an eApp applicant I want to add schools I've attended in the last 10 years and specify the name, address, and type of school I attended and the dates in which I attended the school so that my enrollment can be verified.

Acceptance Criteria 
- [x] Form help - Do not list education before your 18th birthday, unless to provide a minimum of two years education history.
- Fields
	- Have you attended any schools in the last 10 years?
		- [x] Yes / No option
		- [x] **Branch** 
			- [x] For No, go to next form section 
			- [x] For Yes, provide fields to enter school information
	- Provide the dates of attendance 
		- [x] Date Range - Est/Present
		- [x] Validation - For an school attended within the last 3 years 
			- [x]  **Branch** add someone who knows you at that school. _See Epic:_ [#335](https://github.com/truetandem/e-QIP-prototype/issues/335)
	- Select the most appropriate code to describe your school: 
		- [x] Choice: High School; College/University/Military College; Vocational/Technical/Trade School; Correspondence/Distance/Extension/Online School
 	- Provide the name of the school:    
		- [x] Free-text
	- Provide the street address of the school. 
		- [x] Field Help: For correspondence/distance/extension/online schools, provide the address where the records are maintained 
		- [x] Address - With Country Option
		- [x] Provide Street and City
		- [x] State and Zip - or - Country are required 
	- Action - Add another school
		- [x] Add button - appends another school data entry section
	- Action - Remove school
		- [x] Remove button - removes the respective school entry
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![selection_272](https://cloud.githubusercontent.com/assets/5938731/22993327/a12817bc-f390-11e6-8f9d-e04ba799c69e.png)

![selection_273](https://cloud.githubusercontent.com/assets/5938731/22993343/ac36c36a-f390-11e6-91b0-c8f3dc454601.png)

![selection_274](https://cloud.githubusercontent.com/assets/5938731/22993349/b3e8a466-f390-11e6-952f-2bf58579e6ed.png)

![selection_275](https://cloud.githubusercontent.com/assets/5938731/22993362/bd481582-f390-11e6-98a2-f86742e58731.png)
