### ISSUE TITLE
Applicant Education History Person Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#335]
As an eApp applicant for schools I've attended in the last 3 years I want to enter the name and contact information for someone whom I attended the school with so that my investigator can reach out to this person for verification and character reference.

Acceptance Criteria
- [x] Form Help: For schools you attended in the last 3 years, list a person who knew you at the school (instructor, student, etc.). Do not list people for education periods completed more than 3 years ago. For correspondence/distance/extension/online schools, list someone who knew you while you received this education.
- Fields
	- Provide the name of person who knows/knew you at school 
		- [x] Check: I don't know 
		- [x] First Name - Initial Only/No First Name
		- [x] Last Name
 	- Provide current address for this person (including apartment number) 
		- [x] Address - With Country Option
		- [x] Provide Street and City
		- [x] State and Zip - or - Country are required 
	- Provide telephone number for this person 
		- [x] Telephone block: day, night, both
	- Provide email address for this person:  
		- [x] Check: I don't know 
		- [x] Free-text: use e-mail formal validator
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
