### ISSUE TITLE
Applicant Education History Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#336]
As an eApp applicant I want to see a summary of the schools that I have entered into the eApp online form, the time period in which I attended them, and any degrees/diplomas I attained while at the school so that I can easily identify any gaps in my education history for the last 10 years, and reopen/edit specific school entries and degree/diploma, or remove a school or degree/diploma.

Acceptance Criteria
- Fields
	- **Summary of Where you Went to School**
		- [ ] Show a total count of schools attended in the past 10 years
		- [ ] Show a total count of degrees/diplomas attained in the past 10 years
	- **Summary of Your History** (Your History accordion control line items): 
		- [ ] **School** line items
			- [ ] For each school entered - have a line item with these summary fields: 
				- [ ] Name of School: Read-Only label
				- [ ] Time Period: Read-Only label
				- [ ] Action: 
					- [ ] Expand - expand the school details to show school data entry fields for edit
		- [ ] **Degree/Diploma** line items
			- [ ] For each degree/diploma entered - have a line item with this summary field: 
				- [ ] Degree/Diploma: Read-Only label
				- [ ] Actions: 
					- [ ] Expand - expand the degree/diploma details to show  degree/diploma data entry fields for edit
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
![selection_276](https://cloud.githubusercontent.com/assets/5938731/22993479/2d0d2876-f391-11e6-82b7-466a21382321.png)
