### ISSUE TITLE
Applicant Education History Add Degree

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#337]
As an eApp applicant I want to add degrees/diplomas that I've received at a given school so that I can show the results of my schooling.

Acceptance Criteria
- Fields
  - Did you receive a degree/diploma?
    - [ ] Yes/No option
      - [ ] **Branch** - No
        - [ ] Have you received a degree or diploma more than 10 years ago?
          - [ ] Yes/No Option 
      - [ ] **Branch** - Yes
         - [ ] Provide fields to enter degree/diploma information
      - [ ] Provide type of degrees(s)/diploma(s) received 
        - [ ] Select one: High School Diploma; Associate’s; Bachelor’s; Master’s; Doctorate; Professional Degree (e.g. MD, DVM, JD); Other
        - [ ] **Branch**
          - [ ] Other degree/diploma - Optional, shown only if "Other" selected
          - [ ] Multi-line free-text 
      - [ ] Date(s) awarded:
        - [ ] Date: Month/Year Est
     - [ ] Action - Add another degree/diploma
       - [ ] Add button - appends another degree/diploma data entry section
     - [ ] Action - Remove degree/diploma
       - [ ] Remove button - removes the respective degree/diploma entry
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
