### ISSUE TITLE
Applicant Employment History Add Job

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#341]
As an eApp applicant I want to add a job/employment activity, explanation, and date range of employment for each job in my previous 10 years so that I can branch to the appropriate job details page and provide details of my respective work experience.

Acceptance Criteria
- Field Help:
	- [x] List all of your employment activities, including unemployment and self-employment, beginning with the present and working back 10 years. The entire period must be accounted for without breaks. If the employment activity was military duty, list separate employment activity periods to show each change of military duty station.
	Do not list employment before your 18th birthday unless to provide a minimum of 2 years employment history.
- Fields
	- Select your employment activity 
		- [x] **Select:** Active military duty station; National Guard/Reserve; USPHS Commissioned Corps; Other Federal employment; State Government (Non-Federal employment); Self-employment; Unemployment; Federal Contractor; Non-government employment (excluding self-employment); Other (Provide explanation) 
			- [x] **Branch 1:** Active Duty, National Guard/Reserve, or USPHS Commissioned Corps to military job details
			- [x] **Branch 2:** Other Federal employment, State Government, Federal Contractor, Non-government employment, or Other branch to job details
			- [x] **Branch 3:** Self-employment branch to self-employment details
			- [x] **Branch 4:** Unemployment branch to unemployment details
 	- Explanation
		- [x] Required when "other" selected
		- [x] Multiline free-text
	- Provide dates of employment 
		- [x] Date Range - Est/Present
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by pjsumm** [comment]
Spoke with Billy G. and he agreed we should remove the **Optional Comments** field references from the acceptance criteria and create and issue to track the design discussion: Issue [#460](https://github.com/truetandem/e-QIP-prototype/issues/460)

**Comment by floresj** [comment]
![selection_286](https://cloud.githubusercontent.com/assets/5938731/22994854/72a612ee-f396-11e6-8ad9-5f090dac6ca8.png)
![selection_285](https://cloud.githubusercontent.com/assets/5938731/22994860/72ae7790-f396-11e6-99a1-224b5dd4a6de.png)
![selection_284](https://cloud.githubusercontent.com/assets/5938731/22994856/72a9022e-f396-11e6-92a0-63f77bc62742.png)
![selection_283](https://cloud.githubusercontent.com/assets/5938731/22994853/72a60646-f396-11e6-85da-de660094f9ea.png)
![selection_282](https://cloud.githubusercontent.com/assets/5938731/22994855/72a8aa72-f396-11e6-8b4a-5dd7d94452f9.png)
![selection_281](https://cloud.githubusercontent.com/assets/5938731/22994857/72a9d834-f396-11e6-81c9-3a669d7cea22.png)
![selection_280](https://cloud.githubusercontent.com/assets/5938731/22994858/72aafd0e-f396-11e6-804c-e1587e0e0d6e.png)
![selection_279](https://cloud.githubusercontent.com/assets/5938731/22994859/72ac6482-f396-11e6-9e8a-35fcc85af01e.png)
![selection_278](https://cloud.githubusercontent.com/assets/5938731/22994862/72b23b82-f396-11e6-9533-d858e4c1fc30.png)
![selection_277](https://cloud.githubusercontent.com/assets/5938731/22994861/72b027b6-f396-11e6-8147-13450883a9b8.png)
