### ISSUE TITLE
Applicant Employment History Job Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#342]
As an eApp applicant I want to provide information for my job position including the title, status, and employer details such as the business name and contact information and additional periods of activity with that employer so that my employment history can be reviewed by my investigator.

Acceptance Criteria
- Fields
  - Provide most recent position title
    - [x] Free-text
  - Select the employment status for this position
    - [x] Select: Full-time; Part-time
  - Provide the name of your employer:    
    - [x] Free-text
  - Provide the address of employer 
    - [x] Address - With Country Option
    - [x] Provide Street and City
    - [x] State and Zip - or - Country are required 
  - Provide telephone number 
    - [x] Telephone block - day, night, both
  - Additional Periods of Activity with this Employer
    - [x] Provide additional periods of activity if you worked for this employer on more than one occasion at the same physical location. For example, if you worked at XY Plumbing in Denver, CO, during 3 separate periods of time, you would enter information concerning the most recent period of employment above, and provide dates, position titles, and supervisors for the two previous periods of employment as entries below.
    - [x] Not Applicable 
      - [x] Yes/No
      - [x] If Yes allow add; If No do not allow adding
    - [x] Dates of employment
      - [x] Date Range - Est/Present
    - [x] Position title
      - [x] Free-text
    - [x] Supervisor
      - [x] Free-text
    - [x] Add an Additional Period of Activity 
      - [x] Action for Add entry
      - [x] Action for Remove entry  
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@pjsumm the design comps do not have the optional comment(s) per item. Should this be amended or just part of the discussion on #403?

**Comment by pjsumm** [comment]
Spoke with Billy G. and he agreed we should remove the **Optional Comments** field references from the acceptance criteria and create and issue to track the design discussion: Issue [#460](https://github.com/truetandem/e-QIP-prototype/issues/460)
