### ISSUE TITLE
Applicant Employment History Job Physical Address

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#343]
As an eApp applicant I want to provide the address where I performed my job if that address is different from the employer's address so that is is clear where my job was actually performed. 

Acceptance Criteria
- Fields
	- Is/was your physical work address different than your employer's address?
		- [ ] Choose Yes/No
		- [ ] Action: Yes
			- [ ] **Branch**:  Add job's physical address/phone number 
	- Provide the work address where you are/were physically located 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required
    		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide telephone number 
		- [ ] Telephone block - day, night, both  
		- [ ] Allow international or DSN phone number 
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
