### ISSUE TITLE
Applicant Employment History Supervisor Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#344]
As an eApp applicant for a given job I want to provide my supervisor's name, position, email, phone, and address so that my performance and character at the work place can be evaluated by my investigator. 

Acceptance Criteria
- Fields
	- Provide the name of your supervisor:    
		- [x] Free-text
	- Provide the position title of your supervisor:    
		- [x] Free-text
	- Provide the email address of your supervisor:  
		- [x] Free-text
		- [x] email validation
		- [x] Option: I don't know 
  	- Provide the physical work location of your supervisor 
		- [x] Address - With Country Option
		- [x] Provide Street and City
		- [x] State and Zip - or - Country are required
    		- [x] Validation - For an APO/FPO Address 
			- [x] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [x] **Branch** to APO/FPO Location Details
	- Provide the telephone number for this supervisor 
		- [x] Telephone block - day, night, both  
		- [x] Allow international or DSN phone number 
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by pjsumm** [comment]
Spoke with Billy G. and he agreed we should remove the **Optional Comments** field references from the acceptance criteria and create and issue to track the design discussion: Issue [#460](https://github.com/truetandem/e-QIP-prototype/issues/460)
