### ISSUE TITLE
SSN verification style and/or functionality

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#376]
As an eApp Applicant I want to be prompted to verify my social security number so that I am assured that I've entered the data correctly.

Acceptance Criteria
- [x] After user enters social security number they are prompted to re-enter
- [x] Both numbers are compared for consistency, provided error if there is a difference 
- [x] Once verified the user will not be re-prompted to confirm unless they make a change to the field
- [x] When re-entering the form, and the SSN has already been verified, the user will not see the verification fields. 

Brought over from #294

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 @joeignition @bmallred 

"SSN verification style/functionality - Can this be a yes/no instead of re-typing their number?"

Have we decided if we're keeping the re-typing?

**Current**
![screen shot 2017-01-20 at 8 43 14 am](https://cloud.githubusercontent.com/assets/5938731/22151866/fc82c15a-deed-11e6-82b4-c05305ad06f8.png)

**Option 1 - Retype**
![screen shot 2017-01-20 at 8 51 08 am](https://cloud.githubusercontent.com/assets/5938731/22151845/e6d9b908-deed-11e6-9191-edc45d9d4e2b.png)

**Option 2 - Confirmation button**
![screen shot 2017-01-20 at 8 57 50 am](https://cloud.githubusercontent.com/assets/5938731/22151985/99236a1e-deee-11e6-946a-a83f07451c49.png)

**Comment by Jay-Neighbours-I72** [comment]
Option 2 is my preference, less of a burden on the user.

I'm not sure if the official decision was made yet. @billy22g do you know?

**Comment by billy22g** [comment]
Sheldon asked for people to confirm, and specifically mentioned re-typing. But he definitely did not consider this alternative, so I think it's worth putting in front of him before making the call. I suspect it'll be a 1 minute discussion and we'll do one or the other.

**Comment by billy22g** [comment]
Sheldon desires multiple entries. 

Initial direction is to have a confirm repeat field. Usability testing will determine whether we keep that or not.

**Comment by pjsumm** [comment]
Team reviewed and decided to add this to the product backlog for an upcoming sprint.  Need to decided which option to prototype, then usability test the results to validate direction.

**Comment by colinpmacarthur** [comment]
A couple things:

- [ ] Verification is misspelled in the question text.
- [ ] Is `verification` really the right word? That implies that we're doing some kind of behind the scenes check of the SSN.

cc: @billy22g

**Comment by bmallred** [comment]
What do we want to call it then? Confirmation?

@Jay-Neighbours-I72 @billy22g @colinpmacarthur

**Comment by colinpmacarthur** [comment]
I am all for `confirmation`!

**Comment by colinpmacarthur** [comment]
@bmallred The text all looks good to me, but I'm now seeing this odd behavior:

1. I enter my SSN
2. I enter a matching SSN in the confirmation field
3. After validation, the SSN confirmation fields disappear

I think it would be better if the confirmation SSN fields stayed around even after people entered a matching (valid) number.

**Comment by bmallred** [comment]
@colinpmacarthur when they everything is confirmed and they leave the section and come back should it be displayed there as well? Original direction was no and that is why it is not displayed after confirmation.

**Comment by colinpmacarthur** [comment]
Ah ok. Thoughts @billy22g ?

**Comment by bmallred** [comment]
Maybe something along the lines of by default it is displayed, but once it has been confirmed we replace the confirmation inputs with a message stating it has been verified?

## initial state

![initial](https://user-images.githubusercontent.com/697855/28837279-2db345b0-76ba-11e7-8a14-bba12a541613.png)

## providing the confirmation

![inprocess](https://user-images.githubusercontent.com/697855/28837287-37af3b0a-76ba-11e7-92bd-fb181505231b.png)

## confirmation message

![image](https://user-images.githubusercontent.com/697855/28837248-0f105152-76ba-11e7-8e6c-3032dba3ec5e.png)



cc: @Jay-Neighbours-I72 @billy22g @colinpmacarthur

**Comment by billy22g** [comment]
I think my preference is that the dual boxes are not around after the confirmation happens, but if the person *changes* it, then they must reconfirm. I like @bmallred's proposal directionally, but I'll have to see how it feels when implemented.

**Comment by bmallred** [comment]
@billy22g they confirmation portion already comes back once the original is in a dirty state. Just unsure about behavior when confirmed since we only store the original and a flag of whether it was confirmed or not.

**Comment by colinpmacarthur** [comment]
OK, let's plan on usability testing this one @bmallred. cc: @Jay-Neighbours-I72. I think we can move to done and let usability testing surface the issues.

**Comment by bmallred** [comment]
@colinpmacarthur sounds good. I'll move it back in to **review** when the PR for the text change is merged in!
