### ISSUE TITLE
Storyboard Address Verification

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#377]
As an eApp designer I want to create a design concept that illustrates ways that street addresses can be validated in-line as users are entering an address on the SF86 form so that the eApp developers can build a prototype that represents the design concept, and users can test the prototype to validate, or challenge, the design decisions.

Acceptance Criteria
- [ ] Create a Storyboard utilizing the current design standards representing the physical trait form fields
- [ ] Create address data validation design concepts like putting zip code first and proximity search for streets
- [ ] Review the storyboard/comp with 18f PMO and the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-app-address-block](https://cloud.githubusercontent.com/assets/19935974/22799407/ab6641ca-eed3-11e6-8af1-23414bfc737c.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-app-address-block.pdf](https://github.com/truetandem/e-QIP-prototype/files/764759/e-app-address-block.pdf)
