### ISSUE TITLE
Icons for Overview Page

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#378]
As an eApp designer I want to create icons to represent the types of section reviews (One piece at a time, Full section review) for the section overview pages so that users have a visual representation of the review concepts to assist them in understanding what the different section reviews types are. 

Acceptance Criteria
- [ ] Icon for "One piece at a time"
- [ ] Icon for "Full section review"
- [ ] Icons have been reviewed/approved by the 18f PMO
- [ ] Icons have been reviewed/approved by the Product Owner

**Comment by Jay-Neighbours-I72** [comment]
![e-app-review-icons-1](https://cloud.githubusercontent.com/assets/19935974/22563903/71b6f0a6-e950-11e6-91e9-67371ab6c80c.jpg)
![e-app-review-icons-2](https://cloud.githubusercontent.com/assets/19935974/22563904/71b7501e-e950-11e6-8bf8-4f35a9666f1d.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-app-review-icons.pdf](https://github.com/truetandem/e-QIP-prototype/files/764877/e-app-review-icons.pdf)
