### ISSUE TITLE
Storyboard Military History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#379]
As an eApp designer I want to create a design concept that illustrates the in-line branching for military history including the branch served in, discharge information, foreign military service and people from foreign military service to promote ease of use for users entering the data on the form and so that eApp developers can build a prototype that represents the design concept, and users can test the prototype to validate, or challenge, the design decisions.

Acceptance Criteria
- [ ] Create a Storyboard utilizing the current design standards
- [ ] Provide branching representation for branching in the military history form
- [ ] Review the storyboard/comp with the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-1](https://cloud.githubusercontent.com/assets/19935974/22834646/d9dbfe18-ef83-11e6-895e-f3f3dbf2ce48.jpg)
![e-app-comp-military-history-2](https://cloud.githubusercontent.com/assets/19935974/22834647/d9de0c62-ef83-11e6-905b-f3e2e22c630d.jpg)
![e-app-comp-military-history-3](https://cloud.githubusercontent.com/assets/19935974/22834650/d9e29e12-ef83-11e6-864d-2e9d29191e83.jpg)
![e-app-comp-military-history-4](https://cloud.githubusercontent.com/assets/19935974/22834651/d9e36d74-ef83-11e6-8427-a5a4ebebf6ef.jpg)
![e-app-comp-military-history-5](https://cloud.githubusercontent.com/assets/19935974/22834648/d9de6e46-ef83-11e6-849c-beccb05cda44.jpg)
![e-app-comp-military-history-6](https://cloud.githubusercontent.com/assets/19935974/22834649/d9deb658-ef83-11e6-9ef0-056312b4318c.jpg)
![e-app-comp-military-history-7](https://cloud.githubusercontent.com/assets/19935974/22834656/d9eeb526-ef83-11e6-9f1d-8263f5ee0362.jpg)
![e-app-comp-military-history-8](https://cloud.githubusercontent.com/assets/19935974/22834652/d9e9f90a-ef83-11e6-9ff0-52b00ff98b1f.jpg)
![e-app-comp-military-history-9](https://cloud.githubusercontent.com/assets/19935974/22834653/d9ea1d22-ef83-11e6-87f0-7f464062b7ef.jpg)
![e-app-comp-military-history-10](https://cloud.githubusercontent.com/assets/19935974/22834654/d9eaec20-ef83-11e6-89cd-ca9a8f4f4d10.jpg)
![e-app-comp-military-history-11](https://cloud.githubusercontent.com/assets/19935974/22834657/d9f2a71c-ef83-11e6-9f81-b08a6a80c403.jpg)
![e-app-comp-military-history-12](https://cloud.githubusercontent.com/assets/19935974/22834655/d9edfcbc-ef83-11e6-9917-6e7b21d8a36b.jpg)
![e-app-comp-military-history-13](https://cloud.githubusercontent.com/assets/19935974/22834660/d9f8ae82-ef83-11e6-8967-c6752a095cb5.jpg)
![e-app-comp-military-history-14](https://cloud.githubusercontent.com/assets/19935974/22834658/d9f7f230-ef83-11e6-90b7-97b4f265eca2.jpg)
![e-app-comp-military-history-15](https://cloud.githubusercontent.com/assets/19935974/22834659/d9f8f996-ef83-11e6-959b-563e0b03a0a1.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-APP-comp-military-history.pdf](https://github.com/truetandem/e-QIP-prototype/files/767205/e-APP-comp-military-history.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-1](https://cloud.githubusercontent.com/assets/19935974/22900606/f5c5a996-f1fc-11e6-9f76-497e4884a787.jpg)
![e-app-comp-military-history-2](https://cloud.githubusercontent.com/assets/19935974/22900610/f5d10d4a-f1fc-11e6-8f42-fc3581a4ea73.jpg)
![e-app-comp-military-history-3](https://cloud.githubusercontent.com/assets/19935974/22900609/f5cf91cc-f1fc-11e6-8986-5f5f128defd1.jpg)
![e-app-comp-military-history-4](https://cloud.githubusercontent.com/assets/19935974/22900608/f5cdc39c-f1fc-11e6-81bd-b135613aacb5.jpg)
![e-app-comp-military-history-5](https://cloud.githubusercontent.com/assets/19935974/22900611/f5d376b6-f1fc-11e6-9058-3171db54e1f0.jpg)
![e-app-comp-military-history-6](https://cloud.githubusercontent.com/assets/19935974/22900607/f5cd24b4-f1fc-11e6-9884-a30ef0eba6f2.jpg)
![e-app-comp-military-history-7](https://cloud.githubusercontent.com/assets/19935974/22900612/f5d61db2-f1fc-11e6-8786-7b7f4f204cb5.jpg)
![e-app-comp-military-history-8](https://cloud.githubusercontent.com/assets/19935974/22900615/f5e2f28a-f1fc-11e6-9e4b-8603f0402b91.jpg)
![e-app-comp-military-history-9](https://cloud.githubusercontent.com/assets/19935974/22900613/f5d9c296-f1fc-11e6-8deb-12e6a31dec0c.jpg)
![e-app-comp-military-history-10](https://cloud.githubusercontent.com/assets/19935974/22900619/f5f5a9b6-f1fc-11e6-9c25-e1e3c82b5b83.jpg)
![e-app-comp-military-history-11](https://cloud.githubusercontent.com/assets/19935974/22900620/f61ee524-f1fc-11e6-941c-f73316a3c3cf.jpg)
![e-app-comp-military-history-12](https://cloud.githubusercontent.com/assets/19935974/22900614/f5dd33cc-f1fc-11e6-9af9-0f921a1686d8.jpg)
![e-app-comp-military-history-13](https://cloud.githubusercontent.com/assets/19935974/22900616/f5e2eab0-f1fc-11e6-8a29-31c3d633e8b0.jpg)
![e-app-comp-military-history-14](https://cloud.githubusercontent.com/assets/19935974/22900618/f5eb615e-f1fc-11e6-9f48-c92e6f516822.jpg)
![e-app-comp-military-history-15](https://cloud.githubusercontent.com/assets/19935974/22900617/f5e4963a-f1fc-11e6-8f95-9732c7529b18.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-APP-comp-military-history.pdf](https://github.com/truetandem/e-QIP-prototype/files/772251/e-APP-comp-military-history.pdf)
