### ISSUE TITLE
Applicant Employment History Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#410]
As an applicant I want to see a summary listing of employment activity data I've entered so that I can see my employment history timeline and ensure there are no gaps in my 10 year employment history, and I can edit specific employment entries, or remove an entry.

Acceptance Criteria
- Summary of Your Employment Activities (table)
	- [x] Shown only if data has been entered on the Employment Activity details form
	- [x] Time Period: Read-Only label
	- [ ] ~Type of Employment: Read-Only label~
	- [x] Action: Edit - Goes to the employment data entry section
	- [x] Action: Delete - Removes the employment entry
	- [x] Easily toggle between high-level summary data and detail data
- [x] Provide visual indicator showing years where employment history is covered
- [x] Warn the user when there are gaps in employment history for 10 years
- [x] Allow for 30 days between jobs when calculating gaps
- [x] For employment before 18th birthday allow minimum 2 years employment history instead of 10
- [x] Show the user confirmation that there are no gaps in employment history for 10 years
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by pjsumm** [comment]
Created this new story because this summary story and the [Add Employment](https://github.com/truetandem/e-QIP-prototype/issues/341) user story had gotten mixed up during sprint planning.
