### ISSUE TITLE
Applicant Employment History Military Job Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#411]
As an eApp applicant I want to provide information for jobs I performed while I was in the military including my status, rank, and information regarding the duty station including name, address, and phone number so that my military employment history can be reviewed by my investigator.

Acceptance Criteria
- Fields
	- Select the employment status for this position
		- [ ] Select: Full-time; Part-time
	- Provide your assigned duty station during this period
		- [ ] Free-text
	- Provide your most recent rank/position title    
		- [ ] Free-text
	- Provide the address of duty station 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required 
    		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide telephone number 
		- [ ] Telephone block - day, night, both
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
