### ISSUE TITLE
Applicant Employment History Military Job Supervisor

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#412]
As an eApp applicant for a given military job I want to provide my supervisor's name, position/rank, email, phone, and address so that my performance and character at the work place can be evaluated by my investigator. 

Acceptance Criteria
- Fields
	- Provide the name of your supervisor    
		- [ ] Free-text
	- Provide the rank/position title of your supervisor    
		- [ ] Free-text
	- Provide the email address of your supervisor
		- [ ] Free-text
		- [ ] email validation
		- [ ] Option: I don't know 
  	- Provide the physical work location of your supervisor 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required
    		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide supervisor telephone number
		- [ ] Telephone block - day, night, both  
		- [ ] Allow international or DSN phone number 
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
