### ISSUE TITLE
Applicant Employment History Self-Employment Job Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#413]
As an eApp applicant I want to provide information for self-employment positions including the title, status, and employment details such as the employment name, address, and phone number and physcial location where I performed the work during that employment if it was different than the employment address so that my self-employment history can be reviewed by my investigator.

Acceptance Criteria
- Fields
	- Provide most recent position title
		- [ ] Free-text
	- Select the employment status for this position
		- [ ] Select: Full-time; Part-time
	- Provide the name of your employment:    
		- [ ] Free-text
	- Provide the address of employment 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required 
	- Provide telephone number 
		- [ ] Telephone block: day, night, both
	- Is/was your physical work address different than your employer's address?
		- [ ] Choose Yes/No
		- [ ] Action: Yes
		- [ ] **Branch**:  Add job's physical address/phone number 
	- Provide the work address where you are/were physically located 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required
  		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide telephone number 
		- [ ] Telephone block - day, night, both  
		- [ ] Allow international or DSN phone number 
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
This should have a `Reference` as well.
