### ISSUE TITLE
Applicant Employment History Self-Employment Verify

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#414]
As an eApp applicant I want to provide information for a person who can verify my self-employment including their name, address, and phone number so that they can verify that period of self-employment to my investigator.

Acceptance Criteria
- Fields
	- Provide the name of someone that can verify your self-employment
		- [ ] First Name - Initial Only/No First Name
		- [ ] Last Name
	- Provide the address of this verifier 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required 
		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide the telephone number for this person 
		- [ ] Telephone block: day, night, both
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
Need to ask about whether the middle name is optional/required/even there.
