### ISSUE TITLE
Applicant Employment History Unemployment Verify

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#415]
As an eApp applicant I want to provide information for a person who can verify my unemployment period including their name, address, and phone number so that they can verify that period of unemployment to my investigator.

Acceptance Criteria
- Fields
	- Provide the name of someone who can verify your unemployment activities and means of support.
		- [ ] First Name - Initial Only/No First Name
		- [ ] Last Name
	- Provide the address of this verifier 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required 
		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Provide the telephone number for this person 
		- [ ] Telephone block: day, night, both
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
