### ISSUE TITLE
Applicant Employment History Reason Leaving

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#416]
As an eApp applicant I want to provide the reason why I left a job and provide additional details if I left because I was fired, was about to be fired, or asked to leave so that my investigator understands the circumstances surrounding why I left a certain job.

Acceptance Criteria
- Fields
	- Provide the reason for leaving the employment activity. 
		- [ ] Multi-line free text
	- For this employment have any of the following happened to you in the last seven (7) years?
		- [ ] Select the type of incident: Fired, Quit after being told you would be fired, Left by mutual agreement following charges or allegations of misconduct, Left by mutual agreement following notice of unsatisfactory performance
		- [ ] **Branch** - Fired
			- [ ] Provide the reason for being fired.
				- Multi-line free text
			- [ ] Provide the date you were fired.
				- Date/ Estimated 
		- [ ] **Branch** - Quit
			- [ ] Provide the reason for quitting.
				- Reason (Free Text)
			- [ ] Provide the date you quit after being told you would be fired.
				- Date/ Estimated
		- [ ] **Branch** - Left after Charges
			- [ ] Provide the charges or allegations of misconduct.
				- Multi-line free text
			- [ ] Provide the date you left following charges or allegations of misconduct.
				- Date/ Estimated
		- [ ] **Branch** - Left Unsatisfactory performance
			- [ ] Provide the reason(s) for unsatisfactory performance.
				- Reason (Free Text)
			- [ ] Provide the date you left by mutual agreement following a notice of unsatisfactory performance.
				- Date/ Estimated
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
Need to determine if this should go in

 1. It's own subsection
 2. Within an employment entry in the history section
