### ISSUE TITLE
Applicant Employment History Reprimand

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#419]
As an eApp applicant I want to specify whether I have received any disciplinary warnings during a given job and provide details of each warning including the estimated date it was received and a description of the warning so that my investigator can review discipline issues I've had in my employment history.   

Acceptance Criteria
- Fields
	- [x] For this employment, in the last seven (7) years have you received a written warning, been officially reprimanded, suspended, or disciplined for misconduct in the workplace, such as a violation of security policy?
	- [x] Yes/No Option
	- [x] **Branch**
		- [x] On No - move on to next subsection/section
		- [x] On Yes - show the data entry form for job reprimand:
	- Provide the month and year you were warned, reprimanded, suspended or disciplined 
		- [x] Date Month\Year - Est
	- Provide the reason(s) for being warned, reprimanded, suspended or disciplined 
		- [x] Multiline free-text
	- Action - Add another reprimand
		- [x] Add button - appends another job reprimand data entry section
	- Action - Remove reprimand
		- [x] Delete button - remove respective job reprimand entry
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
