### ISSUE TITLE
Applicant Employment History Reprimand Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#421]
As an eApp applicant I want to see a summary of all disciplinary warnings I've received for a given job including the estimated date and description of the warning so that I can review, edit, or remove the entries in my list of job disciplinary warnings. 

Acceptance Criteria
- Fields
	- Summary of Discipline and Warnings 
		- [ ] Shown inline with respective job details
		- [ ] Shown only if there are job disciplinary warnings entered
		- [ ] For each warning show the following fields: 
			- [ ] Date of incident 
				- [ ] Date with Estimate
			- [ ] Type of discipline/warning
				- [ ] Read-Only label
			- [ ] Actions: 
				- [ ] Delete - remove job reprimand entry 
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by pjsumm** [comment]
Delete this story, rolled the remove action into the create page [#419](https://github.com/truetandem/e-QIP-prototype/issues/419), which will be referenced when the applicant is reviewing the job details.
