### ISSUE TITLE
Applicant Employment Former Federal Service

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#452]
As an eApp applicant I want to specifiy whether I have any former federal service employment history and then provide the details of the former federal service like the dates, name of agency, position/title, and location so that my investigator can review my former federal service.

Acceptance Criteria
- Fields
	- Do you have former federal civilian employment, excluding military service, NOT indicated previously, to report? 
		- [ ] Yes/No Option
		- [ ] **branch**
			- [ ] On No navigate to next form section
			- [ ] On Yes show the data entry for former federal service:
	- Provide dates of federal civilian employment 
		- [ ] Date Range - Est/Present
	- Provide the name of the federal agency for which you are/were employed
		- [ ] Free-text
	- Provide your position title
		- [ ] Free-text
	- Provide the location of the agency 
		- [ ] Address - With Country Option
		- [ ] Provide Street and City
		- [ ] State and Zip - or - Country are required 
    		- [ ] Validation - For an APO/FPO Address 
			- [ ] If State = AA, AE, or AP Then City must be = APO or FPO 
			- [ ] **Branch** to APO/FPO Location Details
	- Action - Add another former federal service
		- [ ] Add button - appends another former federal service data entry section
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
