### ISSUE TITLE
Applicant Employment Former Federal Service Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#453]
As an eApp applicant I want to see a summary of my former federal service data entries including the date range, agency, and position for each federal position I've help so that I can review, edit, or remove entries in my former federal service list.

Acceptance Criteria
- Fields
	- Summary of former federal service
		- [ ] ~~Shown only if there are former federal services entered.~~
		- [x] For each former federal service show the following summary fields: 
			- [x] Dates of federal service: Read-Only label
			- [x] Agency: Read-Only label
			- [x] Position title: Read-Only label
			- [x] Actions: 
				- [x] Edit - go to former federal service entry section
				- [x] Delete - remove formal federal service entry from the list
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@pjsumm Had a question about this line?

> Shown only if there are former federal services entered
