### ISSUE TITLE
Applicant Selective Service Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#458]
As an eApp applicant born a male after December 31, 1959 I want to provide my selective service information or provide an explanation for why I don't know it or don't have it so that my investigator can access my selective service record.

Acceptance Criteria
- Fields 
  - Were you born a male after December 31, 1959?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, show selective service registration question
      - [x] If No, go to next subsection
  - Have you registered with the Selective Service System (SSS)?
    - [x] Field Help: The Selective Service website, www.sss.gov, can help provide the registration number for persons who have registered. Note: Selective Service Number is not your Social Security Number
   - [x] Field Help is always visible
    - [x] Select: Yes, No, I don't know
    - [x] **Branch** - Yes
      - [x] Provide registration number
        - [x] Free Text
    - [x] **Branch** - No
      - [x] You responded 'No' to having registered with the Selective Service System (SSS)
      - [x] Provide explanation
        - [x] Multiline free-text
    - [ ] ~~**Branch** - I don’t know~~
      - [ ] ~~You responded 'I don't know' to having registered with the Selective Service System (SSS)~~
      - [ ] ~~Provide explanation~~
        - [ ] ~~Multiline free-text~~
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-1](https://cloud.githubusercontent.com/assets/19935974/23467909/47602b38-fe6d-11e6-98ec-4d55223bb0c2.jpg)
![e-app-comp-military-history-2](https://cloud.githubusercontent.com/assets/19935974/23467905/470a319c-fe6d-11e6-8140-853aec2c9089.jpg)
![e-app-comp-military-history-3](https://cloud.githubusercontent.com/assets/19935974/23467907/47103542-fe6d-11e6-8730-99b0b94ab546.jpg)
![e-app-comp-military-history-4](https://cloud.githubusercontent.com/assets/19935974/23467906/470d23b6-fe6d-11e6-8cec-8edced429a4c.jpg)
![e-app-comp-military-history-5](https://cloud.githubusercontent.com/assets/19935974/23467908/472a69f8-fe6d-11e6-8cb7-42d497884a3c.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Note: Field help is always visible and will be on screen at all times (not just when Yes is select, change from comp)

**Comment by bmallred** [comment]
**Question**: Find out if we can drop "I don't know"
