### ISSUE TITLE
Applicant Military History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#563]
As an eApp applicant I want to specify whether I have served in the US Military and I have provide details on my service such as the branch, rank, service number, status, the date range I served and whether I was discharged so that my investigator can review my military history. 

Acceptance Criteria
- Fields 
  - Have you EVER served in the U.S. Military?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, show military history details (below)
      - [x] If No, go to next form subsection
  - Provide the branch of service you served in
    - [x] Choice - Army, Army National Guard, Navy, Air Force, Air National Guard, Marine Corps, Coast Guard
    - [x] **Branch**
      - [x] State of service, if National Guard
        - [x] Free-text field
  - Provide your status
    - [x] Choice: Active Duty, Active Reserve, Inactive Reserve
  - Officer or enlisted
    - [x] Choice: Not Applicable, Officer, Enlisted
  - Provide your service number
    - [x] Free-text field
  - Provide your dates of service.
    - [x] Date Range with Est/Present
  - Were you discharged from this instance of U.S. military service, to include Reserves, or National Guard?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, show discharge details (below)
      - [x] If No, continue on within the current form section
  - Discharge Details
    - [x] Provide the type of discharge you received
      - [x] Choice: Honorable, Dishonorable, Under Other than Honorable Conditions, General, Bad Conduct, Other (provide type)
      - [x] Provide the reason(s) for the discharge
        - [x] Multiline Free Text
    - [x] Provide the date of discharge listed above
      - [x] Date - Mon/Year Est
  - Action - Do you have additional military service to report?
    - [x] If so please use the button below to add more
    - [x] "Add additional military history" button - appends another military service data entry section
  - Action - Remove military service
    - [x] Remove button - removes the respective military service data entry
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-6](https://cloud.githubusercontent.com/assets/19935974/23468118/f03a91b2-fe6d-11e6-86fd-853473312983.jpg)
![e-app-comp-military-history-7](https://cloud.githubusercontent.com/assets/19935974/23468126/f14c4c62-fe6d-11e6-8a61-5bf49c8c9d42.jpg)
![e-app-comp-military-history-8](https://cloud.githubusercontent.com/assets/19935974/23468123/f05b8502-fe6d-11e6-881b-be9dcae39f06.jpg)
![e-app-comp-military-history-9](https://cloud.githubusercontent.com/assets/19935974/23468119/f04032fc-fe6d-11e6-8e6d-5daa8ea2eae2.jpg)
![e-app-comp-military-history-10](https://cloud.githubusercontent.com/assets/19935974/23468121/f0438a1a-fe6d-11e6-9080-be3096648643.jpg)
![e-app-comp-military-history-11](https://cloud.githubusercontent.com/assets/19935974/23468120/f043834e-fe6d-11e6-9435-bf0671e4a202.jpg)
