### ISSUE TITLE
Applicant Military Disciplinary Action

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#564]
As an eApp applicant I want to specify whether I have been subject to a court martial or other disciplinary actions in the last 7 years while serving in the US Military and provide details any details of such proceedings such as date, description, procedure name, court, and description of proceedings so that my investigator has full details of the disciplinary action and the outcome so the event can be investigated. 

Acceptance Criteria
- Fields 
  - In the last 7 years, have you been subject to court martial or other disciplinary procedure under the Uniform Code of Military Justice (UCMJ), such as Article 15, Captain’s mast, Article 135 Court of Inquiry, etc?
    - [ ] Yes / No Option
    - [ ] **Branch**
      - [ ] If Yes, show military disciplinary procedure details (below)
      - [ ] If No, go to next form subsection
  - Provide the date of the court martial or other disciplinary procedure.
    - [ ] Date - Mon/Year - Estimated
  - Provide a description of the Uniform Code of Military Justice (UCMJ) offense(s) for which you were charged.
    - [ ] Multiline Free-text
  - Provide the name of the disciplinary procedure
    - [ ] Such as Court Martial, Article 15, Captain’s mast, Article 135 Court of Inquiry, etc.
      - [ ] Free-text field
  - Provide the description of the military court or other authority in which you were charged
    - [ ] Title of court or convening authority, address, to include city and state or country if overseas
      - [ ] Multiline Free Text
  - Provide the description of the final outcome of the disciplinary procedure
    - [ ] Such as found guilty, found not guilty, fine, reduction in rank, imprisonment, etc.
      - [ ] Free-text field
  - Action - Additional disciplinary procedures
    - [ ] In the last 7 years do you have an additional instance of military discipline to report?
    - [ ] "Add another discipline" button - appends another disciplinary data entry section
  - Action - Remove military service
    - [ ] Remove button - removes the respective disciplinary data entry
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-10](https://cloud.githubusercontent.com/assets/19935974/23468264/5a1f608a-fe6e-11e6-9066-2e4e4e8f6d67.jpg)
![e-app-comp-military-history-11](https://cloud.githubusercontent.com/assets/19935974/23468260/57f1b376-fe6e-11e6-824d-33b0e1c88188.jpg)

**Comment by bmallred** [comment]
Research looking up court names to be implemented in the future.
