### ISSUE TITLE
Applicant Foreign Military History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#565]
As an eApp applicant I want to specify whether I have ever served in a foreign military as a civilian or military and if I have, provide the organization details of that service, the country, dates served, position, department, description of service and reason for leaving so that my investigator can review my foreign military service.

Acceptance Criteria
- Fields 
  - Have you EVER served, as a civilian or military member in a foreign country’s military, intelligence, diplomatic, security forces, militia, other defense force, or government agency?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, show foreign military service details (below)
      - [x] If No, go to next form subsection
  - During your foreign service, which organization were you serving under
    - [x] Choice: Military (Army, Navy, Air Force, Marines, etc.), Intelligence Service, Diplomatic Service, Security Forces, Militia, Other Defense Forces, Other Government Agency
  - Provide the name of the foreign organization.
    - [x] Free-text field
  - Provide your period of service.
    - [x] Date Range - Est/Present
  - Provide the name of the country.
    - [x] Free-text field
  - Provide your highest position/rank held
    - [x] Free-text field
  - Provide the division/department/office in which you served.
    - [x] Free-text field
  - Provide a description of the circumstances of your association with this organization.
    - [x] Multline Free-text field
  - Provide a description of the reason for leaving this service.
    - [x] Multline Free-text field
  - Do you maintain contact with current or former associates, colleagues, or acquaintances from your service in this organization?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, show foreign military contact details - [Foreign Military contact](https://github.com/truetandem/e-QIP-prototype/issues/566)
      - [x] If No, continue on to next form question (below)
  - Do you have an additional foreign military service to report?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes, add another foreign military service details
      - [x] If No, go to next form subsection
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-12](https://cloud.githubusercontent.com/assets/19935974/23468324/862d2d88-fe6e-11e6-8dc9-0bc716b2f3e8.jpg)
![e-app-comp-military-history-13](https://cloud.githubusercontent.com/assets/19935974/23468327/86ea422e-fe6e-11e6-95a5-c65fc7b5913e.jpg)
![e-app-comp-military-history-14](https://cloud.githubusercontent.com/assets/19935974/23468325/8633dfca-fe6e-11e6-8720-fdde23c6f145.jpg)
![e-app-comp-military-history-15](https://cloud.githubusercontent.com/assets/19935974/23468323/86297e2c-fe6e-11e6-8541-6ddb2482b43a.jpg)
