### ISSUE TITLE
Applicant Foreign Military Contact

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#566]
As an eApp applicant I want to provide details for any contacts, associates, colleagues I keep in touch with from my foreign military service including their full name, address, title, how long I knew them, and how frequently we were in contact so that my investigator can review with whom I maintain contact.

Acceptance Criteria
- Fields 
    - Acquaintance contact details
      - [x] Label: Please provide full name, address (if known), official title, length of association, and frequency of contact for each former associate, colleague or acquaintance with whom you maintain contact.
    - Provide the contact’s full name
      - [x] Full Name field group
    - Provide the contact’s address
      - [x] Address field group
    - Provide the contact’s official title
      - [x] Free-text field
    - Provide the length of your association with the contact
      - [x] Date Range - Est and Present
    - Provide the frequency of Contact
      - [x] Free-text field
    - Action: Do you have any additional foreign military service contacts to report?
      - [x] If yes use the button below to add another contact
      - [x] "Add another contact" button - appends another foreign military contact data entry section
**ADD SUMMARY FIELDS**
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-military-history-12](https://cloud.githubusercontent.com/assets/19935974/23468714/8a73eae8-fe6f-11e6-9c85-78d4ac5fa1e7.jpg)
![e-app-comp-military-history-13](https://cloud.githubusercontent.com/assets/19935974/23468716/8ad5b0f2-fe6f-11e6-8db6-542fb150f07a.jpg)
![e-app-comp-military-history-14](https://cloud.githubusercontent.com/assets/19935974/23468715/8a76e59a-fe6f-11e6-9dd5-2b9f065d64eb.jpg)
![e-app-comp-military-history-15](https://cloud.githubusercontent.com/assets/19935974/23468718/8b43358c-fe6f-11e6-956b-1d4601f625df.jpg)

**Comment by bmallred** [comment]
**Note**: Accordion summary on the foreign contact(s) but not on the foreign service.
