### ISSUE TITLE
Applicant Criminal History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#567]
As an eApp applicant I want to provide high-level information regarding my police record for the past 7 years, if I have one, including whether I have had any court appearances, arrests, charges, parole, and trials so that I can be prompted to provide additional information for my offenses.

Acceptance Criteria
- Police Record
  - [x] For this section report information regardless of whether the record in your case has been sealed, expunged, or otherwise stricken from the court record, or the charge was dismissed. You need not report convictions under the Federal Controlled Substances Act for which the court issued an
expungement order under the authority of 21 U.S.C. 844 or 18 U.S.C. 3607. 
  - [x] Bold: Be sure to include all incidents whether occurring in the U.S. or abroad.
  - [x] Have any of the following happened? 
    - [x] **In the last seven (7) years** have you been issued a summons, citation, or ticket to appear in court in a criminal proceeding against you? 
      - [x] (Answer no if all the citations involved traffic infractions where the fine was less than $300 and did not include alcohol or drugs.)
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
        - [x] If No, do nothing
    - [x] **In the last seven (7) years** have you been arrested by any police officer, sheriff, marshal or any other type of law enforcement official?
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
        - [x] If No, do nothing
    - [x] **In the last seven (7) years** have you been charged with, convicted of, or sentenced for a crime in any court? 
      - [x] (Include all qualifying charges, convictions or sentences in any Federal, state, local, military, or non-U.S. court, even if previously listed on this form).
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
        - [x] If No, do nothing
    - [x] **In the last seven (7) years** have you been or are you currently on probation or parole?
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
        - [x] If No, do nothing
    - [x] Are you currently on trial or awaiting a trial on criminal charges?
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
        - [x] If No, do nothing
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
