### ISSUE TITLE
Applicant Criminal History Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#568]
As an eApp applicant I want to see a summary of my criminal offense data entries including a description of the offense and the date the offense occurred for each criminal offense that I have entered so that I can review, edit, or remove criminal offenses that I have entered on the form.

Acceptance Criteria
- Fields
  - Summary of offenses
    - [x] Shown only if there are criminal offenses entered
    - [x] Listing of each criminal offense the applicant has entered
    - [x] For each criminal offense show the following summary fields: 
      - [x] Offense description: Read-Only label
      - [x] Date of criminal offense: Read-Only label
      - [x] Actions: 
        - [x] Edit - Expand offense in summary view to edit criminal offense data entry 
        - [x] Delete - "Remove offense #" action to remove respective entry from the list
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-police-record-10](https://cloud.githubusercontent.com/assets/19935974/23469059/96306f72-fe70-11e6-94b4-544ebac5d2de.jpg)
