### ISSUE TITLE
Applicant Criminal Offense Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#569]
As an eApp applicant I want to provide details regarding my criminal offenses including the date and description of each offense, the details of the offense, location, whether I was arrested so that my investigator can review my criminal history.

Acceptance Criteria
- Fields
  - Provide details of your offense
  - Provide the date of offense
    - [x] Date - Mon/Day/Year - Est
  - Provide a description of the specific nature of the offense
    - [x] Multiline free-text
  - Did this offense involve any of the following? 
    - [x] Domestic violence or a crime of violence (such as battery or assault) against your child, dependent, cohabitant, spouse or legally recognized civil union/domestic partner, former spouse or legally recognized civil union/domestic partner, or someone with whom you share a child in common?
      - [x] Yes / No Option
    - [x] Involve firearms or explosives?
      - [x] Yes / No Option
    - [x] Involve alcohol or drugs?
      - [x] Yes / No Option
  - Provide the location where the offense occurred.
    - [x] Full Street address with Country
  - Were you arrested, summoned, cited, or did you receive a ticket to appear as a result of this offense by any police officer, sheriff, marshal or any other type of law enforcement official?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes
        - [x] Since you answered yes we need more information
        - [x] Show "Arresting/citing/summoning agency" section (below)
      - [x] If No, continue on the form
  - Arresting/citing/summoning agency
    - [x] Provide the name of the law enforcement agency that arrested/cited/summoned you.
      - [x] Free-text
    - [x] Provide the location of the law enforcement agency.
      - [x] Full Street address with Country
  - As a result of this offense were you charged, convicted, currently awaiting trial, and/or ordered to appear in court in a criminal proceeding against you?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes
        - [x] Since you answered yes we need more information 
        - [x] Show "Court Information" section - [Court Information]()
      - [x] If No
        - [x] You responded ‘No’ to “As a result of this offense were you charged, convicted, currently awaiting trial, and/or ordered to appear in court in a criminal proceeding against you?”
          - [x] Provide Explanation
          - [x] Free-text
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-police-record-1](https://cloud.githubusercontent.com/assets/19935974/23469070/a3c899f2-fe70-11e6-8890-f3a57689be61.jpg)
![e-app-comp-police-record-2](https://cloud.githubusercontent.com/assets/19935974/23469069/a3bc1178-fe70-11e6-9a2d-6f762bc3b7c7.jpg)
![e-app-comp-police-record-3](https://cloud.githubusercontent.com/assets/19935974/23469066/a3aa5f3c-fe70-11e6-8811-26d355112fb3.jpg)
![e-app-comp-police-record-4](https://cloud.githubusercontent.com/assets/19935974/23469075/a43878ee-fe70-11e6-8a5c-afc54e4c066c.jpg)
![e-app-comp-police-record-5](https://cloud.githubusercontent.com/assets/19935974/23469074/a4334194-fe70-11e6-8560-0ce7796adeda.jpg)
![e-app-comp-police-record-6](https://cloud.githubusercontent.com/assets/19935974/23469067/a3b05018-fe70-11e6-8f1c-fd1b9192d8ba.jpg)
![e-app-comp-police-record-7](https://cloud.githubusercontent.com/assets/19935974/23469068/a3b8395e-fe70-11e6-9be1-e4bcb1d06a75.jpg)
![e-app-comp-police-record-8](https://cloud.githubusercontent.com/assets/19935974/23469076/a44f9470-fe70-11e6-86b0-7f581224cef7.jpg)
![e-app-comp-police-record-9](https://cloud.githubusercontent.com/assets/19935974/23469071/a3d387ea-fe70-11e6-8ddc-ac0d3957c256.jpg)
![e-app-comp-police-record-10](https://cloud.githubusercontent.com/assets/19935974/23469082/a732d03a-fe70-11e6-8977-f9cc4a289e69.jpg)
