### ISSUE TITLE
Applicant Criminal Charges Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#570]
As an eApp applicant I want to provide details regarding criminal charges against me including the court information, the charges, outcome, dates, trial, and conviction so that my investigator can review my criminal charges.

Acceptance Criteria
- Fields
  - Court information
    - [x] Provide the name of the court
      - [x] Label: Name of Court
      - [x] Free-text
  - Provide the location of the court
    - [x] Full Street address with Country
  - Charges Detail
    - [x] Label: **Provide all the charges brought against you for this offense**, and the outcome of each charged offense (such as found guilty, found not-guilty, charge dropped or “nolle pros,” etc). If you were found guilty of or pleaded guilty to a lesser offense, list separately both the original charge and the lesser offense.
  - Type of charge
    - [x] Choice: Felony, Misdemeanor, Other
  - Charge
    - [x] Free-text
  - Outcome
    - [x] Free-text
  - Date 
    - [x] Date: Month/Year - Est
  - Sentencing
    - [x] Were you sentenced as a result of this offense?
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes show "Conviction detail" section (below)
        - [ ] If No show "Trial detail" section (below)
  - Conviction detail
    - [x] Provide a description of the sentence.
      - [x] Free-text
    - [x] Were you sentenced to imprisonment for a term exceeding 1 year?
      - [x] Yes / No Option
    - [x] Were you incarcerated as a result of that sentence for not less than 1 year?
      - [x] Yes / No Option
    - [x] If the conviction resulted in imprisonment, provide the dates that you actually were incarcerated. 
      - [ ] Not Applicable
      - [x] Date Range - Est/Present
    - [x] If conviction resulted in probation or parole, provide the dates of probation or parole. 
      - [ ] Not Applicable
      - [x] Date Range - Est/Present
  - Trial detail
    - [x] Are you currently on trial, awaiting a trial, or awaiting sentencing on criminal charges for this offense?
      - [x] Yes / No Option
      - [x] Provide Explanation
        - [x] Free-text
  - Do you have any other offenses where any of the following has happened to you?
    - **In the last seven (7) years** have you been issued a summons, citation, or ticket to appear in court in a criminal proceeding against you? (Do not include citations involving traffic infractions where the fine was less than $300 and did not include alcohol or drugs)
    - **In the last seven (7) years** have you been arrested by any police officer, sheriff, marshal or any other type of law enforcement official?
    - **In the last seven (7) years** have you been charged with, convicted of, or sentenced for a crime in any court? (Include all qualifying charges, convictions, or sentences in a Federal, state, local, military, or non-U.S. court even if previously listed on this form.)
    - **In the last seven (7) years** have you been or are you currently on probation or parole?
    - Are you currently on trial or awaiting a trial on criminal charges?
    - If yes use the button below to add another offense  
      - [x] "Add another offense" button - adds another offense section - [Add Offense](https://github.com/truetandem/e-QIP-prototype/issues/569) 
    - If no select no below and continue
      - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-police-record-1](https://cloud.githubusercontent.com/assets/19935974/23469112/b800bc06-fe70-11e6-95f1-664a143e584c.jpg)
![e-app-comp-police-record-2](https://cloud.githubusercontent.com/assets/19935974/23469111/b7f6cb92-fe70-11e6-9d55-a4aaab0754c8.jpg)
![e-app-comp-police-record-3](https://cloud.githubusercontent.com/assets/19935974/23469116/ba281b0a-fe70-11e6-8b7a-2a51d46f9d2e.jpg)
![e-app-comp-police-record-4](https://cloud.githubusercontent.com/assets/19935974/23469109/b774ec4e-fe70-11e6-8d1f-b91498677f5b.jpg)
![e-app-comp-police-record-5](https://cloud.githubusercontent.com/assets/19935974/23469110/b782abf4-fe70-11e6-84f5-27546b7f7279.jpg)
![e-app-comp-police-record-6](https://cloud.githubusercontent.com/assets/19935974/23469117/ba3538da-fe70-11e6-9eb1-b00484423f7e.jpg)
![e-app-comp-police-record-7](https://cloud.githubusercontent.com/assets/19935974/23469114/b944614e-fe70-11e6-927a-f566bb9ad3ca.jpg)
![e-app-comp-police-record-8](https://cloud.githubusercontent.com/assets/19935974/23469113/b81f1840-fe70-11e6-8742-74cbc805d301.jpg)
![e-app-comp-police-record-9](https://cloud.githubusercontent.com/assets/19935974/23469115/b982cbb4-fe70-11e6-8cdb-60db87961b09.jpg)
![e-app-comp-police-record-10](https://cloud.githubusercontent.com/assets/19935974/23469119/bba61fa4-fe70-11e6-89f3-b3fd03aa3e46.jpg)
