### ISSUE TITLE
Applicant Criminal History Complete Past

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#571]
As an eApp applicant I want to provide my complete criminal past, beyond the last 7 years, so that my investigator is aware of any criminal behavior from my past.

Acceptance Criteria
- Fields
  - **NOTE:** Create separate form section for these fields and response
  - Other than those offenses already listed, have you EVER had the following happen to you?
    - [x] **Have you EVER been convicted** in any court of the United States of a crime, sentenced to imprisonment for a term exceeding 1 year for that crime, and incarcerated as a result of that sentence for not less than 1 year? (Include all qualifying convictions in Federal, state, local, or military court, even if previously listed on this form.)
        - [x] Yes / No Option
        - [x] **Branch**
          - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
          - [x] If No, do nothing
    - [x] **Have you EVER been charged** with any felony offense? (Include those under the Uniform Code of Military Justice and non-military/civilian felony offenses.)
        - [x] Yes / No Option
        - [x] **Branch**
          - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
          - [x] If No, do nothing
    - [x] **Have you EVER been convicted** of an offense involving domestic violence or a crime of violence (such as battery or assault) against your child, dependent, cohabitant, spouse or legally recognized civil union/domestic partner, former spouse or legally recognized civil union/domestic partner, or someone with whom you share a child in common?
        - [x] Yes / No Option
        - [x] **Branch**
          - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
          - [x] If No, do nothing
    - [x] **Have you EVER been charged** with an offense involving firearms or explosives?
        - [x] Yes / No Option
        - [x] **Branch**
          - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
          - [x] If No, do nothing
    - [x] **Have you EVER been charged** with an offense involving alcohol or drugs?
        - [x] Yes / No Option
        - [x] **Branch**
          - [x] If Yes, show "Add your offenses" if not already shown - [Offense Details](https://github.com/truetandem/e-QIP-prototype/issues/569)
          - [x] If No, do nothing
    - If yes use the button below to add another offense  
      - [x] "Add another offense" button - adds another offense section - [Add Offense]() 
    - If no select no below and continue
      - [x] "No" button - move on to next form field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-police-record-1](https://cloud.githubusercontent.com/assets/19935974/23469362/60167c5a-fe71-11e6-9d62-28e7de9e2df2.jpg)
![e-app-comp-police-record-2](https://cloud.githubusercontent.com/assets/19935974/23469363/601f3d9a-fe71-11e6-8d82-f26981092340.jpg)
![e-app-comp-police-record-3](https://cloud.githubusercontent.com/assets/19935974/23469364/601f4556-fe71-11e6-8604-8b38d1c8f076.jpg)
![e-app-comp-police-record-4](https://cloud.githubusercontent.com/assets/19935974/23469367/60236258-fe71-11e6-97f3-f90a0e5522ec.jpg)
![e-app-comp-police-record-5](https://cloud.githubusercontent.com/assets/19935974/23469365/602122cc-fe71-11e6-875e-8e7347919e8f.jpg)
![e-app-comp-police-record-6](https://cloud.githubusercontent.com/assets/19935974/23469368/6025b5da-fe71-11e6-9950-239d9521b8ec.jpg)
![e-app-comp-police-record-7](https://cloud.githubusercontent.com/assets/19935974/23469366/6022f836-fe71-11e6-8cb0-4f082425bb9e.jpg)
![e-app-comp-police-record-8](https://cloud.githubusercontent.com/assets/19935974/23469369/60284f52-fe71-11e6-9ecf-98c049cd1758.jpg)
![e-app-comp-police-record-9](https://cloud.githubusercontent.com/assets/19935974/23469370/6028a880-fe71-11e6-8843-1d3abb8c3ec4.jpg)
![e-app-comp-police-record-10](https://cloud.githubusercontent.com/assets/19935974/23469372/602ebf68-fe71-11e6-9f27-18d01034f5b5.jpg)
