### ISSUE TITLE
Applicant Criminal History Complete Past Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#572]
As an eApp applicant I want to provide all details from any criminal offenses in my past including information on the offense, when it occurred, court information, the charges, outcome, dates, trial, and conviction details so that my investigator is aware of all criminal behavior from my past.

- Fields
  - Provide details of your offense
  - Provide the date of offense
    - [x] Date - Mon/Day/Year - Est
  - Provide a description of the specific nature of the offense
    - [x] Multiline free-text
  - Did this offense involve any of the following? 
    - [x] Domestic violence or a crime of violence (such as battery or assault) against your child, dependent, cohabitant, spouse or legally recognized civil union/domestic partner, former spouse or legally recognized civil union/domestic partner, or someone with whom you share a child in common?
      - [x] Yes / No Option
    - [x] Involve firearms or explosives?
      - [x] Yes / No Option
    - [x] Involve alcohol or drugs?
      - [x] Yes / No Option
  - Court information
    - [x] Provide the name of the court
      - [x] Label: Name of Court
      - [x] Free-text
  - Provide the location of the court
    - [x] Full Street address with Country
  - Charges Detail
    - [x] Label: **Provide all the charges brought against you for this offense**, and the outcome of each charged offense (such as found guilty, found not-guilty, charge dropped or “nolle pros,” etc). If you were found guilty of or pleaded guilty to a lesser offense, list separately both the original charge and the lesser offense.
  - Type of charge
    - [x] Choice: Felony, Misdemeanor, Other
  - Charge
    - [x] Free-text
  - Outcome
    - [x] Free-text
  - Date 
    - [x] Date: Month/Year - Est
  - Sentencing
    - [x] Were you sentenced as a result of this offense?
      - [x] Yes / No Option
      - [x] **Branch**
        - [x] If Yes show "Conviction detail" section (below)
        - [ ] If No show "Trial detail" section (below)
  - Conviction detail
    - [x] Provide a description of the sentence.
      - [x] Free-text
    - [x] Were you sentenced to imprisonment for a term exceeding 1 year?
      - [x] Yes / No Option
    - [x] Were you incarcerated as a result of that sentence for not less than 1 year?
      - [x] Yes / No Option
    - [x] If the conviction resulted in imprisonment, provide the dates that you actually were incarcerated. 
      - [ ] Not Applicable
      - [x] Date Range - Est/Present
    - [x] If conviction resulted in probation or parole, provide the dates of probation or parole. 
      - [ ] Not Applicable
      - [x] Date Range - Est/Present
  - Trial detail
    - [x] Are you currently on trial, awaiting a trial, or awaiting sentencing on criminal charges for this offense?
      - [x] Yes / No Option
      - [x] Provide Explanation
        - [x] Free-text
  - Do you have any other offenses to list where the following has **EVER** happened to you?
    - [x] Have you **EVER** been convicted in any court of the United States of a crime, sentenced to imprisonment for a term exceeding 1 year for that crime, and incarcerated as a result of that sentence for not less than 1 year? (Include all qualifying convictions in Federal, state, local, or military court, even if previously listed on this form)
    - [x] Have you **EVER** been charged with any felony offense? (Include those under the Uniform Code of Military Justice and non-military/civilian offenses).
    - [x] Have you **EVER** been convicted of an offense involving domestic violence or a crime of violence (such as battery or assault) against your child, dependent, cohabitant, spouse or legally recognized civil union/domestic partner, former spouse or legally recognized civil union/domestic partner, or someone with whom you share a child in common?
    - [x] Have you **EVER** been charged with an offense involving firearms or explosives?
    - [x] Have you **EVER** been charged with an offense involving alcohol or drugs?
    - If yes use the button below to add another offense  
      - [x] "Add another offense" button - adds another offense section - [Add Offense](https://github.com/truetandem/e-QIP-prototype/issues/569) 
    - If no select no below and continue
      - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-police-record-1](https://cloud.githubusercontent.com/assets/19935974/23469394/746b79bc-fe71-11e6-9bfe-1e08fc8ae6ea.jpg)
![e-app-comp-police-record-2](https://cloud.githubusercontent.com/assets/19935974/23469401/748735a8-fe71-11e6-8d13-6746011f9c2f.jpg)
![e-app-comp-police-record-3](https://cloud.githubusercontent.com/assets/19935974/23469396/746e7fea-fe71-11e6-80b9-fc5099583e4c.jpg)
![e-app-comp-police-record-4](https://cloud.githubusercontent.com/assets/19935974/23469399/7479a686-fe71-11e6-8ea9-5a75421a3900.jpg)
![e-app-comp-police-record-5](https://cloud.githubusercontent.com/assets/19935974/23469395/746cb3ae-fe71-11e6-8039-2a42191f92fa.jpg)
![e-app-comp-police-record-6](https://cloud.githubusercontent.com/assets/19935974/23469397/7473b140-fe71-11e6-9d9d-c2a3ad9353ba.jpg)
![e-app-comp-police-record-7](https://cloud.githubusercontent.com/assets/19935974/23469403/74b5c328-fe71-11e6-8ab4-99bd9faeaa12.jpg)
![e-app-comp-police-record-8](https://cloud.githubusercontent.com/assets/19935974/23469398/74757dd6-fe71-11e6-802e-d83779b2ae15.jpg)
![e-app-comp-police-record-9](https://cloud.githubusercontent.com/assets/19935974/23469400/74828c4c-fe71-11e6-8889-1d854cb4b690.jpg)
![e-app-comp-police-record-10](https://cloud.githubusercontent.com/assets/19935974/23469402/7497b95a-fe71-11e6-9b95-8dba926ab79c.jpg)
