### ISSUE TITLE
Applicant Protective/Restraining Order History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#573]
As an eApp applicant I want to specify whether I have any domestic violence protective or restraining orders issued against me and if I do provide details regarding the order(s) such as an explanation, date, and court information so that my investigator is aware of the order(s). 

Acceptance Criteria
- Fields
  - Is there currently a domestic violence protective order or restraining order issued against you?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If Yes, show "Add your orders"
      - [x] If No, do nothing and move on to next form section
  - Provide details of your protective or restraining order
    - You responded ‘Yes’ to currently having a domestic violence protective order or restraining order issued against you.
    - Provide explanation
      - [x] Multiline free-text
    - Provide the date the order was issued.
      - [x] Date Month/Year - Estimated
    - Provide the name of the court or agency that issued the order.
      - [x] Free-text
    - Provide the location of the court or agency that issued the order.
      - [x] Full Street address with Country
    - Do you have another domestic violence protective order or restraining order currently issued against you to report?
      - If yes use the button below to add another offense  
        - [x] "Add another order" button - adds another domestic violence protective or restraining orders details section  
      - If no select no below and continue
        - [x] "No" button - move on to next form field
- Validation rules are enforced on the client side as the user leaves the field
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by Jay-Neighbours-I72** [comment]
Let's add this as a new subsection.

**Comment by floresj** [comment]
Page 23
![selection_312](https://cloud.githubusercontent.com/assets/5938731/23966542/1b1832fc-0992-11e7-937d-1a3b3f9d8cad.png)
