### ISSUE TITLE
Applicant Protective/Restraining Order History Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#574]
As an eApp applicant I want to see a summary of my domestic violence protective or restraining orders including a description of the order and the date the order was issued for each domestic violence protective or restraining order that I have entered so that I can review, edit, or remove orders that I have entered on the form.

Acceptance Criteria
- Fields
  - Summary of offenses
    - [x] Shown only if there are domestic violence protective or restraining orders entered
    - [x] Listing of each domestice violence protective or restraining orders the applicant has entered
    - [ ] For each domestic violence protective or restraining orders show the following summary fields:
      - [ ] Offense description: Read-Only label
      - [ ] Date of criminal offense: Read-Only label
      - [x] Actions:
        - [x] Edit - Expand offense in summary view to edit domestic violence protective or restraining orders data entry 
        - [x] Delete - "Remove offense #" action to remove respective entry from the list
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this suppose to be an `Accordion` or a `BranchCollection`?
