### ISSUE TITLE
Storyboard Accordion Options

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#607]
As an eApp designer I want to create storyboards providing optional behaviors and styles for the accordion summary control used throughout the eApp form prototype based on usability testing results so the accordion control can be refined to address usability concerns.

Acceptance Criteria
- [x] Utilize the current design styles and standards
- [x] Create concept for adding new items to the accordion
- [x] Create concept for removing items from the accordion
- [x] Create concept for expanding and contracting between summary and detail views of the accordion 
- [x] Show how the accordion will transition between statess: add/remove/expand/contract
- [x] Review the storyboards/comps with the 18f PMO
- [x] Review the storyboards/comps with the Product Owner
- [x] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-accordion-v2-1](https://cloud.githubusercontent.com/assets/19935974/23665403/57863dfa-0326-11e7-9252-bf4142685aa5.jpg)
![e-qip-comp-accordion-v2-2](https://cloud.githubusercontent.com/assets/19935974/23665404/578ceeca-0326-11e7-94ba-01422985b323.jpg)
![e-qip-comp-accordion-v2-3](https://cloud.githubusercontent.com/assets/19935974/23665405/578d20d4-0326-11e7-95ca-a3b4fa99ac3d.jpg)
![e-qip-comp-accordion-v2-4](https://cloud.githubusercontent.com/assets/19935974/23665408/5792d876-0326-11e7-97be-0c066db767d1.jpg)
![e-qip-comp-accordion-v2-5](https://cloud.githubusercontent.com/assets/19935974/23665406/5790374c-0326-11e7-8ade-0ec50db0731d.jpg)
![e-qip-comp-accordion-v2-6](https://cloud.githubusercontent.com/assets/19935974/23665407/5790d210-0326-11e7-8c73-73a478daf71c.jpg)
![e-qip-comp-accordion-v2-7](https://cloud.githubusercontent.com/assets/19935974/23665409/5795e2d2-0326-11e7-8d37-08db85098b27.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-accordion-V2.pdf](https://github.com/truetandem/e-QIP-prototype/files/824978/e-QIP-comp-accordion-V2.pdf)

**Comment by Jay-Neighbours-I72** [comment]
**Accordion alternate style:**

![e-qip-comp-accoridon-style-alt-1](https://cloud.githubusercontent.com/assets/19935974/23674712/d553e908-0344-11e7-9458-3d2cad5e9236.jpg)
![e-qip-comp-accoridon-style-alt-2](https://cloud.githubusercontent.com/assets/19935974/23674713/d55a27b4-0344-11e7-887f-628e90d8832a.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-accoridon-style-alt.pdf](https://github.com/truetandem/e-QIP-prototype/files/825594/e-QIP-comp-accoridon-style-alt.pdf)

**Comment by Jay-Neighbours-I72** [comment]
**Version 3 starts here:**

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-accordion-v3-1](https://cloud.githubusercontent.com/assets/19935974/23802076/38ce838e-0580-11e7-8a55-5f4b2c758338.jpg)
![e-qip-comp-accordion-v3-2](https://cloud.githubusercontent.com/assets/19935974/23802080/38d48022-0580-11e7-8bfe-c4a19345f175.jpg)
![e-qip-comp-accordion-v3-3](https://cloud.githubusercontent.com/assets/19935974/23802078/38d1e2b8-0580-11e7-8750-a9c504a94aa1.jpg)
![e-qip-comp-accordion-v3-4](https://cloud.githubusercontent.com/assets/19935974/23802079/38d2938e-0580-11e7-9ce3-3f3f118b9b19.jpg)
![e-qip-comp-accordion-v3-5](https://cloud.githubusercontent.com/assets/19935974/23802077/38d03008-0580-11e7-8e96-79cd2125b957.jpg)
![e-qip-comp-accordion-v3-6](https://cloud.githubusercontent.com/assets/19935974/23802081/38d76490-0580-11e7-96d2-4841e6ed8f60.jpg)
![e-qip-comp-accordion-v3-7](https://cloud.githubusercontent.com/assets/19935974/23802085/38dfbf96-0580-11e7-8917-dae8cca02e25.jpg)
![e-qip-comp-accordion-v3-8](https://cloud.githubusercontent.com/assets/19935974/23802082/38db523a-0580-11e7-9673-9de1e67ba591.jpg)
![e-qip-comp-accordion-v3-9](https://cloud.githubusercontent.com/assets/19935974/23802083/38dc4d52-0580-11e7-99c1-4ab714dbaea5.jpg)
![e-qip-comp-accordion-v3-10](https://cloud.githubusercontent.com/assets/19935974/23802084/38df5f7e-0580-11e7-90d4-2b3e0a2a0adf.jpg)
[e-QIP-comp-accordion-V3.pdf](https://github.com/truetandem/e-QIP-prototype/files/834414/e-QIP-comp-accordion-V3.pdf)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 

1. I **like** on hover or open, but I **feel** as if the end user would prefer seeing it all the time
2. Alternate style

**Comment by Jay-Neighbours-I72** [comment]
Updated version 3 with correct content:

[e-QIP-comp-accordion-V3-content-correction.pdf](https://github.com/truetandem/e-QIP-prototype/files/844468/e-QIP-comp-accordion-V3-content-correction.pdf)
