### ISSUE TITLE
Storyboard Your History Refinements

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#608]
As an eApp designer I want to update the storyboards for the Your History section of the eApp form prototype based on usability testing feedback so that the team has new designs to consider for future implementation and usability testing. 

Acceptance Criteria
- [x] Utilize the current design styles and standards
- [x] Update the Your History eApp form section design to address concerns found during usability testing
- [x] Review the storyboards/comps with the 18f PMO
- [x] Review the storyboards/comps with the Product Owner
- [x] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-history-v3-1](https://cloud.githubusercontent.com/assets/19935974/23665278/036750ec-0326-11e7-8eee-969b07fc9763.jpg)
![e-qip-comp-section-history-v3-2](https://cloud.githubusercontent.com/assets/19935974/23665277/0363dd54-0326-11e7-843b-293116c98cdd.jpg)
![e-qip-comp-section-history-v3-3](https://cloud.githubusercontent.com/assets/19935974/23665279/036e6c7e-0326-11e7-8525-9878773b33e9.jpg)
![e-qip-comp-section-history-v3-4](https://cloud.githubusercontent.com/assets/19935974/23665281/03710b0a-0326-11e7-95e5-7772c7e9c4ea.jpg)
![e-qip-comp-section-history-v3-5](https://cloud.githubusercontent.com/assets/19935974/23665280/0370544e-0326-11e7-9d51-87cc2158b197.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-section-history-v3.pdf](https://github.com/truetandem/e-QIP-prototype/files/824974/e-QIP-comp-section-history-v3.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-history-v3-1](https://cloud.githubusercontent.com/assets/19935974/23858309/5e799134-07d6-11e7-83e9-654331ec0bbc.jpg)
![e-qip-comp-section-history-v3-2](https://cloud.githubusercontent.com/assets/19935974/23858307/5e76696e-07d6-11e7-9617-cea24495fa6c.jpg)
![e-qip-comp-section-history-v3-3](https://cloud.githubusercontent.com/assets/19935974/23858311/5ecb5e42-07d6-11e7-96e8-7cf3011b5396.jpg)
![e-qip-comp-section-history-v3-4](https://cloud.githubusercontent.com/assets/19935974/23858308/5e76e768-07d6-11e7-9e57-80154685cc3a.jpg)
![e-qip-comp-section-history-v3-5](https://cloud.githubusercontent.com/assets/19935974/23858310/5e7d4176-07d6-11e7-8c90-78b8a3b9cae8.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-section-history-v3.pdf](https://github.com/truetandem/e-QIP-prototype/files/838448/e-QIP-comp-section-history-v3.pdf)
