### ISSUE TITLE
Storyboard Mental Health

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#609]
As an eApp designer I want to create storyboards for the Mental Health section of the eApp prototype form based on the 2016 SF86 pdf form so that the team can provide stakeholders with a design represenation of the Mental Health section form components to ensure the design meets the data gathering requirements in an easy to use fashion.

Acceptance Criteria
- [ ] Utilize the current design styles and standards
- [ ] Create storyboards to deconstruct the complexity 
- [ ] Review the storyboards/comps with the 18f PMO
- [ ] Review the storyboards/comps with the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
Current progress:

![e-app-comp-mental-health-1](https://cloud.githubusercontent.com/assets/19935974/23918819/de54807c-08ca-11e7-8462-d1554337c652.jpg)
![e-app-comp-mental-health-2](https://cloud.githubusercontent.com/assets/19935974/23918818/de53d032-08ca-11e7-8b84-cafeff34e3b7.jpg)
![e-app-comp-mental-health-3](https://cloud.githubusercontent.com/assets/19935974/23918821/de54935a-08ca-11e7-8581-f174f0c8a864.jpg)
![e-app-comp-mental-health-4](https://cloud.githubusercontent.com/assets/19935974/23918820/de549c10-08ca-11e7-8ae1-7bc206c0700b.jpg)
![e-app-comp-mental-health-5](https://cloud.githubusercontent.com/assets/19935974/23918822/de554b1a-08ca-11e7-92aa-1a831b04d041.jpg)
[e-APP-comp-mental-health.pdf](https://github.com/truetandem/e-QIP-prototype/files/842472/e-APP-comp-mental-health.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-mental-health-1](https://cloud.githubusercontent.com/assets/19935974/24055814/f46f316e-0b17-11e7-976a-f23296569fd4.jpg)
![e-app-comp-mental-health-2](https://cloud.githubusercontent.com/assets/19935974/24055817/f4721e7e-0b17-11e7-8c77-235b700b3fa5.jpg)
![e-app-comp-mental-health-3](https://cloud.githubusercontent.com/assets/19935974/24055815/f46fb378-0b17-11e7-88b0-5000ed7fead6.jpg)
![e-app-comp-mental-health-4](https://cloud.githubusercontent.com/assets/19935974/24055816/f46fc7dc-0b17-11e7-97c2-2f9c50884ff1.jpg)
![e-app-comp-mental-health-5](https://cloud.githubusercontent.com/assets/19935974/24055818/f4733b4c-0b17-11e7-9843-1e463099ce64.jpg)
![e-app-comp-mental-health-6](https://cloud.githubusercontent.com/assets/19935974/24055819/f4749dd4-0b17-11e7-9540-4630ec86a048.jpg)
![e-app-comp-mental-health-7](https://cloud.githubusercontent.com/assets/19935974/24055820/f47620c8-0b17-11e7-83c0-70db524d8a2e.jpg)
[e-APP-comp-mental-health.pdf](https://github.com/truetandem/e-QIP-prototype/files/851359/e-APP-comp-mental-health.pdf)

**Comment by Jay-Neighbours-I72** [comment]
New proposed location for Psychological and Emotional Health section

1. Information About You 
2. Family & Friends 
3. Citizenship
4. Military History
5. Your History 
6. Financial Record
7. Foreign Activities 
**8. Psychological and Emotional Health**
9. Substance Use - New category
10. Investigative and Criminal History

**Comment by bmallred** [comment]
Substance Abuse would be nine (9) then?

**Comment by billy22g** [comment]
Echoing @bmallred, this isn't quite clear. Does this mean you're proposed to increase the number of sections from 9 to 10 and Psychological & Emotional Health is the 8th? @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Fixed, bolding section 8 added an extra number.
