### ISSUE TITLE
Prepare for demonstration video

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#641]
## Things to do before video
 - [x] Add icons to review page
 - [x] Condense **Your history** section

## Thoughts
 - Go through “Information about you” section in its entirety
 - Touch on “Your history section”
 - Video should capture a light overview

## Outline
 - Design
   - Overall form language concept and flow
   - **Note: Speaker should speak to these during the presentation**
 - Login
   - User testXX
   - Password passwordXX
   - Register two factor authentication
     - **Talking point**: “This was the first step in order to proceed and we are iterating on its implementation…”
 - Validation
    - Demonstrate error and note the error in the navigation
    - Demonstrate valid field (green checkbox)
    - Demonstrate inline help
    - Show how it is automatically saving
    - Demonstrate completed section (something small like Foreign activities)
    - Show the score card and progress bar
 - Accordion
   - Show basic branching (Other names used)
   - Demonstrate filling out accordion (collapse, yadda)
   - Add new alias (or a couple)
   - Demonstrate removal of items
 - Review section
   - Show when in a neutral state (no errors but not completed)
   - Show when there are errors
   - Show when the section is completed
 - Your history section
   - **Transition phrase**: “In the interest of time…”
   - Places lived
     - Add address at beginning of quota
     - Add address at end of quota leaving a gap in the middle
   - Review
     - Show that gaps are highlighted

**Comment by bmallred** [comment]
@billy22g uploaded the video here (it was quite large due to us running over the time limit). Any comments on things to cut or if there was something we should apply more focus to is welcome!

Take one (unedited): https://youtu.be/fPnEc2NxkRo

tag: @Jay-Neighbours-I72 @pjsumm @DBrenenborg

**Comment by bmallred** [comment]
@billy22g uploaded the second video (unedited): https://youtu.be/TG0EjlyIVJQ

**Comment by bmallred** [comment]
## TODO

 - [ ] Edit the beginning and end to cut off any background noise
 - [ ] Convert to `mp4` format
 - [ ] Deliver medium

**Comment by bmallred** [comment]
https://youtu.be/E29nwWVrtx4
