### ISSUE TITLE
Form Instructions

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#652]
As an eApp Applicant I want to see basic instructions for how the eApp online SF86 form works so that I have a basic understanding of the form's features and behavior before I begin filling in information.

Acceptance Criteria
- [x] Utilize the style from User Story #698 storyboard form information
- Include the following information sections from the 2016 SF-86 PDF content guide
  - [x] Questionnaire for National Security Positions
  - [x] Purpose of this Form
  - [x] Authority to Request this Information
  - [x] The Investigative Process
  - [x] Your Personal Interview
  - [x] Instructions for Completing this Form
  - [x] Final Determination on Your Eligibility
  - [x] Penalties for Inaccurate or False Statements
  - [x] Disclosure Information
  - [x] Office of Personnel Management (OPM) Routine Uses
  - [x] Public Burden Information

**Comment by bmallred** [comment]
One section not mentioned in the checklist above was the one we added in the comp **How to save your progress**.

**Comment by billy22g** [comment]
This is looking generally really good! A couple issues below:

<img width="1275" alt="screen shot 2017-06-18 at 10 03 04 am" src="https://user-images.githubusercontent.com/5091167/27262140-b58a0f20-540d-11e7-99a8-4260016e9574.png">

1. The height/sizing seems somewhat off. I'd imagine our goal here should be for the entire modal area to be above the fold on the vast majority of screen sizes. See screenshot above from my Macbook. cc: @Jay-Neighbors-I72
2. The background should be locked until the form instructions are dismissed.

**Comment by bmallred** [comment]
@billy22g  just out curiosity what is your resolution? Definitely looks like there are some styling issues in there still

**Comment by billy22g** [comment]
@bmallred 13.3-inch (2560 x 1600) (from About this Mac) - also checked to verify that my Chrome browser was at 100% zoom (normal).

**Comment by bmallred** [comment]
@billy22g thanks!

**Comment by billy22g** [comment]
Looks good on my screen. Not sure we're quite there on mobile and various screen sizes based on some testing, but that seems more of a general concern outside of the scope of this story, so LGTM.
