### ISSUE TITLE
General Release Signature

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#657]
As an eApp Applicant I want to complete the signature fields for the authorization for release of information so that I can consent to the release of my information for the purposes of my investigation and the investigator can proceed. 

Acceptance Criteria
- [x] Use the SF-86 content guide
- [x] Current Signature Fields
  - [x] Signature (Sign in ink)
  - [x] Full name (Type or print legibly)
  - [x] Date signed (mm/dd/yyyy)
  - [x] Other names used
  - [x] Date of birth
  - [x] Social Security Number
  - [x] Current street address Apt. #
  - [x] City (Country)
  - [x] State
  - [x] ZIP Code
  - [x] Telephone number

**Comment by floresj** [comment]
Recap Release form conversation with sir @Jay-Neighbours-I72 

### Page 1
![selection_273](https://user-images.githubusercontent.com/5938731/27690155-82469026-5cae-11e7-9b19-00db5c433071.png)
 - [ ] Include Additional comment link to allow user to add comments. Add after `Additional Comments` paragraph
- [ ] Include textfield for name and date signed

### Page 2
Include the verify fields at the top 
![selection_274](https://user-images.githubusercontent.com/5938731/27690424-4bc4bc16-5caf-11e7-959f-e892b62a4d2f.png)

Then combine **The General ** and **HIPPA** release forms into one page with **General** going first.
- [ ] Include textfield for name and date field for date signed at the end of both

### Page 3
Credit reporting release.
- [ ] Include textfield for name and date field for date signed at the end of both

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 and @floresj, I just noticed **date of birth** is on the *General Release* but **not** on the *HIPPA Release*

Does that change anything with the combining of them?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @floresj pointed that out, I'm making an assumption that it will be ok.

I was thinking we build this as our recommendation then share to make sure it is all good.

Back up plan will be 2 separate pages with 2 verifications.

**Comment by billy22g** [comment]
Don't think this is working quite right. Release of information / HIPAA doesn't appear to actually be showing up as a page at all when I click on it, or click on the button to get to it.

<img width="1205" alt="screen shot 2017-07-26 at 10 57 13 am" src="https://user-images.githubusercontent.com/5091167/28633485-363735de-71f1-11e7-82c2-32258cfdaea6.png">

**Comment by Jay-Neighbours-I72** [comment]
That is still the old style correct @bmallred ?

The new style from the recent storyboard will be done later?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 yes. This has been the the queue for a bit and we had discussed making new tasks for the re-work. We can work from this though.

**Comment by billy22g** [comment]
Does this not make any sense to anyone except me?

The "Additional Comments" header and the "Add a comment" link don't seem to have anything to do with the paragraph between them.

<img width="642" alt="screen shot 2017-11-02 at 7 46 40 am" src="https://user-images.githubusercontent.com/5091167/32329234-099ec8f8-bfa2-11e7-8d4c-04f0c19a3bb0.png">

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @lauraponce Tagging you on the above. I'm not sure we should hold up this story but I do think we should address the Additional Comments section, maybe as a separate task.

**Comment by lauraponce** [comment]
I agree, @billy22g. That text doesn't make sense in there. 

What if we pulled it up so that they read that "After completing..." first then see the additional comments with some different text along the lines of "If you would like to add any additional comments about your answers, please add them here." @Jay-Neighbours-I72?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @lauraponce @bmallred I think I misunderstood the whole "Additional comments" block of text.

I assumed this was offering a place to give additional comments.

Looking again it seems like the headline "Additional comments" is setting up the instruction text below. Not asking for the user to leave comments. (Strange headline for it though)

I don't remember if we put in the "Add comment" feature based on my suggestion or from a product owner request. Any of you remember?

**Comment by bmallred** [comment]
- [ ] Remove headline for additional comments
 - [ ] Remove link for additional comments

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 did this get added to the content tracking doc?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Bump question above.

**Comment by billy22g** [comment]
LGTM otherwise.

**Comment by billy22g** [comment]
Actually, the date doesn't seem to be getting signed.

<img width="658" alt="screen shot 2017-12-27 at 1 29 07 pm" src="https://user-images.githubusercontent.com/5091167/34392540-f5c57168-eb09-11e7-85bb-8aec6bbc6030.png">

**Comment by Jay-Neighbours-I72** [comment]
Sorry I missed this one @billy22g 

Yes this updated was on the laspage of the content tracking doc.

I'm also not seeing the date being signed.

**Comment by bmallred** [comment]
It appears the commit 766f264 changed how the `DateSummary` performed
by not looking for the `date` or `value` property. This is fine but
all usages of the function were not fully tested to check for this change.

**Comment by billy22g** [comment]
LGTM except adding a separate bug
