### ISSUE TITLE
Medical Release Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#658]
As an eApp Applicant, if I have answered "Yes" to the section regarding my mental and emotional health, I want to view my Health Insurance Portability and Accountability Act, HIPPA, rights and complete the signature information fields so that I can understand my rights and legally authorize my investigator access to my health records. 

Acceptance Criteria
- [x] Use text from the SF-86 content guide
- [x] Current Signature Fields
  - [x] Signature 
  - [x] Full name
  - [x] Date signed (mm/dd/yyyy)
  - [x] Other names used
  - [x] Social Security Number
  - [x] Current street address Apt. #
  - [x] City (Country)
  - [x] State
  - [x] ZIP Code
  - [x] Telephone number

**Comment by billy22g** [comment]
Same issue as #657

**Comment by billy22g** [comment]
LGTM
