### ISSUE TITLE
Credit Release

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#659]
As an eApp Applicant, I want to understand the purpose for releasing my credit information and the implications of authorizing my investigator's access to my credit information so that I can complete the signature fields and legally authorize my investigator's access to my credit information

Accpetance Criteria
- [x] Use text from the SF-86 content guide
- [x] Current Signature Fields
  - [x] Print name
  - [ ] Social Security Number
  - [x] Signature 
  - [x] Date (mm/dd/yyyy)

**Comment by billy22g** [comment]
LGTM
