### ISSUE TITLE
Applicant Citizenship

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#660]
As an eApp applicant I want to specify my citizenship status either as a U.S. citizen or national by birth, born to U.S. parent(s) in a foreign country, naturalized, derived, or not a U.S. citizen so that I can provide the details of my citizenship status for my investigator to verify my citizenship.

Acceptance Criteria
- Fields
  - [ ] Help: Select the box that reflects your current citizenship status.
  - [ ] Provide your current citizenship status: 
    - [ ] I am a U.S. citizen or national by birth in the U.S. or U.S. territory/commonwealth.
      - [ ] Go to next form section
    - [ ] I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country. 
      - [ ] **Branch**
      - [ ] When selected go to [#756](https://github.com/truetandem/e-QIP-prototype/issues/756) 
    - [ ] I am a naturalized U.S. citizen.
      - [ ] **Branch**
      - [ ] When selected go to [#757](https://github.com/truetandem/e-QIP-prototype/issues/757) 
    - [ ] I am a derived U.S. citizen 
      - [ ] **Branch**
      - [ ] When selected go to [#758](https://github.com/truetandem/e-QIP-prototype/issues/758) 
    - [ ] I am not a U.S. citizen.
      - [ ] **Branch**
      - [ ] When selected go to [#759](https://github.com/truetandem/e-QIP-prototype/issues/759)
