### ISSUE TITLE
Applicant People Who Know Me Well

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#663]
As an eApp Applicant I want to provide information for three people who know me well for at least the last seven years including dates known, and contact information: telephone, email, and address so that my investigator can meet with these people and discuss my background. 

Acceptance Criteria
- Fields
  - Help: Provide three people who know you well and who preferably live in the U.S. They should be friends, peers, colleagues, college roommates, associates, etc., who are collectively aware of your activities outside of your workplace, school, or neighborhood, and whose combined association with you covers at least the last seven (7) years. Do not list your spouse, former spouse (s), other relatives, or anyone listed elsewhere on this form.
  - Provide dates known.
    - [ ] Date Range - Estimated/Present
  - Provide full name
    - [ ] Name Block
  - Provide rank/title.
    - [ ] Check: Not applicable
    - [ ] Free Text
  - Provide relationship to you: (Check all that apply) 
    - [ ] Choice: Neighbor, Friend, Work associate, Schoolmate, Other (Provide explanation)
    - [ ] Explanation
      - [ ] Free Text
  - Provide phone number for this person. 
    - [ ] Telephone block (with "I don’t know" option)
  - Provide mobile/cell phone number for this person. 
    - [ ] Telephone block (with "I don’t know" option)
  - Provide e-mail address for this person. □ I don’t know
    - [ ] Email block
  - Provide home or work address for this person.
    - [ ] Full Address block
  - Do you have an additional person who knows you well to list?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another person" - button adds another person detail section
      - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
- [ ] Determine if we can re-use/modify the `Reference` component.
