### ISSUE TITLE
Applicant Relative Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#665]
As an eApp applicant I want to provide information about my relatives, such as who they are to me, their name(s), address, and whether they are still living so that my investigator can review who my relatives and use the information I provide to follow-up with them as necessary. 

Acceptance Criteria
- [x] When the user selects the type of relative, the summary list of relatives will be pre-populated
- Fields
  - Select each type of relative applicable to you, regardless if they are living or deceased. (An opportunity will be provided to list multiple relatives for each type.) Check all that apply. 
    - [x] Multiple selection
    - [x] Choices: Mother, Father, Stepmother, Stepfather, Foster parent, Child (including adopted/foster),  Stepchild, Brother, Sister, Stepbrother, Stepsister, Half-brother, Half-sister, Father-in-law, Mother-in-law, Guardian
  - Provide relative type. (Multiple Entries Allowed)
    - [x] Multiple selection
    - [x] Choices: Mother, Father, Stepmother, Stepfather, Foster parent, Child (including adopted/foster),  Stepchild, Brother, Sister, Stepbrother, Stepsister, Half-brother, Half-sister, Father-in-law, Mother-in-law, Guardian
  - Provide your relative’s full name.
    - [x] Name block
  - Provide your relative’s date of birth.
    - [x] Date mm/dd/yy - Estimated
  - Provide your relative’s place of birth.
    - [x] Address - City, State, Country
  - Provide your relative's country(ies) of citizenship.
    - [x] Type ahead field - multiple additions
  - **Branch** - If Mother
    - [x] Text button - Same as listed - disable text if checked
    - [x] Free-text 
  - **Branch** - If Father, Mother, Child, Stepchild, Brother, Sister, Half-Brother, Half-Sister, Step-Brother, Step-Sister, Step-Mother, Step-Father
Relatives other names used.
    - Has this relative used any other names?
      - [x] Yes/No button
      - [x] **Branch** - If Yes (other names branch)
        - [x] Provide other names used and the period of time that your relative used them.
        - [x] Such as maiden, name by a former marriage, former name, alias, or nickname.
          - [x] Name block
        - [x] Maiden name?
          - [x] Yes/No button
          - [x] Date range block
    - Has this relative used any additional names?
      - [x] Yes/No button
      - [x] Yes will load another input to avoid accordion within an accordion
  - **Branch** - If Not Deceased
    - Provide your relative’s current address.
    - Full address with AFP Option
  - **Branch** - If Father, Mother, Child, Stepchild, Brother, Sister, Half-Brother, Half-Sister, Step-Brother, Step-Sister, Step-Mother, Step-Father AND Relative is U.S. Citizen AND Relative POB is Foreign
AND Relative is Deceased
--- OR ---
Relative Current Address is in U.S. AND Relative POB is Foreign AND Relative is U.S. Citizen
--- OR ---
Relative has APO/FPO Address AND Relative POB is Foreign AND Relative is U.S. Citizen
--- OR ---
Relative POB is Foreign AND Relative is U.S. Citizen
    - [x] go to [Applicant Relatives Citizenship Documentation](https://github.com/truetandem/e-QIP-prototype/issues/666)
- [x] Do you have an additional relative to enter?
   - [x] If Yes use button below to add.
   - [x] Button: Add another relative

**Comment by floresj** [comment]
Page 13 Section 18 of PDF.
