### ISSUE TITLE
Applicant Relatives Citizenship Documentation

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#666]
As an eApp applicant I want to provide my relative's citizenship information, such as citizenship status, documentation, naturalization, court information, whether they live in the US or abroad and how frequently I am in touch with them if they live abroad, so that my investigator can review my relatives immigration status and assess my involvement with people living overseas. 

Acceptance Criteria
- Fields show when Father, Mother, Child, Stepchild, Brother, Sister, Half-Brother, Half-Sister, Step-Brother, Step-Sister, Step-Mother, Step-Father AND Relative is U.S. Citizen AND Relative POB is Foreign
AND Relative is Deceased
--- OR ---
Relative Current Address is in U.S. AND Relative POB is Foreign AND Relative is U.S. Citizen
--- OR ---
Relative has APO/FPO Address AND Relative POB is Foreign AND Relative is U.S. Citizen
--- OR ---
Relative POB is Foreign AND Relative is U.S. Citizen
- Fields
  - U.S. Citizenship Documentation
  - Provide one type of citizenship documentation and document number below:
    - [ ] Born Abroad to U.S. Parents:
      - [ ] Text buttons 
        - [ ] FS 240 or 545
        - [ ] DS 1350
    - [ ] Naturalized:
      - [ ] Text buttons 
        - [ ] Alien Registration (on Certificate of Naturalization—utilize USCIS, CIS, or INS Registration number)
        - [ ] Permanent Resident Card (I-551)
        - [ ] Certificate of Naturalization (N550 or N570)
    - [ ] Derived:
      - [ ] Text buttons 
        - [ ] Alien Registration (on Certificate of Citizenship--utilize USCIS, CIS, or INS Registration number)
        - [ ] Permanent Resident Card (I-551)
        - [ ] Certificate of Citizenship (N560 or N561)
        - [ ] Other (Provide explanation)
  - Provide the document number.
    - [ ] Free text single line
  - Provide the name of the court that issued the Certificate of Naturalization.
    - [ ] Free text single line
  - Provide the address of the court that issued the Certificate of Naturalization.
    - [ ] Address block
  - **Branch** - if Relative does not have U.S. Citizenship AND Relative is Not Deceased
    - **Branch** - if Relative has U.S. Address 
      - Provide type of documentation he or she possesses to support U.S. residence:
        - [ ] Not a U.S. Citizen:
          - [ ] Text buttons 
            - [ ] I-551 Permanent Resident
            - [ ] I-766 Employment Authorization
            - [ ] I-94 Arrival-Departure Record
            - [ ] U.S. Visa (red foil number)
            - [ ] I-20 Certificate of Eligibility for Non-Immigrant-F1-Student
            - [ ] DS-2019 Certificate of Eligibility of Exchange Visitor-J1-Status
            - [ ] Other (Provide explanation)
      - Provide the document number.
        - [ ] Free text single line
      - Provide document expiration date.
        - [ ] Date block (day, month, year) - Estimated checkbox
    - **Branch** If Relative has Foreign Address 
      - Provide approximate date of first contact.
        - [ ] Date block (day, month, year) Estimated checkbox
      - Provide approximate date of last contact.
        - [ ] Date block (day, month, year) Estimated checkbox
      - Provide methods of contact.
        - [ ] Check all that apply
          - [ ] Text buttons 
            - [ ] In person
            - [ ] Telephone
            - [ ] Electronic (such as e-mail, texting, chat rooms, etc.
            - [ ] Written correspondence
            - [ ] Other (Provide explanation)
      - Provide Approximate frequency of contact.
        - [ ] Text buttons 
          - [ ] Daily
          - [ ] Weekly
          - [ ] Monthly
          - [ ] Quarterly
          - [ ] Annually
          - [ ] Other (Provide Explanation)
       - Provide name of current employer, or provide the name of their most recent employer if not currently employed (if known).
         - [ ] Free text single line 
         - [ ] "I don't know" text button
       - Provide the address of current employer, or provide the address of their most recent employer if not currently employed.
         - [ ] Address block
         - [ ] "I don't know" text button
       - Is this relative affiliated with a foreign government, military, security, defense industry, foreign movement, or intelligence service?
         - [ ] Yes/No buttons
         - [ ] "I don't know" text button
    - **Branch** If Relative has Foreign Affiliation
      - Describe the relative’s relationship with the foreign government, military, security, defense industry, foreign movement, or intelligence service.
        - [ ] Free-text multi line

**Comment by floresj** [comment]
Page 14 of PDF
![selection_311](https://cloud.githubusercontent.com/assets/5938731/23966350/655e3a42-0991-11e7-96b8-31a1350bc21b.png)
