### ISSUE TITLE
Applicant Relatives Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#667]
As an eApp applicant I want to see a summary of my relatives data entries including my relative's name and who they are (mother, father, etc...) for each relative that I have entered so that I can review, edit, or remove relatives that I have entered on the form.

Acceptance Criteria
- Fields
  - Summary of offenses
    - [ ] Auto-create Relatives entries in the summary view based on the initial selection of relatives in [Applicant Relative Information](https://github.com/truetandem/e-QIP-prototype/issues/665)
    - [ ] Shown only if there relatives entered
    - [ ] Listing of each relative the applicant has entered
    - [ ] For each relative show the following summary fields: 
      - [ ] Relative Name: Read-Only label
      - [ ] Relative Relation: Read-Only label (mother, father, brother, sister, etc...)
      - [ ] Actions: 
        - [ ] Edit - Expand relative info in summary view to edit relative data entry 
        - [ ] Delete - "Remove relative" action to remove respective entry from the list
        - [ ] Toggle - Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
