### ISSUE TITLE
Applicant Foreign Contacts

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#668]
As an eApp applicant I want to provide information for any foreign national within the last seven (7) years with whom I, or my spouse/partner/cohabitant, are connected to so that my investigator can review the level of foreign influence present in my current situation.

Acceptance Criteria
- Field Help: A foreign national is defined as any person who is not a citizen or national of the U.S.
- Fields
  - [ ] Do you have, or have you had, close and/or continuing contact with a foreign national within the last seven (7) years with whom you, or your spouse, or legally recognized civil union/domestic partner, or cohabitant are bound by affection, influence, common interests, and/or obligation? Include associates as well as relatives, not previously listed in Section 18.
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: You indicated that you have, or have had, close and/or continuing contact with a foreign national.
    - You indicated that you have, or have had, close and/or continuing contact with a foreign national.
    - Provide the full name of the foreign national, if known 
      - [ ] Name block
      - [ ] I don’t know
    - Explanation if name is unknown.
      - [ ] Free Text
    - Provide approximate date of first contact.
      - [ ] Date/Estimated
    - Provide approximate date of last contact.
      - [ ] Date/Estimated 
    - Provide methods of contact (check all that apply) 
      - [ ] Choice: In person, Telephone, Electronic (Such as e-mail, texting, chat rooms, etc), Written correspondence, Other (Provide explanation)
      - [ ] Explanation - Free Text
    - Provide approximate frequency of contact. 
      - [ ] Choice: Daily, Weekly, Monthly, Quarterly, Annually, Other (Provide explanation)
      - [ ] Explanation - Free Text
    - Provide the nature of relationship (select all that apply)
      - [ ] Chioce: Professional or Business, Personal (Such as family ties, friendship, affection, common interests, etc), Obligation (Provide explanation), Other (Provide explanation)
      - [ ] Explanation - Free Text
    - Provide other names and/or nicknames, as appropriate.
      - [ ] Name Block
    - Provide country(ies) of citizenship.
      - [ ] Country select
    - Provide date of birth 
      - [ ] Date/Estimated
      - [ ] I don’t know
    - Provide place of birth
      - [ ] City/Country  
      - [ ] I don’t know
    - Provide current address.
      - [ ] Address Block with APO/FPO option
    - Provide the name of the foreign national’s current employer, or provide the name of their most recent employer if not currently employed. 
      - [ ] Free Text
      - [ ] I don’t know
    - Provide the address of the foreign national’s current employer, or provide the address of their most recent employer if not currently employed.
      - [ ] Address Block
      - [ ] I don't know
    - Is this foreign national affiliated with a foreign government, military, security, defense industry, or intelligence service?
      - [ ] Yes/No Option
      - [ ] I don't know
        - [ ] **Branch** if Yes Contact Foreign Military
          - [ ] Describe the contact’s relationship with the foreign government, military, security, defense industry, or intelligence service.
            - [ ] Free Text
    - Do you have, or have you had, close and/or continuing contact with any additional foreign national within the last seven (7) years with whom you, or your spouse, or cohabitant are bound by affection, influence, common interests, and/or obligation? Include associates as well as relatives, not previously listed in Section 18.
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another instance" - button adds another foreign contact detail section
        - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
## Content Guide

![foreign-contacts-guidelines](https://cloud.githubusercontent.com/assets/697855/25580098/d847a046-2e4b-11e7-9180-27b878e009a1.png)

**Comment by bmallred** [comment]
## Deviation from the content guide

For the question 

> Provide other names and/or nicknames, as appropriate

instead of asking for only a **singular** name we are proposing allowing for **multiple entries** with some slight updates to verbiage to accomodate it.

### First question

> Has this foreign national used any other names and/or nicknames?

### Subsequent questions

> Any additional other names and/or nicknames for this foreign national?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Did you review these content updates, and are you tracking them?

**Comment by billy22g** [comment]
The help icons are oddly located throughout this page.

**Comment by bmallred** [comment]
@billy22g I noticed the same thing from one of your other bug #1150. Sweeping through the application on PR #1165

**Comment by Jay-Neighbours-I72** [comment]
@billy22g yeah this is being tracked, we had a placeholder until it was in the Protoype:
<img width="745" alt="screen shot 2017-05-09 at 10 19 44 am" src="https://cloud.githubusercontent.com/assets/19935974/25855403/195ff276-34a1-11e7-82be-32cc33badc78.png">


Now that it is I can put full screenshots and an explanation in the tracking doc

**Comment by billy22g** [comment]
Couple things:
1. Help icon out of place
2. Too much space between "Country" input and the "or" and "I don't know"

<img width="685" alt="screen shot 2017-05-09 at 4 35 54 pm" src="https://cloud.githubusercontent.com/assets/5091167/25875620/b3ecd190-34d5-11e7-9b76-92918a4f2b80.png">

**Comment by billy22g** [comment]
I think "I don't know" is missing as an option here.

<img width="682" alt="screen shot 2017-05-09 at 4 38 23 pm" src="https://cloud.githubusercontent.com/assets/5091167/25875673/f873f92e-34d5-11e7-8981-42280291c765.png">

**Comment by bmallred** [comment]
@billy22g absolutely correct on missing **I don't know value**. Will add that in shortly.

**Comment by bmallred** [comment]
For the help icon went ahead and created a bug: #1191. This appears to happen once the view size is at a certain breakpoint and when there are nested fields. Easy solution would to be un-nest them, but this happens enough we need to see if there is another way of handling it.

Added the **I don't know** value to the options

## Preview
![idk-contacts](https://cloud.githubusercontent.com/assets/697855/25896928/03060304-3554-11e7-96d6-e7074630c205.png)

**Comment by billy22g** [comment]
LGTM after the PR is merged.
