### ISSUE TITLE
Applicant Foreign Business Advice

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#669]
As an eApp applicant I want to provide information regarding advise or consultation I have given to foreign businesses in the past sever years so that my investigator can see my involvement in foreign business interests.

Acceptance Criteria
- Fields
  - Have you in the last seven (7) years provided advice or support to any individual associated with a foreign business or other foreign organization that you have not previously listed as a former employer? (Answer “No” if all your advice or support was authorized pursuant to official U.S. Government business.)
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide a description of advice/support provided
  - Provide a description of advice/support provided.
    - [x] Free Text
  - Provide the name of the individual to whom advice or support was provided.
    - [x] Name block
  - Provide the name of the foreign organization or foreign business with whom the individual is associated.
    - [x] Free Text
  - Provide the country of origin for the organization or business.
    - [x] Free Text
  - Provide the date(s) during which this advice or support was provided.
    - [x] Date Range (Estimated/Present)
  - Describe what compensation, if any, was provided for your service.
    - [x] Free Text
  - Have you in the last seven (7) years provided advice or support to any other individual associated with a foreign business or other foreign organization that you have not previously listed as a former employer? (Answer “No” if all your advice or support was authorized pursuant to official U.S. Government business.)
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another instance" - button adds another foreign business advice detail section
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign business consulting](https://cloud.githubusercontent.com/assets/12962390/25616826/ee254bae-2f0c-11e7-9c78-febaf302e6e7.png)

**Comment by billy22g** [comment]
The first question is not from the right section.

<img width="1239" alt="screen shot 2017-05-08 at 11 12 15 am" src="https://cloud.githubusercontent.com/assets/5091167/25815820/5559023a-33df-11e7-81c8-d619f1f2de52.png">

**Comment by billy22g** [comment]
"Add another interest" button is also not correct text (from different section than this one). cc: @Jay-Neighbours-I72 for what the right text should be.

**Comment by bmallred** [comment]
Just a reminder if we need to update it in the wireframe, too.

**Comment by billy22g** [comment]
LGTM
