### ISSUE TITLE
Storyboard Form Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#688]
As an eApp designer I want to create storyboards for the Introduction/Information section of the eApp prototype form based on the 2016 SF86 pdf form so that the team can provide stakeholders with a design representation of how users will be prompted with information as they enter the eApp form, before they start data entry.

Acceptance Criteria
- [ ] Utilize the current design styles and standards
- [ ] Create storyboards to reflect how large amounts of information will be presented to the user as they enter the eApp form
- [ ] Show the data sections cataloged in the [Form Information](https://github.com/truetandem/e-QIP-prototype/issues/653) Epic
- [ ] Review the storyboards/comps with the 18f PMO
- [ ] Review the storyboards/comps with the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
Include auto save explanation and walkthrough video style.

**Comment by pjsumm** [comment]
Closing.
This is a duplicate of [698](https://github.com/truetandem/e-QIP-prototype/issues/698)
