### ISSUE TITLE
Storyboard Illegal Drug Use Activity

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#689]
As an eApp designer I want to create storyboards for the Illegal Use of Drugs and Drug Activity section of the eApp prototype form based on the 2016 SF-86 PDF form so that the team can provide stakeholders with a design representation of how users will be prompted for questions and how the branching and conditional fields will behave as users navigate the Illegal Use of Drugs and Drug Activity section.

Acceptance Criteria
- [ ] Utilize the current design styles and standards
- [ ] Create storyboards to show how the team proposes to deconstruct complex branching to a usable flow
- [ ] Show how conditional branching and fields will occur 
- [ ] Show how high-level and embedded summaries will be displayed
- [ ] Review the storyboards/comps with the 18f PMO
- [ ] Review the storyboards/comps with the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by pjsumm** [comment]
This section has been completed.  OBE.
