### ISSUE TITLE
Storyboard Form Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#698]
As an eApp designer I want to create storyboards for the SF-86 form information sections of the eApp prototype to display before the user begins to enter data on the form itself so that the team can provide stakeholders with a design representation of how information will be presented to users accessing the eApp form.

Acceptance Criteria
- Create storyboards to show how data sections will be presented
  - Data sections:
    - [ ] Questionnaire for National Security Positions
    - [ ] Purpose of this Form
    - [ ] Authority to Request this Information
    - [ ] The Investigative Process
    - [ ] Your Personal Interview
    - [ ] Instructions for Completing this Form
    - [ ] Final Determination on Your Eligibility
    - [ ] Penalties for Inaccurate or False Statements
    - [ ] Disclosure Information
    - [ ] Office of Personnel Management (OPM) Routine Uses
    - [ ] Public Burden Information
- [ ] Utilize the current design styles and standards
- [ ] Review the storyboards/comps with the 18f PMO
- [ ] Review the storyboards/comps with the Product Owner
- [ ] Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
2 Options:

**Comment by Jay-Neighbours-I72** [comment]
Option 1:

![e-qip-instructions-option-1-1](https://cloud.githubusercontent.com/assets/19935974/24048584/c02c4ddc-0aff-11e7-9942-167b1b47aaff.jpg)
![e-qip-instructions-option-1-2](https://cloud.githubusercontent.com/assets/19935974/24048586/c0307d80-0aff-11e7-9a57-8d3a6bc8a728.jpg)
![e-qip-instructions-option-1-3](https://cloud.githubusercontent.com/assets/19935974/24048585/c02cc8fc-0aff-11e7-8537-1b2b373eb2a4.jpg)
![e-qip-instructions-option-1-4](https://cloud.githubusercontent.com/assets/19935974/24048588/c033d7f0-0aff-11e7-919e-22cc45360527.jpg)
![e-qip-instructions-option-1-5](https://cloud.githubusercontent.com/assets/19935974/24048589/c03517be-0aff-11e7-9c07-28de95c4712d.jpg)
![e-qip-instructions-option-1-6](https://cloud.githubusercontent.com/assets/19935974/24048587/c033cb48-0aff-11e7-8f9c-f0bb81b56530.jpg)
![e-qip-instructions-option-1-7](https://cloud.githubusercontent.com/assets/19935974/24048590/c035d046-0aff-11e7-8473-c3fd7088312d.jpg)
[e-QIP-instructions-option-1.pdf](https://github.com/truetandem/e-QIP-prototype/files/850895/e-QIP-instructions-option-1.pdf)

**Comment by Jay-Neighbours-I72** [comment]
Option 2:

![e-qip-instructions-option-2-1](https://cloud.githubusercontent.com/assets/19935974/24048606/cbee70e6-0aff-11e7-98bc-31fff8481443.jpg)
![e-qip-instructions-option-2-2](https://cloud.githubusercontent.com/assets/19935974/24048607/cbf79b12-0aff-11e7-902c-11d7a5460531.jpg)
[e-QIP-instructions-option-2.pdf](https://github.com/truetandem/e-QIP-prototype/files/850897/e-QIP-instructions-option-2.pdf)

**Comment by billy22g** [comment]
Testing comment.

**Comment by DBrenenborg** [comment]
Jay,
I like option 2 better that option 1.  I was also wondering what you thought about more of a pop-up (apple-like) that had a yes/no at the bottom?

what are your thoughts.

thanks.
Drew

**Comment by Jay-Neighbours-I72** [comment]
@DBrenenborg Here is a comp for the pop-up style.

Instructions would overlay the first section of the form, once user clicked yes pop-up would go away revealing that first section.

**Note the second (really long) jpg here and 2nd page of the PDF are only to show the full length of the scroll.** Users would not see the full length extended like that, it is only for our internal reference.

![e-qip-instructions-option-3-1](https://cloud.githubusercontent.com/assets/19935974/24712495/0976f758-19f1-11e7-9555-9446f6aefa61.jpg)
![e-qip-instructions-option-3-2](https://cloud.githubusercontent.com/assets/19935974/24712496/0977eb0e-19f1-11e7-9052-a13dd7ebf602.jpg)

[e-QIP-instructions-option-3.pdf](https://github.com/truetandem/e-QIP-prototype/files/899866/e-QIP-instructions-option-3.pdf)

**Comment by bmallred** [comment]
Sounds like **Option 3** is the winner.

**Comment by Jay-Neighbours-I72** [comment]
Option 3 it is
