### ISSUE TITLE
Accordion Rework

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#700]
Update the eApp prototype accordion web control based on usability testing user feedback. 

Acceptance Criteria
- [x] Utilize Storyboard Accordion Rework Comp from [Epic #607](https://github.com/truetandem/e-QIP-prototype/issues/607)
  - [x] Adjust styles outside of the accordion 
  - [x] Rework structure of accordion summary
  - [x] Rework structure of accordion item content
  - [x] Add remove button to summary
