### ISSUE TITLE
Applicant Finances Delinquent Payments Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#733]
As an applicant I want to see a summary listing of all delinquent payment data I've entered so that I can see all related delinquent payments data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of delinquent payments
  - [x] Shown only if delinquent payments data entries exist
  - [x] Listing of each delinquent payment entry the applicant has entered
  - [x] For each delinquent payment entry show the following summary fields: 
    - [x] Date of issue: Read-Only label
    - [x] Agency/Institution/Individual owed: Read-Only label
    - [x] Amount: Read-Only label
    - [x] Actions:
      - [x] Edit - goes to delinquent payment information entry section
      - [x] Delete - Removes the delinquent payment information entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
