### ISSUE TITLE
Applicant Finances Non-Payment Consequence Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#734]
As an applicant I want to see a summary listing of all consequences from not paying debt that I've entered so that I can see all related non-payment consequence data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of non-payment consequences
  - [x] Shown only if non-payment consequences data entries exist
  - [x] Listing of each non-payment consequence entry the applicant has entered
  - [x] For each non-payment consequences entry show the following summary fields:
    - [x] Date of issue: Read-Only label
    - [x] Agency/Institution/Individual owed: Read-Only label 
    - [x] Amount: Read-Only label
    - [x] Actions:
      - [x] Edit - goes to non-payment consequence information entry section
      - [x] Delete - Removes the non-payment consequence information entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why
