### ISSUE TITLE
Applicant Mental Health Information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#748]
As an eApp applicant I want to understand why the government is asking me about my psychological and emotional health so that I understand the impact of providing my psychological and emotional health background on my clearance investigation.

Acceptance Criteria:
- [x] Header: Why we are asking
- [x] Form Help text: 
  - The U.S. government recognizes the critical importance of mental health and advocates proactive management of mental health conditions to support the wellness and recovery of Federal employees and others. Every day individuals with mental health conditions carry out their duties without presenting a security risk. While most individuals with mental health conditions do not present security risks, there may be times when such a condition can affect a person’s eligibility for a security clearance.
  - Individuals experience a range of reactions to traumatic events. For example, the death of a loved one, divorce, major injury, service in a military combat environment, sexual assault, domestic violence, or other difficult work-related, family, personal, or medical issues may lead to grief, depression, or other responses. The government recognizes that mental health counseling and treatment may provide important support for those who have experienced such events, as well as for those with other mental health conditions. Nothing in this questionnaire is intended to discourage those who might benefit from such treatment from seeking it.
  - **Mental health treatment and counseling, in and of itself, is not a reason to revoke or deny eligibility** for access to classified information or for holding a sensitive position, suitability or fitness to obtain or retain Federal or contract employment, or eligibility for physical or logical access to federally controlled facilities or information systems. 
  - **Seeking or receiving mental health care for personal wellness and recovery may contribute favorably to decisions about your eligibility.**
- [x] Next button -> move to "Competence" section
