### ISSUE TITLE
Applicant Mental Health Diagnosis Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#753]
As an applicant I want to see a summary listing of all mental health diagnosis data I've entered so that I can see all related mental health diagnosis data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of mental health diagnosis
  - [ ] Shown only if mental health diagnosis information has been provided
  - [ ] Listing of each mental health diagnosis entry the applicant has entered
  - [ ] For each required mental health diagnosis entry show the following summary fields: 
    - [ ] Condition: Read-Only label
    - [ ] Dates of diagnosis: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to mental health diagnosis information entry section
      - [ ] Delete - Removes the mental health diagnosis information entry
- Easily toggle between high-level summary data and detail data
