### ISSUE TITLE
Applicant Mental Health Impaired Judgement

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#754]
As an eApp applicant I want to specify whether I have a mental health disorder that substantially adversely affects my judgement and provide the details of my treatment, including date and information for the professional who treated me so that I can provide the information regarding my mental health disorder that substantially adversely affects my judgement and my investigator can review the information.

Acceptance Criteria
- Fields (all required unless specified otherwise)
  - Do you have a mental health or other health condition that substantially adversely affects
your judgment, reliability, or trustworthiness even if you are not experiencing such symptoms
today?
  - Note: If your judgment, reliability, or trustworthiness is not substantially adversely affected by a mental health or other condition, then you should answer "no" even if you have a mental health or other condition requiring treatment. For example, if you are in need of emotional or mental health counseling as a result of service as a first responder, service in a military combat environment, having been sexually assaulted or a victim of domestic violence, or marital issues, but your judgment, reliability or trustworthiness is not substantially adversely affected, then answer "no."
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] No - move on to the next form section 
      - [ ] Yes - An entry is created in the summary section, go to: Did you ever receive or are you currently receiving counseling...
  - Did you ever receive or are you currently receiving counseling or treatment for that condition? (You may choose not to answer this question. However, such consultation or treatment will not disqualify you and is considered to be a positive action.)
    - [ ] Yes/No/I decline to answer - Options
    - [ ] **Branch**
      - [ ] I decline to answer - move on to the next section
      - [ ] No - must provide explanation 
        - [ ] Free text
      - [ ] Yes - An entry is created in the summary section, go to: Provide the dates of counseling or treatment
  - Provide the dates of counseling or treatment.
    - [ ] Date Range (Month/Year) (Estimated/Present)
  - Provide the name, address, and telephone number of the health care professional.
    - [ ] Free Text
    - [ ] Telephone Number
  - Provide the address of the health care professional.
    - [ ] Street address and city
    - [ ] State and Zip Code or Country
  - Provide the name, address, and telephone number of the agency/organization/facility where counseling/treatment was provided
    - [ ] Free Text
      - [ ] Check - same as above (when checked, field optional)
    - [ ] Telephone Number
      - [ ] Check - same as above (when checked, field optional)
  - Provide the address of the agency/organization/facility where counseling/treatment was provided
    - [ ] Street address and city 
    - [ ] State and Zip Code or Country 
      - [ ] Check - same as above (when checked, field optional)
  - Do you have an additional instance where you ever received or are you currently receiving counseling or treatment for that condition? (You may choose not to answer this question. However, such consultation or treatment will not disqualify you and is considered to be a positive action.)
    - [ ] Yes/No/I decline to answer - Options
    - [ ] **Branch**
      - [ ] I decline to answer - move on to the next section
      - [ ] No - move on to next section
      - [ ] Yes - A new entry is created in the summary section, go to: Did you ever receive or are you currently receiving counseling...
  - Have you ever chosen not to follow a prescribed course of treatment for any of these conditions?
    - [ ] Yes/No - Options
    - [ ] **Branch**
      - [ ] Yes - provide explanation
        - [ ] Free text
      - [ ] No - move on to next form section
