### ISSUE TITLE
Applicant Mental Health Impaired Judgement Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#755]
As an applicant I want to see a summary listing of all mental health impairment data I've entered so that I can see all related mental health impairment data entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of mental health impairments
  - [ ] Shown only if mental health impairment information has been provided
  - [ ] Listing of each mental health impairment entry the applicant has entered
  - [ ] For each required mental health impairment entry show the following summary fields: 
    - [ ] Instance ##: Read-Only label (where ## is list number)
    - [ ] Actions:
      - [ ] Edit - goes to mental health impairment information entry section
      - [ ] Delete - Removes the mental health impairment information entry
- Easily toggle between high-level summary data and detail data

**Comment by floresj** [comment]
To maintain consistency, I added the date range summary info rather than just `Instance #`
