### ISSUE TITLE
Applicant Citizenship Foreign Born

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#756]
As an eApp applicant born to U.S. citizen parents in a foreign country I want to provide documentation proving my citizenship status and whether I was born on a military base so that my investigator can verify my citizenship.

Acceptance Criteria
- Fields
  - Help: You answered that you are a U.S. citizen or national by birth, born to U.S. parent(s) in a foreign country.
  - Provide type of documentation of U.S. citizen born abroad.
    - [ ] Choice: FS 240, DS 1350, FS 545, Other (Provide explanation)
    - [ ] Explanation 
      - [ ] Shown if "Other" selected
      - [ ] Multi-line text
  - Provide document number for U.S. citizen born abroad:
    - [ ] Free-text
  - Provide the date the document was issued.
    - [ ] Date with estimate
  - Provide the place of issuance.
    - [ ] Address: City, State, Country
  - Provide the name in which document was issued.
    - [ ] Name block
  - Provide your Certificate of Citizenship number.
    - [ ] Free-text
  - Provide the date the certificate was issued.
    - [ ] Date with estimate
  - Provide the name in which the certificate was issued.
    - [ ] Name block
  - Were you born on a U.S. military installation?
    - [ ] Yes/No choice
    - [ ] **Branch** If Yes
      - [ ] Provide the name of the base.
        - [ ] Free-text

**Comment by bmallred** [comment]
For the field **Provide type of documentation of U.S. citizen born abroad** something similar has been used in the **Relatives** section. See if we can refactor this out (not necessary, but if they are the same then why not?)
