### ISSUE TITLE
Applicant Citizenship Naturalized

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#757]
As an eApp applicant who is a naturalized U.S citizen I want to provide information regarding when I entered the U.S., my path to citizenship, and certificate of naturalzation information so that my investigator can verify my naturalization and current citizenship.

Acceptance criteria
- Fields
  - Help: You answered that you are a naturalized U.S. citizen.
  - Provide the date of entry into the U.S.
    - [x] Date/estimated
  - Provide the location of entry into the U.S.
    - [x] Address: City and State only
  - Provide country(ies) of prior citizenship.
    - [x] Country (Allows for Multiples)
  - Do/did you have a U.S. alien registration number?
    - [x] Yes/No Choice
    - [x] **Branch** Show the next question if Yes selected
      - [x] Provide your U.S. alien registration number on Certificate of Naturalization USCIS, CIS, or INS registration, I-551, I-766.
        - [x] Free-Text
  - Provide your Certificate of Naturalization number (N550 or N570).
    - [x] Free-Text
  - Provide the name of the court that issues the Certificate of Naturalization.
    - [x] Free-Text
  - Provide the address of the court that issued the Certificate of Naturalization.
    - [x] Address block
  - Provide the date the Certificate of Naturalization was issued.
    - [x] Date/estimated
  - Provide the name in which the Certificate of Naturalization was issued.
    - [x] Name block
  - Provide the basis of naturalization. 
    - [x] Choice: Based on my own individual naturalization application, Other (Provide explanation)
    - [x] Explanation

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 what kind of elements would **Provide the basis of naturalization** use? Radio buttons?
