### ISSUE TITLE
Applicant Citizenship Not U.S.

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#759]
As an eApp applicant who is not a U.S citizen I want provide the information surrounding my residence status and alien registration documentation so that my investigator can review my residence status.

Acceptance Criteria
- Fields
  - Help: Not a U.S. Citizen
  - Provide your residence status.
    - [x] Free Text
  - Provide your date of entry into the U.S.
    - [x] Date/estimated
  - Provide your country(ies) of citizenship: 
    - [x] Add country control
    - [x] Allow multiple
  - Provide your place of entry in the U.S.
    - [x] Address: City/State only
  - Provide your alien registration number. (I-551, I-766)
    - [x] Free Text
  - Provide document expiration date (I-766 ONLY).
    - [x] Date/estimated
  - Provide type of document issued. (I-94, U.S. Visa-red foil number, I-20, DS-2019, etc.)
    - [x] Choice: I-94, U.S. Visa (red foil number), I-20, DS-2019, Other (Provide explanation)
    - [x] Explanation (shown if "Other" selected)
      - [x] Multi-line text
  - Provide document number.
    - [x] Free Text
  - Provide the name in which the document was issued.
    - [x] Name block
  - Provide the date document was issued.
    - [x] Date/estimated
  - Provide document expiration date.
    - [x] Date/estimated

**Comment by bmallred** [comment]
## Question: Duplicate expiration fields?

![duplicate-expirations](https://cloud.githubusercontent.com/assets/697855/25020032/eb87489a-205a-11e7-92a3-f1f8a1874238.png)

The highlighted areas are both expiration fields asking for a date. Is it necessary to have both?

**Comment by billy22g** [comment]
My take is that it's an oversight that Jay should track for Donna. Expiration date for one doc vs all others seems like the same thing to me.

**Comment by bmallred** [comment]
## Section with two document expirations listed

![citizenstatus](https://cloud.githubusercontent.com/assets/697855/25049779/714d27d6-2111-11e7-9b8d-b7cbdcc67a40.png)
