### ISSUE TITLE
Applicant Dual Citizenship

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#767]
As an eApp applicant I want to specify whether I have ever held dual citizenship and provide information regarding the country, period of time, date range, and whether I am still a dual citizen so that my investigator can review my citizenship status and validate the information I have provided.

Acceptance Criteria
- Fields
  - Do you now or have you EVER held dual/multiple citizenships?
    - [x] Yes/No Choice
    - [x] **Branch** 
      - [x] if no - move to next form section
      - [x] if yes - show and proceed to dual citizenship detail data entry section below
  - Help: You answered “Yes” to having EVER held dual/multiple citizenship
  - Provide country of citizenship.
    - [x] Free-text 
    - [x] Use country auto-complete
  - Help: During what period of time did you hold citizenship with this country?
  - Provide the date range that you held this citizenship, beginning with the date it was acquired through its termination or “Present,” whichever is appropriate.
    - [x] Date Range with estimated/present
    - [x] ** Branch ** If Present/Current
      - [x] Do you currently hold citizenship with this country?
        - [x] Yes/No Choice
      - [x] Provide explanation
        - [x] Multi-line text
  - How did you acquire this non-U.S. citizenship you now have or previously had?
    - [x] Free Text
  - Have you taken any action to renounce your foreign citizenship?
    - [x] Yes/No Choice
  - Provide explanation
    - [x] Free Text
  - Do you have an additional citizenship to provide?
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another citizenship" - button adds another citizenship detail section
      - [x] If no, user continues to next form section
