### ISSUE TITLE
Applicant Dual Citizenship Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#768]
As an eApp applicant I want to see a summary listing of all countries I've entered for my dual citizenship status so that I can see all countries related to my multiple citizenship entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of dual/multiple citizenships you have listed
  - [x] Shown only if dual citizenship information has been provided
  - [x] Listing of each dual citizenship entry the applicant has entered
  - [x] For each dual citizenship entry show the following summary fields: 
    - [x] Country: Read-Only label
    - [x] Dates of Citizenship: Read-Only label
    - [ ] Actions taken: Read-Only label
    - [x] Accordion Actions:
      - [x] Edit - goes to dual citizenship information entry section
      - [x] Delete - Removes the dual citizenship information entry
- Easily toggle between high-level summary data and detail data

**Comment by bmallred** [comment]
@pjsumm the summary says it should have **Actions taken**. Typically we don't include such large blocks of text... is it okay to omit this from the summary?
