### ISSUE TITLE
Applicant Dual Citizenship Passport

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#769]
As an eApp applicant I want to specify whether I have ever held a passport issued by another country and provide details such as the country, date, and place of issue, the name, number, date of issue on the passport, and whether I've used the passport and where, so that my investigator can review my travel history under foreign issued passports. 

Acceptance Criteria
- Fields
  - Have you EVER been issued a passport (or identity card for travel) by a country other than the U.S.?
    - [x] Yes/No Choice
    - [x] **Branch** 
      - [x] if no - move to next form section
      - [x] if yes - show and proceed to foreign passport detail data entry section below
  - Help: You responded “Yes” to having been issued a passport (or identity card for travel) by a country other than the U.S.
  - Provide the country in which the passport (or identity card) was issued.
    - [x] Country - free text with country lookup
  - Provide the date the passport (or identity card) was issued.
    - [x] Date estimated
  - Provide the place the passport (or identity card) was issued.
    - [x] Address: City/Country only
  - Provide the name in which passport (or identity card) was issued: Last name:
    - [x] Name block
  - Provide the passport (or identity card) number.
    - [x] Free Text
  - Provide the passport (or identity card) expiration date.
    - [x] Date estimated
  - Have you EVER used this passport (or identity card) for foreign travel?
    - [x] Yes/No Choice
    - [x] **Branch** If yes show the question/fields
      - [x] Provide the countries to which you traveled on this passport (or identity card) and the dates involved with each.
        - [x] Country - free text with country lookup
        - [x] Date range present/estimate
  - Do you have an additional foreign passport (or identity card) to report?
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another foreign passport" - button adds another foreign passport detail section
      - [x] If no, user continues to next form section

**Comment by bmallred** [comment]
Need to get with @Jay-Neighbours-I72 and determine the best way to handle the possible accordion-in-accordion issue with the foreign passports and travel.
