### ISSUE TITLE
Applicant Dual Citizenship Passport Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#770]
As an applicant I want to see a summary listing of all passports issued by other countries that I've entered so that I can see all related foreign passport entries, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of foreign passports
  - [x] Shown only if foreign passport information has been provided
  - [x] Listing of each foreign passport entry the applicant has entered
  - [x] For each foreign passport entry show the following summary fields: 
    - [x] Country: Read-Only label
    - [x] Dates issued: Read-Only label
    - [x] Actions:
      - [x] Edit - goes to foreign passport information entry section
      - [x] Delete - Removes the foreign passport information entry
- Easily toggle between high-level summary data and detail data
