### ISSUE TITLE
Applicant People Who Know You Well Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#855]
As an eApp applicant I want to see a summary listing of all people I've entered for the people who know me well section of the SF86 so that I can see a listing of all people I've chosen to reference, reopen and edit specific people entries, or remove a person\people.

Acceptance Criteria
- Summary of people who know you well
  - [ ] Shown only if person information has been provided
  - [ ] Listing of each person entry the applicant has entered
  - [ ] Visual indicator of how many of the 3 have been entered (like schools) 
  - [ ] Visual indicator for seven years of coverage
  - [ ] For each person entry show the following summary fields: 
    - [ ] Name: Read-Only label
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to person iformation entry section
      - [ ] Delete - Removes the person information entry
- Easily toggle between high-level summary data and detail data

**Comment by bmallred** [comment]
- [ ] Component mixture of `SummaryProgress` and `SummaryCounter`
 - [ ] Gap analysis to cover years as well as quota of items
