### ISSUE TITLE
Applicant Marital/Relationship Status Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#856]
As an eApp Applicant I want to provide the name(s), place of birth, citizenship, social security number, location, and contact information for the person I am currently in a relationship with so that my investigator can review my relationship status information.

Acceptance Criteria
- Fields
  - Help: You selected “Currently in a civil marriage,” “currently in a legally recognized civil union or legally recognized domestic partnership” or “Separated.” Complete the following about the person with whom you are in a civil marriage, legally recognized civil union, or legally recognized domestic partnership, or the person from whom you are currently separated.
  - Provide full name.
    - [ ] Name block
  - Provide date of birth.
    - [ ] Date (Est.)
  - Provide place of birth.
    - [ ] Address block (city,county,state/country)
  - If the person is foreign born, provide one type of documentation that he or she possesses and the document number.
    - [ ] **Branch** if born in a foreign country
      - [ ] Born Abroad to U.S. Parents:
        - [ ] Choice: FS 240 or 545; DS 1350
      - [ ] Naturalized:
        - [ ] Choice: Alien Registration (on Certificate of Naturalization—utilize USCIS, CIS, or INS Registration number); Permanent Resident Card (I-551); Certificate of Naturalization (N550 or N570)
      - [ ] Derived:
        - [ ] Choice: Alien Registration (on Certificate of Citizenship—utilize USCIS, CIS, or INS Registration number); Permanent Resident Card (I-551); Certificate of Citizenship (N560 or N561)
      - [ ] Not a U.S. Citizen:
        - [ ] Choice: I-551 Permanent Resident; I-766 Employment Authorization; I-94 Arrival-Departure Record;U.S. Visa (red foil number);I-20 Certificate of Eligibility for Non-Immigrant-F1-Student; DS-2019 Certificate of Eligibility of Exchange Visitor-J1-Status
      - [ ] Other (Provide explanation)
        - [ ] Explanation 
          - [ ] Free Text
    - Provide document number
      - [ ] Free Text
    - Provide document expiration date, if applicable.
      - [ ] Date - Estimated
  - Provide U.S. Social Security Number. 
    - [ ] Check:  Not applicable
    - [ ] SSN fields
  - Provide other names used (such as maiden name, names by other marriages, civil marriages, legally recognized civil unions, or legally recognized domestic partnerships, nicknames, etc., and provide dates used for each name).
    - [ ] Check: Not applicable
    - [ ] Name Block
    - [ ] Check: Maiden Name
      - [ ] Dates Used
        - [ ] Date Range (Estimated/Present)
  - Provide country(ies) of Citizenship.
    - [ ] Multiple Country selection control
  - Provide date when you entered into your civil marriage, civil union, or domestic partnership.
    - [ ] Date (Estimated)
  - Provide location.
    - [ ] Address: City, County, State or Country
  - Provide current address, if different than your current address.
    - [ ] Check: Use my current address.
    - [ ] Address block
  - Provide telephone number.
    - [ ] Check: Use my current telephone number
    - [ ] Telephone block
  - Provide email address
    - [ ] Free Text (with email validation)
  - Does the person have an APO/FPO address?
    - [ ] Choice: Yes/No
      - [ ] **Branch** If yes show address block with APO/FPO
  - Are you separated?
    - [ ] Choice: Yes/No
      - [ ] **Branch** If Separated show fields
        - [ ] Provide date of separation.
          - [ ] Date (Estimated)
        - [ ] If legally separated, provide the location of the record. 
          - [ ] Check: Not Applicable
          - [ ] Address: City, State and Zip Code or Country
  - Do you have a person from whom you are divorced/dissolved, annulled, or widowed to report?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another person" - button adds another person detail section
      - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
May need to go over **Branch if born in a foreign country** with @Jay-Neighbours-I72

**Comment by bmallred** [comment]
[ ] Refactor ApplicantSSN to use an SSN component within the Form directory.

**Comment by bmallred** [comment]
Determine behavior of **Use my current telephone number** since we allow for multiple. Maybe a suggestion?

**Comment by bmallred** [comment]
- [ ] Determine behavior of **Use my current address**
