### ISSUE TITLE
Applicant No Longer Married Details

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#857]
As an eApp Applicant I want to provide information about any person from whom I am divorced/dissolved, annulled, or widowed including their name, birth information, citizenship, contact information, and the details of what happened so that my investigator can review the circumstance surround the ending of my marriage.

Acceptance Criteria
- Fields
  - Do you have a person from whom you are divorced/dissolved, annulled, or widowed to report?
    - [ ] Choice: Yes/No
    - [ ] **Branch** If Separated show fields
  - Help: Provide information about any person from whom you are divorced/dissolved, annulled, or widowed.
  - Provide the full name.
    - [ ] Name block
  - Provide the date of birth.
    - [ ] Date (Estimated)
  - Provide the place of birth.
    - [ ] Address block
  - Provide the country(ies) of citizenship.
    - [ ] Country multiple select
  - Provide the telephone number.
    - [ ] Check: I don’t know
    - [ ] Telephone block
  - Provide the date your civil marriage, civil union, or domestic partnership was legally recognized.
Date (Estimated)
  - Provide the location.
    - [ ] Address: City, State or Country
  - Provide the date divorced/dissolved, annulled or widowed
    - [ ] Date (Estimated)
  - Provide the status.
    - [ ] Choice: Divorced/Dissolved; Widowed; Annulled
    - [ ] **Branch** if Divorced/Dissolved or Annulled
      - Provide where the record of divorce/dissolution or annulment is located.
        - [ ] Address block
      - Is this person deceased?
        - [ ] Choice: I don’t know, Yes, No
        - [ ] **Branch** If Not Deceased get last address
          - Provide last known address of the person from whom you are divorced/dissolved or annulled. 
            - [ ] Check: I don’t know
            - [ ] Address block   
  - Do you have any additional person(s) from whom you are divorced/dissolved, annulled, or widowed to report?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another person" - button adds another person detail section
      - [ ] If no, user continues to next form section
