### ISSUE TITLE
Applicant No Longer Married Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#858]
As an eApp applicant I want to see a summary listing of all people I've entered for the people from whom I am divorced/dissolved, annulled, or widowed section of the SF86 so that I can see a listing of all people with whom I was once married, reopen and edit specific people entries, or remove a person\people.

Acceptance Criteria
- Summary of marital/relationship History
  - [ ] Shown only if marital/relationship history information has been provided
  - [ ] Listing of each fmarital/relationship history entry the applicant has entered
  - [ ] For each marital/relationship history entry show the following summary fields: 
    - [ ] Person: Read-Only label
    - [ ] Date Range: Read-Only label
    - [ ] Status: Read-Only label 
    - [ ] Actions:
      - [ ] Edit - goes to marital/relationship history information entry section
      - [ ] Delete - Removes the marital/relationship history information entry
- Easily toggle between high-level summary data and detail data

**Comment by floresj** [comment]
Switching summary to use date of divorce which is a normal date control and not a date range.
