### ISSUE TITLE
Applicant Cohabitation Status

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#859]
As an eApp Applicant I want to provide the name(s), place of birth, citizenship, social security number, location, and contact information for the person I am currently cohabiting with so that my investigator can review my cohabitation relationship status information.

Acceptance Criteria
- Fields
  - Do you presently reside with a person, other than a spouse or legally recognized civil union/domestic partner, with whom you share bonds of affection, obligation, or other commitment, as opposed to a person with whom you live for reasons of convenience (e.g. a roommate)? If so, complete the following. If the person was born outside the U.S., provide citizenship information
    - [x] Choice: Yes/No
    - [x] **Branch**
      - [x] No - move on to next form section
      - [x] Yes - show data entry fields for cohabitant
  - Help: You have indicated that you currently have a cohabitant
  - Provide cohabitant full name.
    - [x] Name block
  - Provide the date of birth.
    - [x] Date (Est.)
  - Provide the place of birth.
    - [x] Address block (city,county,state/country)
  - For your foreign born cohabitant, indicate one type of documentation that he or she possesses and the document number
    - [x] **Branch** if cohabitant born in a foreign country
      - [x] Born Abroad to U.S. Parents:
        - [x] Choice: FS 240 or 545; DS 1350
      - [x] Naturalized:
        - [x] Choice: Alien Registration (on Certificate of Naturalization—utilize USCIS, CIS, or INS Registration number); Permanent Resident Card (I-551); Certificate of Naturalization (N550 or N570)
      - [x] Derived:
        - [x] Choice: Alien Registration (on Certificate of Citizenship—utilize USCIS, CIS, or INS Registration number); Permanent Resident Card (I-551); Certificate of Citizenship (N560 or N561)
      - [x] Not a U.S. Citizen:
        - [x] Choice: I-551 Permanent Resident; I-766 Employment Authorization; I-94 Arrival-Departure Record;U.S. Visa (red foil number);I-20 Certificate of Eligibility for Non-Immigrant-F1-Student; DS-2019 Certificate of Eligibility of Exchange Visitor-J1-Status
      - [x] Other (Provide explanation)
        - [x] Explanation 
          - [x] Free Text
    - Provide document number
      - [x] Free Text
    - Provide document expiration date, if applicable.
      - [x] Date - Estimated
  - Provide your cohabitant’s U.S. Social Security Number. 
    - [x] Check:  Not applicable
    - [x] SSN fields
  - Provide other names used by your cohabitant (such as maiden name, names by other marriages, etc., and provide dates each name was used)
    - [x] Check: Not applicable
    - [x] Name Block
    - [x] Check: Maiden Name
      - [x] Dates Used
        - [x] Date Range (Estimated/Present)
  - Provide your cohabitant’s country(ies) of Citizenship.
    - [x] Multiple Country selection control
  - Provide date cohabitation residing with person began.
    - [x] Date (Estimated)
  - Do you have an additional cohabitant to report?
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another cohabitant" - button adds another cohabitant detail section
      - [x] If no, user continues to next form section
- [x] Validate that the spouse is not added as a cohabitant

**Comment by bmallred** [comment]
- [ ] Is the **place of birth** similar to previous use case or just an address?

**Comment by bmallred** [comment]
Very similar to #856
