### ISSUE TITLE
Applicant Cohabitation Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#860]
As an eApp applicant I want to see a summary listing of all people I've entered for the cohabitants section of the SF86 so that I can see a listing of all people with which I am currently cohabiting, reopen and edit specific cohabitant entries, or remove a cohabitant(s).

Acceptance Criteria
- Summary of cohabitants
  - [ ] Shown only if cohabitant information has been provided
  - [ ] Listing of each cohabitant entry the applicant has entered
  - [ ] For each cohabitant entry show the following summary fields: 
    - [ ] Person: Read-Only label
    - [ ] Date Range: Read-Only label
    - [ ] Actions:
      - [ ] Edit - goes to cohabitant information entry section
      - [ ] Delete - Removes the cohabitant information entry
- Easily toggle between high-level summary data and detail data
