### ISSUE TITLE
Applicant Foreign Contacts Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#861]
As an eApp applicant I want to see a summary listing of all people I've entered for the foreign contacts section of the SF86 so that I can see a listing of all foreign contacts I've had in the past 7 years, reopen and edit specific foreign cohabitant entries, or remove a cohabitant(s).

Acceptance Criteria
- Summary of Foreign Contacts
  - [x] Shown only if foreign contacts have been provided
  - [x] Listing of each foreign contact entry the applicant has entered
  - [x] For each foreign contact entry show the following summary fields: 
    - [x] Foreign contact name: Read-Only label
    - [x] Country: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to foreign contact entry section
      - [x] Delete - Removes the foreign contact information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
Showing country doesn't work right if the country name is long. And what happens if there are multiple countries of citizenship here? Seems to only show the first. Wonder what we gain by showing country here, maybe we should just remove it? cc: @Jay-Neighbours-I72 

<img width="887" alt="screen shot 2017-05-08 at 10 56 13 am" src="https://cloud.githubusercontent.com/assets/5091167/25815098/fd046216-33dc-11e7-8c1d-a059a412ac02.png">

**Comment by bmallred** [comment]
We can definitely do that. It also gets rid of the use case of which country to display as well (since theirs may be multiple.

**Comment by billy22g** [comment]
Deferring to @Jay-Neighbours-I72 for final call on this.

**Comment by bmallred** [comment]
There are dates within this section as well which we could use in its place:

 - approximate date of first contact
 - approximate date of last contact

**Comment by Jay-Neighbours-I72** [comment]
I am good with removing country here, I would say that the person's name is the most important so that can remain top level and all other info is within the accordion item

@billy22g @bmallred

**Comment by bmallred** [comment]
Removed the country in the summary in https://github.com/truetandem/e-QIP-prototype/commit/96815de4ba6eb2273d12b9d1c8133e5fc0989aa9

**Comment by billy22g** [comment]
LGTM
