### ISSUE TITLE
Applicant Foreign Activities - Financial Interests

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#862]
As an eApp applicant I want to provide information regarding any foreign financial interests I, or my spouse/partner/cohabitant, have ever had so that my investigator can review the level of foreign financial interests we have had. 

Acceptance Criteria
- Fields
  - Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children EVER had any foreign financial interests (such as stocks, property, investments, bank accounts, ownership of corporate entities, corporate interests or exchange traded funds (ETFs) held in specific geographical or economic sectors) in which you or they have direct control or direct ownership? (Exclude financial interests in companies or diversified mutual funds or diversified ETFs that are publicly traded on a U.S. exchange.)
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Specify
  - Specify: 
    - [ ] Choice: (check all that apply) Yourself, Spouse or legally recognized civil union/domestic partner, Cohabitant, Dependent children
  - Provide the type of financial interest.
    - [ ] Free Text
  - Provide the date acquired
    - [ ] Date (Estimated)
  - Provide how the financial interest was acquired (such as purchase, gift, etc.)
    - [ ] Free Text
  - Provide the cost (in U.S. dollars) at time of acquisition. 
    - [ ] Estimated
    - [ ] Free Text
  - Provide the current value (in U.S. dollars) or the value at the time control or ownership was sold, lost or otherwise disposed of. 
    - [ ] Estimated
    - [ ] Free Text
  - Provide the date control or ownership was relinquished.
    - [ ] Date (Estimated)
    - [ ] Not applicable:
  - Provide explanation of how interest control or ownership was sold, lost or otherwise disposed of.
    - [ ] Free Text
  - Are there any co-owners of this foreign financial interest?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide full name of co-owner
        - [ ] You responded ‘Yes’ to there being co-owners; provide the name, address, citizenship, and relationship of the co-owner(s).
        - [ ] Provide full name of co-owner.
          - [ ] Name Block
        - [ ] Provide co-owner current address.
          - [ ] Address Block
        - [ ] Provide co-owner’s country(ies) of citizenship.
          - [ ] Country Select
        - [ ] Provide the nature of your relationship with the co-owner.
          - [ ] Free Text
        - [ ] Are there any additional co-owners of this foreign financial interest? 
          - [ ] Yes/No Option
            - [ ] Yes - add another section 
            - [ ] No - move on to the next section
    - Do you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children have any additional foreign financial interests?
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another instance" - button adds another foreign financial interest detail section
        - [ ] If no, user continues to next form section

**Comment by floresj** [comment]
![selection_069](https://cloud.githubusercontent.com/assets/5938731/25585385/3cd92d06-2e68-11e7-84c7-1579c8a614e0.png)

**Comment by billy22g** [comment]
LGTM
