### ISSUE TITLE
Applicant Foreign Activities - Financial Interests Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#863]
As an eApp applicant I want to see a summary listing of all foreign financial interests I've entered for so that I can see a listing of all foreign financial interests I've ever had, reopen and edit specific foreign financial interest entries, or remove an entry.

Acceptance Criteria
- Summary of foreign financial interests
  - [ ] Shown only if foreign financial interests have been provided
  - [ ] Listing of each foreign financial interest the applicant has entered
  - [ ] For each foreign financial interests entry show the following summary fields: 
    - [ ] Who: Read-Only label
    - [ ] Type: Read-Only label
    - [ ] Amount: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to foreign financial interests entry section
      - [ ] Delete - Removes the foreign financial interests information entry
- Easily toggle between high-level summary data and detail data

**Comment by pjsumm** [comment]
![foreign financial interests](https://cloud.githubusercontent.com/assets/12962390/25616572/9d17d9f8-2f0b-11e7-8891-7762d35bd2be.png)

**Comment by billy22g** [comment]
LGTM
