### ISSUE TITLE
Applicant Foreign Financial Interests Other

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#864]
As an eApp applicant I want to provide information regarding any foreign financial interests controlled by another on our behalf that I, or my spouse/partner/cohabitant, have ever had so that my investigator can review the level of foreign financial interests we have had. 

Acceptance Criteria
- Fields
  - Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children EVER had any foreign financial interests that someone controlled on your behalf?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Specify
  - Specify
    - [ ] Choice: (check all that apply) Yourself, Spouse or legally recognized civil union/domestic partner, Cohabitant, Dependent children
  - Provide the type of financial interest.
    - [ ] Free Text
  - Provide the name of the individual who controls this financial interest on your behalf.
    - [ ] Name - first Last
  - Provide this individual’s relationship to you.
    - [ ] Free Text
  - Provide the date the financial interest was acquired.
    - [ ] Date (Estimated)
  - Provide the cost (in U.S. dollars) at time of acquisition. 
    - [ ] Estimated
    - [ ] Free Text - money
  - Provide details regarding how it was acquired (such as purchase, gift, etc.).
    - [ ] Free Text
  - Provide the current value (in U.S. dollars) or value at the time interest was sold, lost or otherwise disposed of. 
    - [ ] Estimated
    - [ ] Free Text
  - Provide the date interest was sold, lost, or otherwise disposed of. 
    - [ ] Not applicable
    - [ ] Date (Estimated)
  - Provide explanation if interest was sold, lost, or otherwise disposed of.
    - [ ] Free Text
  - Are there any co-owners of the foreign financial interest controlled on your behalf?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide full name of co-owner
        - [ ] You responded ‘Yes’ to there being co-owners; provide the name, address, citizenship, and relationship of the co-owner(s).
        - [ ] Provide full name of co-owner.
          - [ ] Name Block
        - [ ] Provide co-owner current address.
          - [ ] Address Block
        - [ ] Provide co-owner’s country(ies) of citizenship.
          - [ ] Country multi-select
        - [ ] Provide the nature of your relationship with the co-owner.
          - [ ] Free Text
        - [ ] Are there any additional co-owners for this foreign financial interest controlled on your behalf to report?
          - [ ] Yes/No Option
            - [ ] Yes - add another section 
            - [ ] No - move on to the next section
  - Do you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children have any additional foreign financial interests controlled on your behalf?
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another instance" - button adds another foreign financial interests controlled on your behalf detail section
        - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
## Content guide

![foreign-1](https://cloud.githubusercontent.com/assets/697855/25595894/932fd232-2e94-11e7-8b69-f257cb9543a1.png)

**Comment by billy22g** [comment]
LGTM
