### ISSUE TITLE
Applicant Foreign Financial Interests Other Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#865]
As an eApp applicant I want to see a summary listing of all foreign financial interests controlled by someone else I've entered for so that I can view all foreign financial interests controlled by someone else I've ever had, reopen and edit specific foreign financial interest entries, or remove an entry.

Acceptance Criteria
- Summary of foreign financial interests controlled by someone else
  - [ ] Shown only if foreign financial interests controlled by someone else have been provided
  - [ ] Listing of each foreign financial interest controlled by someone else the applicant has entered
  - [ ] For each foreign financial interests controlled by someone else entry show the following summary fields: 
    - [ ] Person: Read-Only label
    - [ ] Type: Read-Only label
    - [ ] Amount: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to foreign financial interests controlled by someone else entry section
      - [ ] Delete - Removes the foreign financial interests controlled by someone else information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
