### ISSUE TITLE
Applicant Foreign Real Estate

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#866]
As an eApp applicant I want to provide information regarding any foreign real estate that I, or my spouse/partner/cohabitant, have ever owned so that my investigator can review the level of foreign real estate interests we have had, or plan to have. 

Acceptance Criteria
- Fields
  - Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children EVER owned, or do you anticipate owning, or plan to purchase real estate in a foreign country?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Specify
  - Specify: 
    - [ ] Choice: (check all that apply) Yourself, Spouse or legally recognized civil union/domestic partner, Cohabitant, Dependent children
  - Provide the type of real estate property (such as home, business, etc.).
    - [ ] Free Text
  - Provide the location/address of property.
    - [ ] Address: Street, City, Country
  - Provide the date of the purchase or be acquired
    - [ ] Date (Estimated)
  - Provide how the foreign real estate was or is to be acquired (such as purchase, gift, etc.).
    - [ ] Free Text
  - Provide the date sold, if applicable.
    - [ ] Date (Estimated)
  - Provide the cost (in U.S. dollars) when sold or expected at time of acquisition. 
    - [ ] Estimated
    - [ ] Free Text - money
  - Are/were/will there any co-owners of this foreign real estate?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide full name of co-owner.
        - [ ] You responded ‘Yes’ to there being any co-owners.
        - [ ] Provide full name of co-owner.
          - [ ] Name Block
        - [ ] Provide co-owner current address.
          - [ ] Address Block
        - [ ] Provide co-owner’s country(ies) of citizenship.
          - [ ] Country multi-Select
        - [ ] Provide the nature of your relationship with the co-owner.
          - [ ] Free Text
        - [ ] Are there any additional co-owners of this foreign financial interest? 
          - [ ] Yes/No Option
            - [ ] Yes - add another section 
            - [ ] No - move on to the next section
  - Do you have an additional instance of you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children EVER having owned, or anticipate owning, or planning to purchase real estate in a foreign country?
      - [ ] If yes use the button below to add another.
      - [ ] **Branch**
        - [ ] "Add another instance" - button adds another foreign real estate interest detail section
        - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
## Content guide

![foreign-2](https://cloud.githubusercontent.com/assets/697855/25595941/ca76e348-2e94-11e7-91a1-b3260be29afc.png)

**Comment by billy22g** [comment]
LGTM
