### ISSUE TITLE
Applicant Foreign Real Estate Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#867]
As an eApp applicant I want to see a summary listing of all foreign real estate I've owned or plan to own so that I can view all of my foreign real estate, reopen and edit specific foreign real estate entries, or remove an entry.

Acceptance Criteria
- Summary of foreign real estate interests
  - [ ] Shown only if foreign real estate interests entered
  - [ ] Listing of each foreign real estate interests the applicant has entered
  - [ ] For each foreign real estate interest entry show the following summary fields: 
    - [ ] Who: Read-Only label
    - [ ] Date Purchased: Read-Only label
    - [ ] Address: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to foreign real estate interests entyy section
      - [ ] Delete - Removes the foreign foreign real estate interests information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
