### ISSUE TITLE
Applicant Foreign Benefits

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#868]
As an eApp applicant I want to provide information regarding any benefits from a foreign country that I, or my spouse/partner/cohabitant, have had in the last seven years, or plan to have in the future so that my investigator can review the benefits we have received, or plan to receive, from a foreign country. 

Acceptance Criteria
- Fields
  - As a U.S. citizen, have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children received in the last seven (7) years, or are eligible to receive in the future, any educational, medical, retirement, social welfare, or other such benefit from a foreign country?
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Specify
  - Specify (check all that apply) 
      - [ ] Choice: Yourself, Spouse or legally recognized civil union/domestic partner, Cohabitant, Dependent children
  - Provide the type of benefit:
    - [ ] Choice: Educational, Medical, Retirement, Social Welfare, Other such benefit (Provide explanation)
    - [ ] Explanation: Free Text
  - Provide the frequency of the benefit. 
    - [ ] Choice: Onetime benefit, Future benefit, Continuing benefit, Other (Provide explanation)
    - [ ] Explanation: Free Text
    - [ ] **Branch** If Onetime Benefit
      - [ ] You have indicated that you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children received a onetime benefit from a foreign country
      - [ ] Provide the date the benefit was received.
        - [ ] Date (Estimated)
      - [ ] Provide the name of the country providing the benefit.
        - [ ] Country
      - [ ] Provide the total value (in U.S. dollars) of the benefit received. 
        - [ ] Estimated
        - [ ] Free Text
      - [ ] Provide the reason this benefit was received. 
        - [ ] Free Text
      - [ ] As a result of this benefit are you, your spouse or legally recognized civil union/domestic partner, your cohabitant, or dependent children obligated in any way to this foreign country? If yes provide explanation
        - [ ] Choice: Yes/No
          - [ ] If Yes - Explanation - Free Text
    - [ ] **Branch** If Future Benefit
      - [ ] You have indicated that you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children expect to receive a benefit from a foreign country.
      - [ ] Provide the date the benefit will begin.
        - [ ] Date (Estimated)
      - [ ] Provide the frequency the benefit will be received.
        - [ ] Choice: Annually, Quarterly, Monthly, Weekly, Other (Provide explanation)
        - [ ] Explanation: Free Text
      - [ ] Provide the name of the country providing this benefit.
        - [ ] Country Select
      - [ ] Provide the value (in U.S. dollars) of the benefit to be received. 
        - [ ] Estimated
        - [ ] Free Text
      - [ ] Provide the reason this benefit will be received.
        - [ ] Free Text
      - [ ] As a result of this benefit are you, your spouse or legally recognized civil union/domestic partner, your cohabitant, or dependent children obligated in any way to this foreign country? If yes provide explanation.
        - [ ] Choice: Yes/No
          - [ ] If Yes - Explanation - Free Text
    - [ ] **Branch** If Continuing Benefit
      - [ ] You have indicated that you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children receive a continuing or other benefit from a foreign country.
      - [ ] Provide the date the benefit began. 
        - [ ] Date (Estimated)
      - [ ] Provide the date the benefit is expected to end.
        - [ ] Date (Estimated)
      - [ ] Provide the frequency that this benefit is received.
        - [ ] Choice: Annually, Quarterly, Monthly, Weekly, Other (Provide explanation)
        - [ ] Explanation: Free Text
      - [ ] Provide the name of the country providing this benefit.
        - [ ] Country Select
      - [ ] Provide the total value (in U.S. dollars) of the benefit to be received. 
        - [ ] Estimated
        - [ ] Free Text
      - [ ] Provide the reason this benefit will be received.
        - [ ] Free Text
      - [ ] As a result of this benefit are you, your spouse or legally recognized civil union/domestic partner, your cohabitant, or dependent children obligated in any way to this foreign country? If yes provide explanation.
        - [ ] Choice: Yes/No
          - [ ] If Yes - Explanation - Free Text
  - Do you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children receive any additional benefits from a foreign country?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another foreign benefit detail section
      - [ ] If no, user continues to next form section

**Comment by bmallred** [comment]
## Content guide

![foreign-3](https://cloud.githubusercontent.com/assets/697855/25595997/071f1dce-2e95-11e7-9cd9-2a968773356e.png)

**Comment by billy22g** [comment]
Future and continuing benefits doesn't accept future dates.

<img width="699" alt="screen shot 2017-05-08 at 4 04 07 pm" src="https://cloud.githubusercontent.com/assets/5091167/25827383/29e18432-3408-11e7-9ed0-60239d92a108.png">

<img width="714" alt="screen shot 2017-05-08 at 4 04 42 pm" src="https://cloud.githubusercontent.com/assets/5091167/25827386/2f60a442-3408-11e7-925e-038d543f440b.png">

**Comment by billy22g** [comment]
Also, this field does not validate.

<img width="707" alt="screen shot 2017-05-08 at 4 11 15 pm" src="https://cloud.githubusercontent.com/assets/5091167/25827566/1212b794-3409-11e7-9d69-e8751021694e.png">

**Comment by floresj** [comment]
There's still some working being done on this issue. I forgot to move it back to in progress.

**Comment by billy22g** [comment]
LGTM
