### ISSUE TITLE
Applicant Foreign Benefits Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#869]
As an eApp applicant I want to see a summary listing of all benefits I have received from a foreign country in the past 7 years, or will received in the future, so that I can view all foreign benefits I've had, or will have, reopen and edit specific foreign benefit entries, or remove an entry.

Acceptance Criteria
- Summary of foreign benefits
  - [ ] Shown only if foreign benefits entered
  - [ ] Listing of each foreign benefit the applicant has entered
  - [ ] For each foreign benefit entry show the following summary fields: 
    - [ ] Who: Read-Only label
    - [ ] Date Purchased: Read-Only label
    ~~- [ ] Address: Read-Only label~~ No address field in this section. Going to use Country.
    - [ ] Actions:
      - [ ] Edit - click on item to go to foreign benefit entry section
      - [ ] Delete - Removes the foreign benefit information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
