### ISSUE TITLE
Applicant Foreign Financial Support Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#871]
As an eApp applicant I want to see a summary listing of all financial support I've ever provided for foreign nationals, so that I can view all foreign financial support obligations, reopen and edit specific foreign financial support entries, or remove an entry.

Acceptance Criteria
- Summary of foreign financial support
  - [x] Shown only if foreign financial support entered
  - [x] Listing of each foreign financial support the applicant has entered
  - [x] For each foreign financial support entry show the following summary fields: 
    - [x] Name: Read-Only label
    - [x] Country: Read-Only label
    - [x] Actions:
      - [x] Edit - Click on item to go to foreign benefit information entry
      - [x] Delete - Removes the foreign benefit information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
