### ISSUE TITLE
Applicant Family Foreign Business Advice

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#873]
As an eApp applicant I want to provide information regarding advise or consultation my immediate family has given to foreign businesses in the past sever years so that my investigator can see my immediate family's involvement in foreign business interests.

Acceptance Criteria
- Fields
  - For this question, “Immediate Family” means your spouse or legally recognized civil union/domestic partner, parents, step-parents, siblings, half and step-siblings, children, step-children, and cohabitant. Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or any member of your immediate family in the last seven (7) years been asked to provide advice or serve as a consultant, even informally, by any foreign government official or agency? (Answer “No’ if all the advice or support was authorized pursuant to official U.S. Government business.)
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the name of the government official
  - Provide the name of the government official.
    - [x] Name Block
  - Provide the name of the agency.
    - [x] Free Text
  - Provide the country with which the government official or agency is affiliated.
    - [x] Country select
  - Provide the date of the request.
    - [x] Date (Estimated)
  - Provide the circumstances of request.
    - [x] Free Text
  - Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or any member of your immediate family in the last seven (7) years been asked to provide advice or serve as a consultant, even informally, by any other foreign government official or agency? (Answer ‘No’ if all the advice or support was authorized pursuant to official U.S. Government business.)
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another instance" - button adds another family foreign business advice detail section
      - [x] If no, user continues to next form section

**Comment by billy22g** [comment]
Need to remove "If yes use the button below to add another interest."

<img width="1277" alt="screen shot 2017-05-08 at 11 30 56 am" src="https://cloud.githubusercontent.com/assets/5091167/25816625/dfd11fb8-33e1-11e7-89e3-8c7923229cee.png">

**Comment by billy22g** [comment]
Additionally, we removed the "Immediate Family" definition from the question. Was that intentional? cc: @Jay-Neighbours-I72

**Comment by bmallred** [comment]
@billy22g I think I missed adding the definition of immediate family.

**Comment by bmallred** [comment]
Added missing paragraph in [564d289](https://github.com/truetandem/e-QIP-prototype/pull/1165/commits/564d289c567876d43979fc0bd5e09f9515caab3e#diff-963d509a83d23add3d4e46cb59a1be9fR5650)

**Comment by billy22g** [comment]
LGTM
