### ISSUE TITLE
Applicant Foreign Business Job Offer

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#875]
As an eApp applicant I want to provide information regarding foreign business job offers I've received in the past seven years so that my investigator can see my offers from foreign business interests. 

Acceptance Criteria
- Field
  - Has any foreign national in the last seven (7) years offered you a job, asked you to work as a consultant, or consider employment with them?
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the name of the foreign national who made the offer.
  - Provide the name of the foreign national who made the offer.
    - [x] Name block
  - Provide a description of the position offered.
    - [x] Free Text
  - Provide the date when this offer was extended.
    - [x] Date (Estimated)
  - Provide the location where this occurred.
    - [x] Address: City, State, and Zip Code or Country
  - Did you accept the offer?
    - [x] Choice: Yes/No
    - [x] Explanation - Free Text
  - Has any additional foreign national, in the last seven (7) years, offered you a job, asked you to work as a consultant, or consider employment with them?
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another instance" - button adds another foreign business job offer detail section
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign business job offer](https://cloud.githubusercontent.com/assets/12962390/25616737/7ec1a33e-2f0c-11e7-9fbd-dc70c276de23.png)

**Comment by billy22g** [comment]
I don't think this should say "Add another interest" or "If yes use the button below to add another interest" cc: @Jay-Neighbours-I72 for the correct text

<img width="822" alt="screen shot 2017-05-08 at 4 49 53 pm" src="https://cloud.githubusercontent.com/assets/5091167/25828631/7bbe23d6-340e-11e7-8a64-3d18bb81eab6.png">

**Comment by Jay-Neighbours-I72** [comment]
Agreed @billy22g

**Comment by billy22g** [comment]
LGTM
