### ISSUE TITLE
Applicant Foreign Business Job Offer Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#876]
As an eApp applicant I want to see a summary listing of foreign business job offers for the past seven years that I've provided, so that I can view all of my foreign business job offers, reopen and edit specific foreign business job offer entries, or remove an entry.

Acceptance Criteria
- Summary of family foreign business job offer
  - [x] Shown only if family foreign business job offer entered
  - [x] Listing of each family foreign business job offer the applicant has entered
  - [x] For each family foreign business job offer entry show the following summary fields: 
    - [x] Job Description: Read-Only label
    - [x] Date of offer: Read-Only label
    - [x] Actions:
      - [x] Edit - Click on item to go to family foreign business job offer information entry
      - [x] Delete - Removes the family foreign business job offer information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
"Did you accept the offer?" should be a Yes/No checkboxes with the explanation as supplementary info below it. The content guide is weird on this one though.

<img width="697" alt="screen shot 2017-05-10 at 12 02 20 pm" src="https://cloud.githubusercontent.com/assets/5091167/25913648/b88380de-3578-11e7-8f88-10e42f429576.png">

Content guide:
<img width="654" alt="screen shot 2017-05-10 at 12 03 14 pm" src="https://cloud.githubusercontent.com/assets/5091167/25913655/bde23fa2-3578-11e7-8b88-59ecb22acfa4.png">

**Comment by bmallred** [comment]
## Preview

![job-offer](https://cloud.githubusercontent.com/assets/697855/25922585/bf71126a-35a7-11e7-892c-94d6846c9e88.png)

**Comment by lauraponce** [comment]
Looks good!
