### ISSUE TITLE
Applicant Foreign Business Conferences

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#879]
As an eApp applicant I want to provide information regarding any foreign business conferences, trade shows, or seminars that I have attended in the past seven years so that my investigator can review my involvement with foreign businesses.

Acceptance Criteria
- Fields
  - Have you in the last seven (7) years attended or participated in any conferences, trade shows, seminars, or meetings outside the U.S.? (Do not include those you attended or participated in on official business for the U.S. government.)
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the name and description of event.
  - Provide the name and description of event.
    - [x] Free Text
  - Provide the name of sponsoring organization.
    - [x] Free Text
  - Provide the city where the event was held.
    - [x] Free Text
  - Provide the country where the event was held.
    - [x] Country select
  - Provide the dates for the event.
    - [x] Date Range (Estimated/Present)
  - Provide the purpose of the event.
    - [x] Free Text
  - Was there any subsequent contact with any foreign nationals as a result of the event?
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - Add a detail entry section
        - [x] You responded ‘Yes’ to there having been subsequent contact with any foreign nationals as a result of the event.
        - [x] Provide explanation.
          - [x] Free Text
        - [x] Do you have another subsequent contact to report for this event?
          - [x] Yes/No Option
            - [x] **Branch**
              - [x] yes - add another detail section
              - [x] no - move on to next section
  - Have you in the last seven (7) years, attended or participated in any additional conferences, trade show, seminars, or meetings outside the U.S.? (Do not include those you attended or participated in on official business for the U.S. government).
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another instance" - button adds another foreign business conference detail section
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign conferences](https://cloud.githubusercontent.com/assets/12962390/25616659/1a3a9e34-2f0c-11e7-9713-3e66cae699f6.png)

**Comment by billy22g** [comment]
One issue I see:

It should say "Provide the name of sponsoring organization" (remove "the")

**Comment by billy22g** [comment]
LGTM
