### ISSUE TITLE
Applicant Foreign Business Conferences Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#880]
As an eApp applicant I want to see a summary listing of all foreign business conferences I've attended in the last seven years, so that I can view all foreign business conference entries, reopen and edit specific foreign business conference entries, or remove an entry.

Acceptance Criteria
- Summary of foreign business conferences
  - [x] Shown only if foreign business conferences entered
  - [x] Listing of each foreign business conference the applicant has entered
  - [x] For each foreign business conference entry show the following summary fields: 
    - [x] City: Read-Only label
    - [x] Date: Read-Only label
    - [x] Actions:
      - [x] Edit - Click on item to go to foreign business conferences information entry
      - [x] Delete - Removes the foreign business conferences information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
Same thing with the "add another" button and text. Seems like it needs a broader look with @Jay-Neighbours-I72. We can discuss briefly in standup tomorrow if needed.

<img width="774" alt="screen shot 2017-05-08 at 6 52 37 pm" src="https://cloud.githubusercontent.com/assets/5091167/25831204/9c7f6d1c-341f-11e7-8a83-4565c05db4d6.png">

**Comment by Jay-Neighbours-I72** [comment]
This is my mistake in the wireframes from copying and pasting. @bmallred @billy22g 

Each should be specific to the question being asked, so this example is "Add another event" or "Add another conference, trade show, seminar, or meeting"

**Comment by billy22g** [comment]
LGTM
