### ISSUE TITLE
Applicant Foreign Government Contact

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#881]
As an eApp applicant I want to provide information regarding any contact I, or any member of my immediate family, have had with a foreign government representative in the last seven years so that my investigator can review any contact me, or my family, has made with a foreign government. 

Acceptance Criteria
- Fields
  - For Section 20b, “Immediate Family” means your spouse, parents, step-parents, siblings, half and step-siblings, children, step-children, and cohabitant. Have you or any member of your immediate family in the last seven (7) years had any contact with a foreign government, its establishment (such as embassy, consulate, agency, military service, intelligence or security service, etc.) or its representatives, whether inside or outside the U.S.? (Answer ‘No’ if the contact was for routine visa applications and border crossings related to either official U.S. Government travel, foreign travel on a U.S. passport, or as a U.S. military service member in conjunction with a U.S. Government military duty.)
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the name of the individual involved in the contact
  - Provide the name of the individual involved in the contact.
    - [ ] Name block
  - Provide the location of the contact.
    - [ ] Address block
  - Provide the date of contact.
    - [ ] Date (Estimated)
  - Provide the foreign government(s) involved.
    - [ ] Free Text
  - Provide the type of establishment (such as embassy, consulate, agency, military service, intelligence or security service, etc.) involved.
    - [ ] Free Text
  - Provide the names of the foreign representatives involved in contact.
    - [ ] Free Text
  - Provide the purpose/circumstances of contact.
    - [ ] Free Text
  - Was there any subsequent contact initiated by you, your immediate family member, or a representative of the foreign organization?
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - Add a detail entry section
        - [ ] You responded ‘Yes’ to there having been subsequent contact initiated by you, your immediate family member, or a representative of the foreign organization.
        - Provide the purpose of the subsequent contact.
          - [ ] Free Text
        - Provide the date of most recent contact.
          - [ ] Date (Estimated)
        - Provide plans for future contact.
          - [ ] Free Text
        - Do you have another subsequent contact to report for this event?
          - [ ] Yes/No Option
            - [ ] **Branch**
              - [ ] yes - add another detail section
              - [ ] no - move on to next section
   - Have you or any member of your immediate family in the last seven (7) years had any additional contact with a foreign government, its establishment (such as embassy, consulate, agency, military service, intelligence or security service, etc.) or its representatives, whether inside or outside the U.S.? (Answer ‘No’ if the contact was for routine visa applications and border crossings related to either official U.S. Government travel, foreign travel on a U.S. passport, or as a U.S. military service member in conjunction with a U.S. Government military duty.)
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another foreign government contact detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign government contact](https://cloud.githubusercontent.com/assets/12962390/25616981/d966d1be-2f0d-11e7-8315-e11426b46f03.png)

**Comment by bmallred** [comment]
![foreign-business-contact](https://cloud.githubusercontent.com/assets/697855/26252177/87229334-3c7d-11e7-826b-38ee36fc8e94.gif)

**Comment by billy22g** [comment]
The "provide location" should use a pared down version. It's city/state/zip in the US or city/country outside.

**Comment by bmallred** [comment]
## Preview with place instead of full address
![place](https://cloud.githubusercontent.com/assets/697855/26647012/ddfe325c-460b-11e7-8ce5-5cc135ebb697.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 pointed out this is still missing the zip code (another derivative of address which hasn't been accounted for). Pushing back to **in progress** and closing the bug #1449

**Comment by floresj** [comment]
Just making a note that this is handled in PR #1477.

**Comment by billy22g** [comment]
LGTM!
