### ISSUE TITLE
Applicant Foreign Government Contact Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#882]
As an eApp applicant I want to see a summary listing of all contacts I, and my family, have made to foreign government personnel in the last seven years, so that I can view all foreign contacts we've made, reopen and edit specific foreign contact entries, or remove an entry.

Acceptance Criteria
- Summary of foreign government contact 
  - [ ] Shown only if foreign government contact entered
  - [ ] Listing of each foreign government contact the applicant has entered
  - [ ] For each foreign government contact entry show the following summary fields: 
    - [ ] Name: Read-Only label
    - [ ] Government: Read-Only label
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - Click on item to go to foreign government contact information entry
      - [ ] Delete - Removes the foreign government contact information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
