### ISSUE TITLE
Applicant Foreign National Sponsorship

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#883]
As an eApp applicant I want to provide information regarding any foreign nationals I have sponsored to come to the United States in the last seven years so that my investigator can review who I sponsored and whether I keep in contact with them.

Acceptance Criteria
- Fields
  - Have you in the last seven (7) years sponsored any foreign national to come to the U.S. as a student, for work, or for permanent residence?
  - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the name of the sponsored foreign national
  - Provide the name of the sponsored foreign national.
    - [x] Name block
  - Provide the date of birth for the sponsored foreign national. 
    - [x] I don’t know
    - [x] Date (Estimated)
  - Provide the place of birth for the sponsored foreign national.
    - [x] Address: City State and Zip or country
  - Provide the current street address of the sponsored foreign national.
    - [x] Address block
  - Provide the country(ies) of citizenship for the sponsored foreign national.
    - [x] country multi-select
  - Provide the name of the organization through which sponsorship was arranged, if applicable. 
    - [x] Not Applicable 
    - [x] Free Text
  - Provide the address of the organization through which sponsorship was arranged, if applicable.     - [ ] Not Applicable
    - [x] Address Block
  - Provide the dates of stay in the U.S. for the sponsored foreign national.
    - [x] Date Range (Estimated/Present)
  - Provide the address of the sponsored foreign national while residing in the U.S.
    - [x] Address block
  - Provide the purpose of stay in the U.S. for the sponsored foreign national.
    - [x] Free Text
  - Provide the purpose of your sponsorship for the sponsored foreign national.
    - [x] Free Text
  - Have you in the last seven (7) years sponsored any additional foreign national to come to the U.S. as a student, for work, or for permanent residence?
    - [x] If yes use the button below to add another.
    - [x] **Branch**
      - [x] "Add another instance" - button adds another foreign national sponsorship detail section
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign national sponsor](https://cloud.githubusercontent.com/assets/12962390/25616988/e4e3d500-2f0d-11e7-865b-332b8db23494.png)

**Comment by bmallred** [comment]
![foreign-business-sponsorship](https://cloud.githubusercontent.com/assets/697855/26251651/ff2acc22-3c7b-11e7-96c2-e158c95afab2.gif)

**Comment by lauraponce** [comment]
All the fields look good! One question though, for the address block of "Provide the address of the sponsored foreign national while residing in the U.S." – should we limit their selection to just U.S. addresses? Currently, it's the normal address block.

**Comment by bmallred** [comment]
@lauraponce that is a good question and I definitely follow the logic.

**Comment by bmallred** [comment]
![address-no-buttons](https://user-images.githubusercontent.com/697855/27086497-67628200-5020-11e7-8a71-3c66d29f7137.png)

**Comment by billy22g** [comment]
Copy error should be fixed in #1456. LGTM.
