### ISSUE TITLE
Applicant Foreign National Sponsorship Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#884]
As an eApp applicant I want to see a summary listing of all foreign nationals I have sponsored over the last seven years, so that I can view all foreign nation entries, reopen and edit specific foreign national entries, or remove an entry.

Acceptance Criteria
- Summary of foreign national sponsorship 
  - [ ] Shown only if foreign national sponsorship entered
  - [ ] Listing of each foreign national sponsorship the applicant has entered
  - [ ] For each foreign national sponsorship entry show the following summary fields: 
    - [ ] Name: Read-Only label
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - Click on item to go to foreign national sponsorship information entry
      - [ ] Delete - Removes the foreign national sponsorship information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
