### ISSUE TITLE
Applicant Foreign Political Office

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#885]
As an eApp applicant I want to provide information regarding any political office positions I have ever held in a foreign country so that my investigator can review my political ties to foreign countries.

Acceptance Criteria
- Fields 
  - Have you EVER held political office in a foreign country?
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to:Provide the position held.
  - Provide the position held.
    - [ ] Free Text
  - Provide the dates you held political office.
    - [ ] Date range (Estimated/Present)
  - Provide the name of the country involved.
    - [ ] Country select
  - Provide the reason(s) for these activities.
    - [ ] Free Text
  - Provide your current eligibility to hold political office in a foreign country.
    - [ ] Free Text
  - Have you EVER held any additional political office in a foreign country?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another foreign office detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign held office](https://cloud.githubusercontent.com/assets/12962390/25616995/ee02eca2-2f0d-11e7-91bb-bb66396a9421.png)

**Comment by bmallred** [comment]
![foreign-business-political](https://cloud.githubusercontent.com/assets/697855/26249433/91a6e20a-3c74-11e7-85f7-0f9860fd07a2.gif)

**Comment by lauraponce** [comment]
Looks good!
