### ISSUE TITLE
Applicant Foreign Political Office Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#886]
As an eApp applicant I want to see a summary listing of all financial support I've ever provided for foreign nationals, so that I can view all foreign financial support obligations, reopen and edit specific foreign financial support entries, or remove an entry.

Acceptance Criteria
- Summary of foreign political office 
  - [ ] Shown only if foreign political office  entered
  - [ ] Listing of each foreign political office  the applicant has entered
  - [ ] For each foreign political office  entry show the following summary fields: 
    - [ ] Position: Read-Only label
    - [ ] Country: Read-Only label
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - Click on item to go to foreign political office  information entry
      - [ ] Delete - Removes the foreign political office  information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
