### ISSUE TITLE
Applicant Foreign Election

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#887]
As an eApp applicant I want to provide information regarding any foreign elections that I have voted in so that my investigator can review my eligibility to vote in a foreign country's election.

Acceptance Criteria
- Fields
  - Have you EVER voted in the election of a foreign country?
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date you voted in the foreign election.
  - Provide the date you voted in the foreign election.
    - [ ] Date (Estimated)
  - Provide the name of the country involved.
    - [ ] Country select
  - Provide the reason(s) for these activities.
    - [ ] Free Text
  - Provide your current eligibility to vote in a foreign country.
    - [ ] Free Text
  - Do you have other instances of voting in the election of a foreign country to report?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another foreign election voting detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign voting](https://cloud.githubusercontent.com/assets/12962390/25617000/faf8f226-2f0d-11e7-8443-924ee00acbec.png)

**Comment by bmallred** [comment]
![foreign-business-voting](https://cloud.githubusercontent.com/assets/697855/26249221/a45b15fc-3c73-11e7-94eb-dfbd83408004.gif)

**Comment by lauraponce** [comment]
Looks great!
