### ISSUE TITLE
Applicant Foreign Countries Visited

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#898]
As an eApp applicant I want to provide information regarding all countries I've visited in the last 7 years not on official business so that my investigator can review my travel destinations and reasons for travel.

Acceptance Criteria 
- Fields
  - Have you traveled outside the U.S. in the last past seven (7) years?
    - [ ] Yes/No Option
  - Has your travel in the last seven (7) years been solely for U.S. Government business/military overseas assignment on official government orders (i.e., no personal trips in conjunction with the official U.S. Government business)?
  - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the country visited.
  - Provide the country visited.
    - [ ] Country select
  - Provide the dates of your travel to this country.
    - [ ] Date Range (Estimated)
  - Provide the total number of days involved in the visit. 
    - [ ] Choice: 1-5, 6-10, 11-20, 21-30, More than 30, Many short trips
  - Provide the purpose of the travel to this country (Check all that apply) 
    - [ ] Choice: Business/professional, Volunteer activities, Education, Tourism, "Trade shows, conferences, and seminars", Visit family or friends, Other
  - While traveling to, or in this country, were you questioned, searched, or otherwise detained (other than for normal customs requirements) by the local customs or security service officials when entering or leaving this country? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to or in this country, were you involved in any encounter with the police? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to or in this country, were you contacted by, or in contact with any person known or suspected of being involved or associated with foreign intelligence, terrorist, security, or military organizations? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to, or in this country, were you involved in any counterintelligence or security issues not reported? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to or in this country, were you contacted by, or in contact with anyone exhibiting excessive knowledge of or undue interest in you or your job? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to or in this country, were you contacted by, or in contact with anyone attempting to obtain classified information or unclassified, sensitive information? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - While traveling to, or in this country, were you threatened, coerced, or pressured in any way to cooperate with a foreign government official or foreign intelligence or security service? If yes provide explanation.
    - [ ] Yes/No Option
    - [ ] **Branch** If Yes, show explanation - Free Text 
  - Field Help: Respond for the time frame of the last seven (7) years, beginning with the most recent and working backwards (Do not list trips that ONLY involved travel on official U.S. Government business on official government orders, but you must include any personal trips made in conjunction with the official U.S. Government travel).
  - Do you have additional travel outside the U.S. in the last seven (7) years for other than solely U.S. Government business on official government orders?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another instance" - button adds another foreign country visited detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![foreign countries visited](https://cloud.githubusercontent.com/assets/12962390/25617051/49256a60-2f0e-11e7-8392-350701526da5.png)

**Comment by bmallred** [comment]
![foreign-travel](https://cloud.githubusercontent.com/assets/697855/26248971/6c1eb5f0-3c72-11e7-90e8-bbb50deede50.gif)

**Comment by lauraponce** [comment]
1. Do we want to allow them to enter United States in the country list? It currently allows that option. @billy22g 

2. The second branching question is missing "(i.e., no personal trips in conjunction with the official U.S. Government business)" at the end of the question – should this be pulled out into the help text? @Jay-Neighbours-I72 

3. For providing the dates of travel, I feel like we need to clarify in the help text that it's the _entire_ timeframe which could include multiple trips. 

4. For providing the total number of days in the visit, should it be "visit(s)" since there is an option for multiple trips? I know this strays from the text on the form.

5. I feel like this question can benefit from some help text: "While traveling to, or in this country, were you involved in any counterintelligence or security issues not reported?" – I'm not entirely sure what it means by not reported, so maybe we can clarify that?

6. There is a typo for the very last question on the page: "othe" should be "other"

7. There is a typo for volunteer activities: "activites" should be "activities"

8. One more typo on the summary page for the "Have you or any member of your immediate family in the last seven (7) years had any contact with a foreign government, its establishment or its representatives, whether inside or outside the U.S.?" question - "conjuction" should be "conjunction"

**Comment by bmallred** [comment]
@lauraponce good catch on **number 1**... probably not!

**Comment by bmallred** [comment]
Any suggestions for items **2, 3, 4, and 5**?

cc: @Jay-Neighbours-I72 @billy22g @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
2: I'd say let's have this as P text below the question. Billy expressed concern about hiding this level of informative text in help text.

3. @lauraponce @billy22g  Would the user group multiple trips into one accordion item or break them out into separate items (one item per trip)? My assumption was it would be one item per trip.

4. Same question as 3^. 

5. Agreed, I'm not entirely sure what is being asked either. @billy22g any thoughts?

**Comment by lauraponce** [comment]
For 3 and 4 @Jay-Neighbours-I72 that's a valid point that they could break it up into multiple accordion items, but the form does give them the option to say "many short trips" so it seems like they could do one or the other?

**Comment by Jay-Neighbours-I72** [comment]
@lauraponce that is tricky isn't it. Maybe we write the text to support both then?

**Comment by bmallred** [comment]
## For item 2
![person-trips](https://cloud.githubusercontent.com/assets/697855/26741106/1932b712-47a6-11e7-8d48-659288effdc9.png)

**Comment by billy22g** [comment]
Oof, this *is* tough! I think we should ask them one way and expect it to happen one way, but the "many short trips" really throws it off. This is a @Sheldon1013 question/decision that we should bring up in Sprint Review @Jay-Neighbours-I72 and @lauraponce or another venue to discuss with him.

**Comment by Jay-Neighbours-I72** [comment]
Jay to write help text to explain many short trips:
If gap between trips is more than 6 months enter a separate accordion item.
If gap is less than 6 months enter in a single item.

**Comment by Jay-Neighbours-I72** [comment]
PR made for help text

**Comment by billy22g** [comment]
LGTM
