### ISSUE TITLE
Applicant Foreign Countries Visited Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#899]
As an eApp applicant I want to see a summary listing of all countries I've visited in the last 7 years not on official business, so that I can view all countries I've visited, reopen and edit specific country visit entries, or remove an entry.

Acceptance Criteria
- Summary of foreign countries visited
  - [ ] Shown only if foreign countries visited entered
  - [ ] Listing of each foreign countries visited the applicant has entered
  - [ ] For each foreign foreign countries visited show the following summary fields: 
    - [ ] Country: Read-Only label
    - [ ] Reason: Read-Only label
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - Click on item to go to foreign countries visited information entry
      - [ ] Delete - Removes the foreign countries visited information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
- The acceptance criteria says to add in the reason for travel as well, but I'm not sure if there is enough space in the summary area. Currently it just shows the country and the dates, was it decided to not include the reason there as well? @bmallred @billy22g @Jay-Neighbours-I72 

![screen shot 2017-06-16 at 1 55 12 pm](https://user-images.githubusercontent.com/21222704/27238630-af80666a-529b-11e7-8a6e-1e78679fba49.png)

**Comment by bmallred** [comment]
If there was it was probably on a call and I don't quite remember.

In the past we've had to remove several "long text" entries in the summary due to size or to increase readability.

**Comment by billy22g** [comment]
Yeah, I think the reason is too long to fit, and the dates give the person enough context to be able to distinguish between multiple trips to the same country @lauraponce. LGTM
