### ISSUE TITLE
Applicant Illegal Use of Drugs

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#900]
As an eApp applicant I want to provide information regarding instances where I have illegally used drugs or controlled substances in the last seven years so that my investigator can review my drug use history.

Acceptance Criteria
- [x] Section Help: We note, with reference to this section, that neither your truthful responses nor information derived from your responses to this section will be used as evidence against you in a subsequent criminal proceeding. As to this particular section, this applies whether or not you are currently employed by the Federal government. The following questions pertain to the illegal use of drugs or controlled substances or drug or controlled substance activity in accordance with Federal laws, even though permissible under state laws.
- Fields
  - [x] In the last seven (7) years, have you illegally used any drugs or controlled substances? Use of a drug or controlled substance includes injecting, snorting, inhaling, swallowing, experimenting with or otherwise consuming any drug or controlled substance.
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to Provide the type of drug or controlled substance.
  - You answered ‘Yes’ to in the last seven (7) years having illegally used a drug or controlled substance.
  - Provide the type of drug or controlled substance.
    - [x] Choice: Cocaine or crack cocaine (Such as rock, freebase, etc.); Stimulants (Such as amphetamines, speed, crystal meth, ecstasy, etc.); THC (Such as marijuana, weed, pot, hashish, etc.); Depressants (Such as barbiturates, methaqualone, tranquilizers, etc.); Ketamine (Such as special K, jet, etc.); Narcotics (Such as opium, morphine, codeine, heroin, etc.); Hallucinogenic (Such as LSD, PCP, mushrooms, etc.); Steroids (Such as the clear, juice, etc.); Inhalants (Such as toluene, amyl nitrate, etc.); Other (Provide explanation)
    - [x] Explanation if other (Free Text)
  - Provide an estimate of the month and year of first use.
    - [x] Date M/Y (Estimated)
  - Provide an estimate of the month and year of most recent use.
    - [x] Date M/Y (Estimated)
  - Provide nature of use, frequency, and number of times used.
    - [x] Free Text
  - Was your use while you were employed as a law enforcement officer, prosecutor, or courtroom official, or while in a position directly and immediately affecting the public
    - [x] Yes/No Option
  - Was your use while possessing a security clearance?
    - [x] Yes/No Option
  - Do you intend to use this drug or controlled substance in the future?
    - [x] Yes/No Option
  - Provide explanation of why you intend or do not intend to use this drug or controlled substance in the future.
    - [x] Free Text
  - Do you have an additional instance(s) of illegal use of a drug or controlled substance to enter?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by billy22g** [comment]
@pjsumm Would you mind including a screenshot here please?

**Comment by pjsumm** [comment]
![druguse](https://cloud.githubusercontent.com/assets/12962390/26505807/29928f9e-4218-11e7-8aa4-8865e3c43022.png)

**Comment by lauraponce** [comment]
1. We should remove the estimated checkbox for "Provide an estimate of the month and year of first use" and "Provide an estimate of the month and year of most recent use" since we are asking for an estimate in the question.

2. "Was your use while you were employed as a law enforcement officer, prosecutor, or courtroom official, or while in a position directly and immediately affecting the public" is missing a question mark at the end (I know it's also missing it on the form too, but I'm pretty sure that was a mistake on the form).

3. Should the title of the accordion section default to the type of drug rather than the date of first use?
<img width="608" alt="screen shot 2017-06-06 at 10 13 20 pm" src="https://user-images.githubusercontent.com/21222704/26859404-7fa53eea-4b05-11e7-86cf-763871b0e019.png">

**Comment by billy22g** [comment]
Makes a lot of sense to me on #3.

**Comment by bmallred** [comment]
@lauraponce @Jay-Neighbours-I72 something like this?

![drug-type-summary](https://user-images.githubusercontent.com/697855/27082715-d4de23aa-5013-11e7-8a48-49997c019229.png)

We can also convert the dates to use the standard "1/2010 - 1/2011" format but wasn't sure if that was desired.

**Comment by Jay-Neighbours-I72** [comment]
That looks a bit busy to me, I was thinking the drug type/name only. No dates.

@lauraponce your thoughts?

**Comment by billy22g** [comment]
That was my thinking as well, just the name of the drug.

**Comment by bmallred** [comment]
![no-dates-just-drugs](https://user-images.githubusercontent.com/697855/27131424-a8b2f6b4-50d8-11e7-9d5b-0b247027d33e.png)

**Comment by billy22g** [comment]
LGTM, thanks!
