### ISSUE TITLE
Applicant Illegal Use of Drugs Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#901]
As an eApp applicant I want to see a summary listing of all illegal drug use in the last 7 years that I have entered so that I can view my illegal drug use, reopen and edit specific drug use entries, or remove an entry.

Acceptance Criteria
- Summary of illegal use of drugs 
  - [ ] Shown only if illegal use of drugs have been provided
  - [ ] Listing of each illegal use of drugs entry the applicant has entered
  - [ ] For each illegal use of drugs entry show the following summary fields: 
    - [ ] Dates: Read-Only label
      - [ ] First Use
      - [ ] Last Use
    - [ ] Actions:
      - [ ] Edit - click on item to go to illegal use of drugs entry section
      - [ ] Delete - Removes the illegal use of drugs information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
- [ ] Add the dates for first use and last use as a part of the summary. (Currently, only the label of the drug type is showing and the dates are not present on the collapsed accordion state in the summary.)

**Comment by bmallred** [comment]
@lauraponce the dates were removed due to the conversation on #900. Should we reconsider adding them?

Sorry kind of confusing since the summary is an individual issue apart from the form fields and such.

**Comment by lauraponce** [comment]
Ah, I hadn't caught up on that thread on the other one. That sounds good and makes sense to me!
