### ISSUE TITLE
Applicant Illegal Drug Handling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#902]
As an eApp applicant I want to provide information regarding any instances where I was involved in the illegal purchase, manufacture, cultivation, trafficking, production, transfer, shipping, receiving, handling or sale of any drug or controlled substance in the last seven years so that my investigator can review my involvement in illegal drug handling.

Acceptance Criteria
- Fields
  - [x] In the last seven (7) years, have you been involved in the illegal purchase, manufacture, cultivation, trafficking, production, transfer, shipping, receiving, handling or sale of any drug or controlled substance?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the type of drug or controlled substance.
  - Provide the type of drug or controlled substance.
    - [x] Choice: Cocaine or crack cocaine (Such as rock, freebase, etc.); Stimulants (Such as amphetamines, speed, crystal meth, ecstasy, etc.); THC (Such as marijuana, weed, pot, hashish, etc.); Depressants (Such as barbiturates, methaqualone, tranquilizers, etc.); Ketamine (Such as special K, jet, etc.); Narcotics (Such as opium, morphine, codeine, heroin, etc.); Hallucinogenic (Such as LSD, PCP, mushrooms, etc.); Steroids (Such as the clear, juice, etc.); Inhalants (Such as toluene, amyl nitrate, etc.); Other (Provide explanation)
    - [x] Explanation if other (Free Text)
  - Provide an estimate of the month and year of first use.
    - [x] Date M/Y (Estimated)
  - Provide an estimate of the month and year of most recent use.
    - [x] Date M/Y (Estimated)
  - Provide nature of and frequency of activity.
    - [x] Free Text
  - Provide the reason(s) why you engaged in the activity.
    - [x] Free Text
  - Was your involvement while you were employed as a law enforcement officer, prosecutor, or courtroom official, or while in a position directly and immediately affecting the public safety?
    - [x] Yes/No Option
  - Was your involvement while possessing a security clearance?
    - [x] Yes/No Option
  - Do you intend to engage in this activity in the future?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If Yes to Future Activity
      - [x] You have indicated that you plan to engage in the illegal purchase, manufacture, cultivation, trafficking, production, transfer, shipping, receiving, handling or sale of a drug or controlled substance in the future. Provide explanation.
        - [x] Free Text
  - Do you have an additional instance(s) of having been involved in the illegal purchase, manufacture, cultivation, trafficking, production, transfer, shipping, receiving, handling or sale of a drug or controlled substance to enter?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![drugpurchase](https://cloud.githubusercontent.com/assets/12962390/26505838/4559f582-4218-11e7-8e38-bac2fb77e366.png)

**Comment by lauraponce** [comment]
1. We should remove the estimated checkbox for the two dates: "Provide an estimate of the month and year of first involvement" and "Provide an estimate of the month and year of most recent involvement" 

2. For "Provide the reason(s) why you engaged in the activity." we should remove the period at the end to be consistent with the others

3. "Was your involvement while you were employed as a law enforcement officer, prosecutor, or courtroom official, or while in a position directly and immediately affecting the public" is missing "safety?" at the end of it

**Comment by lauraponce** [comment]
Looks good!
