### ISSUE TITLE
Applicant Illegal Drug Handling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#903]
As an eApp applicant I want to see a summary listing of all illegal drug handling/trafficking in the last 7 years that I have entered so that I can view my illegal handling/trafficking, reopen and edit specific drug handling/trafficking entries, or remove an entry.

Acceptance Criteria
- Summary of illegal drug handling 
  - [ ] Shown only if illegal drug handling entries have been provided
  - [ ] Listing of each illegal drug handling entry the applicant has entered
  - [ ] For each illegal drug handling entry show the following summary fields: 
    - [ ] Dates: Read-Only label
      - [ ] First Use
      - [ ] Last Use
    - [ ] Actions:
      - [ ] Edit - click on item to go to illegal drug handling entry section
      - [ ] Delete - Removes the illegal drug handling information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
- [ ] Add the dates for first use and last use as a part of the summary. (Currently, only the label of the drug type is showing and the dates are not present on the collapsed accordion state in the summary.)

**Comment by bmallred** [comment]
@lauraponce again we followed suit on #900 (although it is a different subsection). This was done because they both were displaying the same information in the same way. Should we handle this section in a different manner?

**Comment by lauraponce** [comment]
Sorry for the confusion! I was just going off of the description here, but that makes more sense based on the #900 thread.

**Comment by bmallred** [comment]
@lauraponce not a problem at all!
