### ISSUE TITLE
Applicant Illegal Drug Involvement with Clearance

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#904]
As an eApp applicant I want to provide information regarding any illegal drug use or involvement while possessing a security clearance so that my investigator can review whether I have been involved with illegal drugs while possessing a security clearance. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER illegally used or otherwise been illegally involved with a drug or controlled substance while possessing a security clearance other than previously listed?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide a description of your involvement.
  - You responded ‘Yes’ to having EVER illegally used or otherwise been involved with a drug or controlled substance while possessing a security clearance, other than previously listed.
  - Provide a description of your involvement.
    - [ ] Free Text
  - Provide the dates of involvement/use.
    - [ ] Date Range (Estimated/Present)
  - Provide an estimate of the number of times you used and/or were involved with this drug or controlled substance while possessing a security clearance.
    - [ ] Free Text
  - Do you have an additional instance(s) of the illegal use or involvement with a drug or controlled substance while possessing a security clearance to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![drugusewithclearance](https://cloud.githubusercontent.com/assets/12962390/26505853/504ea8f2-4218-11e7-9083-ceb8883cd937.png)

**Comment by lauraponce** [comment]
Looks good!
