### ISSUE TITLE
Applicant Illegal Drug Involvement with Clearance Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#905]
As an eApp applicant I want to see a summary listing of all illegal drug involvement while I held a security clearance, reopen and edit specific drug involvement with a security clearance data entries, or remove an entry.

Acceptance Criteria
- Summary of illegal drug involvement with clearance
  - [ ] Shown only if illegal drug involvement with clearance entries have been provided
  - [ ] Listing of each illegal drug involvement with clearance entry the applicant has entered
  - [ ] For each illegal drug involvement with clearance entry show the following summary fields: 
    - [ ] Date Range: Read-Only label
    - [ ] Description: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to illegal drug involvement with clearance entry section
      - [ ] Delete - Removes the illegal drug involvement with clearance information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
