### ISSUE TITLE
Applicant Illegal Drug Involvement as Law Enforcement

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#906]
As an eApp applicant I want to provide information regarding any illegal drug use or involvement while working in law enforcement so that my investigator can review whether I have been involved with illegal drugs while working in law enforcement. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER illegally used or otherwise been involved with a drug or controlled substance while employed as a law enforcement officer, prosecutor, or courtroom official; or while in a position directly and immediately affecting the public safety other than previously listed?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide a description of the drugs...
  - You responded ‘Yes’ to having EVER illegally used, or otherwise been involved with a drug or controlled substance while employed as a law enforcement officer, prosecutor, or courtroom official; or while in a position directly and immediately affecting the public safety other than previously listed.
  - Provide a description of the drugs or controlled substances used and your involvement.
    - [ ] Free Text
  - Provide the dates of involvement/use.
    - [ ] Date Range (Estimated/Present)
  - Provide an estimate the number of times you used and/or were involved this drug or controlled substance while employed in this capacity.
    - [ ] Free Text
  - Do you have an additional instance(s) of illegal use or involvement with a drug or controlled substance while employed as a law enforcement officer, prosecutor, or courtroom official; or while in a position directly and immediately affecting the public safety to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![druguselawenforcement](https://cloud.githubusercontent.com/assets/12962390/26505865/61c403f2-4218-11e7-8b96-e12432eaa16e.png)

**Comment by lauraponce** [comment]
- [ ] The last question on the page should be "Do you have an additional instance(s) of illegal use or involvement with a drug or controlled substance while employed as a law enforcement officer, prosecutor, or courtroom official; or while in a position directly and immediately affecting the public safety to enter?"

Q for @billy22g - this question correctly matches what's in the form, but it sounds like it's missing a few words: 

"Provide an estimate the number of times you used and/or were involved this drug or controlled substance while employed in this capacity" 

Should we just leave as-is since it matches or is it possible to change to something like, 

"Provide an estimate **for** the number of times you used and/or were involved **with** this drug or controlled substance while employed in this capacity"

**Comment by billy22g** [comment]
@lauraponce Great catch. @bmallred Let's change it to:

"Provide an estimate of the number of times you used and/or were involved with this drug or controlled substance while employed in this capacity"

@Jay-Neighbors-I72 would you mind adding this to the tracking doc for Donna?

**Comment by floresj** [comment]
@billy22g @lauraponce I'll change that now.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g In the google doc now

**Comment by lauraponce** [comment]
Looks good!
