### ISSUE TITLE
Applicant Illegal Drug Involvement as Law Enforcement Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#907]
As an eApp applicant I want to see a summary listing of all illegal drug involvement while I worked in law enforcement, reopen and edit specific drug involvement data entries, or remove an entry.

Acceptance Criteria
- Summary of illegal drug involvement as law enforcement
  - [ ] Shown only if illegal drug involvement as law enforcement entries have been provided
  - [ ] Listing of each illegal drug involvement as law enforcement entry the applicant has entered
  - [ ] For each illegal drug involvement as law enforcement entry show the following summary fields: 
    - [ ] Date Range: Read-Only label
    - [ ] Description: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to illegal drug involvement as law enforcement entry section
      - [ ] Delete - Removes the illegal drug involvement as law enforcement information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
