### ISSUE TITLE
Applicant Prescription Drug Misuse

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#908]
As an eApp applicant I want to provide information regarding prescription drug misuse I have had in the last seven years so that my investigator can review when and why I misused prescription drugs.

Acceptance Criteria
- Fields
  - [ ] In the last seven (7) years have you intentionally engaged in the misuse of prescription drugs, regardless of whether or not the drugs were prescribed for you or someone else?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the name of the prescription drug...
  - You responded ‘Yes’ to in the last seven (7) years having intentionally engaged in the misuse of prescription drugs, regardless of whether the drugs were prescribed for you or someone else.
  - Provide the name of the prescription drug that you misused.
    - [ ] Free Text
  - Provide the dates of involvement in the above.
    - [ ] Date Range (Estimated/Present)
  - Provide the reason(s) for and circumstances of the misuse of the prescription drug.
    - [ ] Free Text
  - Was your involvement while you were employed as a law enforcement officer, prosecutor, or courtroom official, or while in a position directly and immediately affecting the public safety?
    - [ ] Yes/No Option
  - Was your involvement while possessing a security clearance?
    - [ ] Yes/No Option
  - Do you have an additional instance(s) of intentionally engaging in the misuse of prescription drugs in the last seven (7) years to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![druguseperscription](https://cloud.githubusercontent.com/assets/12962390/26505874/681ccc16-4218-11e7-8bb9-aba86cf49e18.png)

**Comment by lauraponce** [comment]
Looks good!
