### ISSUE TITLE
Applicant Prescription Drug Misuse Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#909]
As an eApp applicant I want to see a summary listing of all prescription drug misuse in the last seven years, reopen and edit specific prescription drug misuse data entries, or remove an entry.

Acceptance Criteria
- Summary of prescription drug misuse
  - [ ] Shown only if prescription drug misuse entries have been provided
  - [ ] Listing of each prescription drug misuse entry the applicant has entered
  - [ ] For each prescription drug misuse entry show the following summary fields: 
    - [ ] Name of Drug: Read-Only label
    - [ ] Date Range: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to prescription drug misuse entry section
      - [ ] Delete - Removes the prescription drug misuse information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
