### ISSUE TITLE
Applicant Drug Use Ordered Counselling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#910]
As an eApp applicant I want to provide information regarding instances where I was advised or ordered to seek counselling for my drug use so that my investigator can review the circumstances under which I was advised/ordered to seek counselling. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER been ordered, advised, or asked to seek counseling or treatment as a result of your illegal use of drugs or controlled substances?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Have any of the following ordered, advised, or asked...
  - You responded ‘Yes’ to having EVER been ordered, advised, or asked to seek counseling or treatment as a result of your illegal use of drugs or controlled substances
  - Have any of the following ordered, advised, or asked you to seek counseling or treatment as a result of your illegal use of drugs or controlled substances? (Check all that apply)
    - [ ] Choice: An employer, military commander, or employee assistance program; A medical professional; A mental health professional; A court official / judge; I have not been ordered, advised, or asked to seek counseling or treatment by any of the above.
    - [ ] Provide explanation - Free Text
  - Did you take action to receive counseling or treatment?
   - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
        - You have indicated that you did not receive treatment. Provide explanation.
          - [ ] Free Text
      - [ ] Yes - If Yes to Action Taken
        - Provide the type of drug or controlled substance for which you were treated.
          - [ ] Choice: Cocaine or crack cocaine (Such as rock, freebase, etc.); Stimulants (Such as amphetamines, speed, crystal meth, ecstasy, etc.); THC (Such as marijuana, weed, pot, hashish, etc.); Depressants (Such as barbiturates, methaqualone, tranquilizers, etc.); Ketamine (Such as special K, jet, etc.); Narcotics (Such as opium, morphine, codeine, heroin, etc.); Hallucinogenic (Such as LSD, PCP, mushrooms, etc.); Steroids (Such as the clear, juice, etc.); Inhalants (Such as toluene, amyl nitrate, etc.); Other (Provide explanation)
          - [ ] Free Text
        - Provide the name of the treatment provider. (Last name, First name)
          - [ ] Free Text
        - Provide the address for this treatment provider.
          - [ ] Address Block
        - Provide a telephone number for the treatment provider.
          - [ ] Telephone Block
        - Provide the dates of treatment.
          - [ ] Date Range (Estimated/Present)
        - Did you successfully complete the treatment?
          - [ ] Yes/No Option
          - [ ] **Branch** If No to Successful Treatment
            - You have indicated that you did not successfully complete the treatment. Provide explanation.
              - [ ] Free Text
  - Do you have another instance of having been ordered, advised, or asked to seek drug or controlled substance counseling or treatment to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![druguseorderedcounselling](https://cloud.githubusercontent.com/assets/12962390/26505883/74524db2-4218-11e7-9530-a0e0e8b07b8d.png)

**Comment by lauraponce** [comment]
Everything looks good as far as the content goes, but one thought about the boxes for the first question: should the last option for "no" be mutually exclusive with the other boxes? So if they click that "no" one, but have others checked, it would uncheck the others and if they check others after having the "no" one checked, it would uncheck the "no" one. Thoughts @Jay-Neighbours-I72 @billy22g ?

![screen shot 2017-06-15 at 4 35 16 pm](https://user-images.githubusercontent.com/21222704/27200658-a63cf810-51e8-11e7-9067-689e38337ed4.png)

**Comment by billy22g** [comment]
What you're recommending makes a ton of sense to me @lauraponce. To be clear, when you're saying "No," you mean the box with "I have not been ordered, advised, or asked to seek counseling or treatment by any of the above," right?

**Comment by Jay-Neighbours-I72** [comment]
Ah good point @lauraponce I agree.

**Comment by lauraponce** [comment]
@billy22g Correct - I was saving time by not typing it all out, but I realize that could have been unclear :) "I have not been ordered, advised, or asked to seek counseling or treatment by any of the above" is what I meant by "No"

**Comment by bmallred** [comment]
Can do! We'll move this back to **in progress**

**Comment by billy22g** [comment]
LGTM, same issues as #915 though with the inconsistent responses. Less so on this one because there's no "Other" button.
