### ISSUE TITLE
Applicant Drug Use Ordered Counselling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#911]
As an eApp applicant I want to see a summary listing of all instances where I was advised/ordered to seek counselling for drug use, reopen and edit specific instances of counselling entries, or remove an entry.

Acceptance Criteria
- Summary of drug use ordered counselling
  - [ ] Shown only if drug use ordered counselling entries have been provided
  - [ ] Listing of each drug use ordered counselling entry the applicant has entered
  - [ ] For each drug use ordered counselling entry show the following summary fields: 
    - [ ] Who Ordered Counselling: Read-Only label 
    - [ ] Date Range: Read-Only label  (if available)
    - [ ] Actions:
      - [ ] Edit - click on item to go to drug use ordered counselling entry section
      - [ ] Delete - Removes the drug use ordered counselling information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
