### ISSUE TITLE
Applicant Drug Use Voluntary Counselling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#912]
As an eApp applicant I want to provide information regarding instances where I voluntarily sought counselling for my drug use so that my investigator can review the circumstances under which I voluntarily sought counselling for drug use. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER voluntarily sought counseling or treatment as a result of your use of a drug or controlled substance?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the type of drug or controlled substance...
If Yes to Voluntarily Seeking Treatment for the Misuse of Drugs
  - Voluntary treatment detail
  - Provide the type of drug or controlled substance for which you were treated.
    - [ ] Choice: Cocaine or crack cocaine (Such as rock, freebase, etc.); Stimulants (Such as amphetamines, speed, crystal meth, ecstasy, etc.); THC (Such as marijuana, weed, pot, hashish, etc.); Depressants (Such as barbiturates, methaqualone, tranquilizers, etc.); Ketamine (Such as special K, jet, etc.); Narcotics (Such as opium, morphine, codeine, heroin, etc.); Hallucinogenic (Such as LSD, PCP, mushrooms, etc.); Steroids (Such as the clear, juice, etc.); Inhalants (Such as toluene, amyl nitrate, etc.); Other (Provide explanation)
    - [ ] Free Text
  - Provide the name of the treatment provider. (Last name, First name)
    - [ ] Free Text
  - Provide the address for this treatment provider.
    - [ ] Address block
  - Provide a telephone number for the treatment provider.
    - [ ] Telephone number block
  - Provide the dates of treatment.
    - [ ] Date Range (Estimated/Present)
  - Did you successfully complete the treatment?
    - [ ] Yes/No Option
    - [ ] **Branch** If No to Successful Treatment
      - You have indicated that you did not you successfully complete the treatment. Provide explanation.
      - [ ] Free Text
  - Do you have another instance of EVER voluntarily seeking counseling or treatment as a result of your use of a drug or controlled substance?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![drugusevoluntarycounselling](https://cloud.githubusercontent.com/assets/12962390/26505901/7f0cac48-4218-11e7-89fe-01bde5e089eb.png)

**Comment by lauraponce** [comment]
Should we have validation that two names (first AND last) were entered here? Right now it allows just one name to be entered. @billy22g @Jay-Neighbours-I72 

![screen shot 2017-06-15 at 4 39 54 pm](https://user-images.githubusercontent.com/21222704/27200841-62369e4a-51e9-11e7-81cc-65fe6b18829c.png)

**Comment by billy22g** [comment]
Some people only have one name, so I think it's almost impossible to validate that imo.

**Comment by bmallred** [comment]
The help icon appears to be off on this one as well!
