### ISSUE TITLE
Applicant Drug Use Voluntary Counselling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#913]
As an eApp applicant I want to see a summary listing of all instances where I voluntarily  sought counselling for drug use, reopen and edit specific instances of counselling entries, or remove an entry.

Acceptance Criteria
- Summary of drug use voluntary counselling
  - [ ] Shown only if drug use voluntary counselling entries have been provided
  - [ ] Listing of each drug use voluntary counselling entry the applicant has entered
  - [ ] For each drug use voluntary counselling entry show the following summary fields: 
    - [ ] Provider: Read-Only label 
    - [ ] Date Range: Read-Only label  (if available)
    - [ ] Actions:
      - [ ] Edit - click on item to go to drug use voluntary counselling entry section
      - [ ] Delete - Removes the drug use voluntary counselling information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
