### ISSUE TITLE
Applicant Alcohol Use Negative Impact

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#914]
As an eApp applicant I want to provide information regarding instances where where alcohol had a negative impact on my professional or personal life, or required law enforcement intervention so that my investigator can review the circumstances under which my alcohol use negatively impacted my life, or caused a public safety concern. 

Acceptance Criteria
- Fields 
  - [ ] In the last seven (7) years has your use of alcohol had a negative impact on your work performance, your professional or personal relationships, your finances, or resulted in intervention by law enforcement/public safety personnel?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the month/year when this negative impact occurred.
  - You responded ‘Yes’ to your alcohol use having had a negative impact on your work performance, your professional or personal relationships, your finances, or resulted in intervention by law enforcement/public safety personnel.
  - Provide the month/year when this negative impact occurred.
    - [ ] Date (Estimated)
  - Provide an explanation of the circumstances and the negative impact.    
    - [ ] Free Text
    - [ ] Free Text
  - Provide dates of involvement or use.
    - [ ] Date Range (Estimated/Present)
  - Has the use of alcohol had other negative impacts on your work performance, your professional or personal relationships, your finances, or resulted in intervention by law enforcement/public safety personnel?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another impact"- button adds another detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![alcoholuse](https://cloud.githubusercontent.com/assets/12962390/25882737/a94f3eb0-3513-11e7-8923-9bf0f659aaac.png)

**Comment by lauraponce** [comment]
1. Should we decrease the font size for the main question? @Jay-Neighbours-I72 

![screen shot 2017-06-09 at 3 52 26 pm](https://user-images.githubusercontent.com/21222704/26992253-c7c1eee4-4d2b-11e7-95f9-03eb08f5c9fe.png)

2. Should we break this into two questions to make it more clear? E.g. 1. Provide an explanation of the circumstances and 2. Provide the negative impact @Jay-Neighbours-I72 @billy22g 

![screen shot 2017-06-09 at 3 52 32 pm](https://user-images.githubusercontent.com/21222704/26992288-f7daad64-4d2b-11e7-96b3-5fd760996cb9.png)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @lauraponce Looks like we go between `H2` and `H3` for the subsection headers. For instance, Financial Record and Military history use `H2` while some items in Investigative and Criminal History use `H3`. We should probably normalize these headers unless there's a reason to use both.

**Comment by Jay-Neighbours-I72** [comment]
@floresj the reason to use both was visual space. 

The really long header we changed to H3 so they didn't take up so much space and were easier to read.

Does this mess up our accessibility?

**Comment by bmallred** [comment]
I thought we did `h3`'s for sub-subsections and `h2`'s for subsections due to the review section and it's layout?

**Comment by Jay-Neighbours-I72** [comment]
Yeah that structure is ideal.

The issue we run into is the really long questions and the goal with those is to use a smaller typeface.

Is there a better way to solve this without changing to an H3?

**Comment by billy22g** [comment]
@lauraponce Leaving this for you as you have a better sense of what's considered done here I think with respect to page structure and potentially breaking up the two fields.

I don't think we can break it into two questions, but we could change the verbiage (e.g. "Provide circumstances" and "Provide negative impact" or add a bit more space between.

**Comment by lauraponce** [comment]
@billy22g That sounds like a good option. @Jay-Neighbours-I72 thoughts on adding some padding between the two text boxes and leaving the question as-is but changing the description to "Provide circumstances" for the first box and "Provide negative impact" for the second box?

**Comment by billy22g** [comment]
Bump for @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
@lauraponce Yeah I like that idea, would read nicer. That make sense @bmallred @floresj ? I can walk through via hangout if that is easier.

For the larger headline size question Bryan and I talked through that last week and will be using a smaller size for the really long headlines.

**Comment by colinpmacarthur** [comment]
I think all these issues have been addressed and this section looks good to me! 👍
