### ISSUE TITLE
Applicant Alcohol Use Ordered Counseling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#915]
As an eApp applicant I want to provide information regarding instances where I was advised or ordered to seek counselling for my alcohol use so that my investigator can review the circumstances under which I was advised/ordered to seek alcohol use counselling. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER been ordered, advised, or asked to seek counseling or treatment as a result of your use of alcohol?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Have any of the following ordered, advised, or asked you to seek counseling or treatment as a result of your use of alcohol? (Check all that apply)
  - You responded ‘Yes” to having been ordered, advised or asked to seek counseling or treatment as a result of your use of alcohol.
  - Have any of the following ordered, advised, or asked you to seek counseling or treatment as a result of your use of alcohol? (Check all that apply)
    - [ ] Choice: An employer, military commander, or employee assistance program; A medical professional; A mental health professional; A court official / judge; I have not been ordered, advised, or asked to seek counseling or treatment by any of the above. ; Other (Provide Explanation)
    - [ ] Other Explanation: Free Text
  - Did you take action to seek counseling or treatment?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If "No" Action Taken
        - You responded ‘No’ to having taken action to seek counseling or treatment.         - Explain the reasons for not taking action to seek counseling or treatment.
          - [ ] Free Text
      - [ ] If "Yes" Action Taken
        - You responded ‘Yes’ to having taken action to seek counseling or treatment.
        - Provide the dates of counseling or treatment.
          - [ ] Date Range (Estimated/Present)
        - Provide the name of the individual counselor or treatment provider.
          - [ ] Free Text
        - Provide the full address of the counseling/treatment provider.
          - [ ] Address block
        - Provide telephone number.
          - [ ] Telephone block
        - Did you successfully complete the treatment program?
          - [ ] Yes/No Option
          - [ ] **Branch**
            - [ ] If "No" to Successful Completion
              - You responded “No” to having successfully completed the treatment program. Provide explanation 
                - [ ] Free Text
  - Do you have additional instances of having been ordered, advised or asked to seek counseling or treatment as a result of your use of alcohol to enter?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another treatment" - button adds another detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![alcoholuseorderedtreatment](https://cloud.githubusercontent.com/assets/12962390/25882772/d0ff5260-3513-11e7-8440-94a4edbc6d1f.png)

**Comment by lauraponce** [comment]
- Similar to #910 - should these options be mutually exclusive as well? This one has an "Other" option which is the only difference in #910 @billy22g 

![screen shot 2017-06-16 at 1 44 36 pm](https://user-images.githubusercontent.com/21222704/27238194-f67f44de-5299-11e7-9138-c942d434cb7f.png)

**Comment by billy22g** [comment]
@lauraponce I think you're saying that "I have not been ordered, advised, or asked to seek counseling or treatment by any of the above" should be mutually exclusive with the other options, to include "Other". If so, I agree. cc: @bmallred

**Comment by billy22g** [comment]
Wait, what? This seems like it might be a mistake on the form.

<img width="692" alt="screen shot 2017-06-21 at 6 41 09 am" src="https://user-images.githubusercontent.com/5091167/27384609-bed52ccc-564c-11e7-9fad-5ae30150018f.png">

**Comment by billy22g** [comment]
To clarify the above, it's inconsistent to say "Yes" to the first question and then select "I have not been ordered, advised, or asked to seek counseling or treatment by any of the above" to the follow up, which is essentially the same question. The presence of the "Other" button renders the aforementioned button useless, because you already said you have been. @Jay-Neighbours-I72 @lauraponce @DBrenenborg @Sheldon1013

**Comment by billy22g** [comment]
Gonna close this, but added the "needs answer" label to clarify the form itself. LGTM.
