### ISSUE TITLE
Applicant Alcohol Use Ordered Counseling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#916]
As an eApp applicant I want to see a summary listing of all instances where I was advised/ordered to seek counselling for alcohol use, reopen and edit specific instances of alcohol counseling entries, or remove an entry.

Acceptance Criteria
- Summary of alcohol use counseling 
  - [ ] Shown only if alcohol counseling instances have been provided
  - [ ] Listing of each alcohol counseling instance entry the applicant has entered
  - [ ] For each alcohol use counseling instance entry show the following summary fields: 
    - [ ] Requested by: Read-Only label
    - [ ] Treatment date: Read-Only label (only if treatment taken)
    - [ ] Actions:
      - [ ] Edit - click on item to go to alcohol use counseling entry section
      - [ ] Delete - Removes the alcohol use counseling information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
- [ ] The titles of the types of counseling need spacing between the words for formatting

![screen shot 2017-06-16 at 1 41 34 pm](https://user-images.githubusercontent.com/21222704/27238110-a8664090-5299-11e7-980e-57743a381911.png)
