### ISSUE TITLE
Applicant Alcohol Use Voluntary Counseling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#917]
As an eApp applicant I want to provide information regarding instances where I voluntarily sought counselling for my alcohol use so that my investigator can review the circumstances under which I voluntarily sought counselling for alcohol use.

Acceptance Criteria
- Fields
  - Have you EVER voluntarily sought counseling or treatment as a result of your use of alcohol?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the dates of counseling or treatment
  - You responded ‘Yes’ to voluntarily seeking counseling or treatment.
  - Provide the dates of counseling or treatment.
    - [ ] Date Range (Estimated/Present)
  - Provide the name of the individual counselor or treatment provider.
    - [ ] Free Text
  - Provide the full address of the counseling/treatment provider.
    - [ ] Address block
  - Provide telephone number.
    - [ ] Telephone block 
  - Did you successfully complete the treatment program?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If Unsucessful
        - You answered ‘No’ to having successfully completed the treatment program. Provide explanation:
          - [ ] Free Text
  - Do you have additional instances where you have voluntarily sought counseling or treatment as a result of your use of alcohol to enter?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another treatment" - button adds another detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![alcoholusevoluntarytreatment](https://cloud.githubusercontent.com/assets/12962390/25882832/07efebcc-3514-11e7-9d89-5227188cb9db.png)

**Comment by lauraponce** [comment]
Looks good!
