### ISSUE TITLE
Applicant Alcohol Use Other Counseling

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#919]
As an eApp applicant I want to provide information regarding other instances where I sought counselling or treatment for my alcohol use so that my investigator can review the circumstances of the other instances where I sought counselling/treatment for alcohol use.

- Fields
  - Have you EVER received counseling or treatment as a result of your use of alcohol in addition to what you have already listed on this form?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the name of individual counselor or treatment provider.
  - You responded ‘Yes’ to having EVER received counseling or treatment as a result of your use of alcohol.
  - Provide the name of individual counselor or treatment provider.
    - [ ] Free Text
  - Provide the full address of counseling/treatment provider.
    - [ ] Address Block
  - Provide the name of agency/organization where counseling/treatment was provided.
    - [ ] Free Text
  - Provide the address of agency/organization where counseling/treatment was provided: 
    - [ ] Same as above - Check
    - [ ] Address block - required if not "same as above"
  - Provide the date counseling or treatment began.
    - [ ] Date (Estimated)
  - Provide the date counseling or treatment ended
    - [ ] Date (Estimated/Present)
  - Did you successfully complete your counseling or treatment?
    - [ ] Yes/No Option
    - [ ] Explanation (for Yes or No) - Free Text
  - Did you receive alcohol-related counseling or treatment another time?
    - [ ] If yes use the button below to add another.
    - [ ] **Branch**
      - [ ] "Add another treatment" - button adds another detail section
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![alcoholusecounseling](https://cloud.githubusercontent.com/assets/12962390/25882865/340942ee-3514-11e7-8e71-dd434a8bd1f9.png)

**Comment by lauraponce** [comment]
- [ ] The date fields for "Provide the date counseling or treatment ended" aren't allowing input - I can click inside them, but it won't allow anything to be inputted. In addition, the present button isn't working. (Note, the date fields above are working fine.)

![screen shot 2017-06-16 at 1 07 16 pm](https://user-images.githubusercontent.com/21222704/27237002-565b96c8-5295-11e7-83cf-2d22505efe51.png)

**Comment by billy22g** [comment]
The end date shouldn't be able to be before the beginning date.

<img width="534" alt="screen shot 2017-06-21 at 6 56 23 am" src="https://user-images.githubusercontent.com/5091167/27385127-ca120d56-564e-11e7-8a9f-234536fb330f.png">

**Comment by bmallred** [comment]
## Preview

![screen shot 2017-06-23 at 10 42 38 am](https://user-images.githubusercontent.com/697855/27487103-c1ff5fb6-5800-11e7-80ba-8b3d0f722119.png)

**Comment by billy22g** [comment]
LGTM, posted a message in Slack about dates of personal things being before birth dates, but I think we'll likely handle that validation separately and holistically.
