### ISSUE TITLE
Applicant Alcohol Use Other Counseling Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#920]
As an eApp applicant I want to see a summary listing of all instances of other times that I sought counselling\treatment for alcohol use, reopen and edit specific instances of counselling entries, or remove an entry.

Acceptance Criteria
- Summary of alcohol use counseling 
  - [ ] Shown only if alcohol counseling instances have been provided
  - [ ] Listing of each alcohol counseling instance entry the applicant has entered
  - [ ] For each alcohol use counseling instance entry show the following summary fields: 
    - [ ] Counselor name: Read-Only label
    - [ ] Treatment dates: Read-Only label (only if treatment taken)
    - [ ] Actions:
      - [ ] Edit - click on item to go to alcohol use counseling entry section
      - [ ] Delete - Removes the alcohol use counseling information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
