### ISSUE TITLE
Applicant Investigation History

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#924]
As an eApp applicant I want to provide information regarding previous investigations into my background for security clearance so that my investigator can the results of previous background investigations.

Acceptance Criteria
- Fields
  - [x] Has the U.S. Government (or a foreign government) EVER investigated your background and/or granted you a security clearance eligibility/access?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the investigating agency:
  - You responded ‘Yes’ to the U.S. Government (or a foreign government) having investigated your background and/or having granted you a security clearance eligibility/access.
  - Provide the investigating agency:
    - [x] Choice: U.S. Department of Defense; U.S. Department of State; U.S. Office of Personnel Management; Federal Bureau of Investigation; U.S. Department of Treasury (Provide name of bureau); U.S. Department of Homeland Security; Foreign government, (Provide name of government); I don’t know; Other (Provide explanation)
    - [x] Free Text
  - Date the investigation was completed. 
    - [x] Check: I don’t know
    - [x] Date (Estimated)
  - Provide the name of agency that issued the clearance eligibility/access if different from the investigating agency.
    - [x] Free Text
  - Provide the date clearance eligibility/access was granted.
    - [x] Check: I don’t know
    - [x] Date (Estimated)
  - Provide the level of clearance eligibility/access granted.
    - [x] Choice: None; Confidential; Secret; Top Secret; Sensitive Compartmented Information (SCI); Q; L; I don’t know; Issued by foreign country; Other (Provide explanation)
    - [x] Free Text
  - Do you have another investigation to enter?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![clearanceinvestigationhistory](https://cloud.githubusercontent.com/assets/12962390/26505927/96daf05a-4218-11e7-816e-6ae453f3baa1.png)

**Comment by bmallred** [comment]
## Preview
![investigations-history](https://cloud.githubusercontent.com/assets/697855/26697651/c18809c4-46e0-11e7-9d05-b069f1c6ce1b.gif)

**Comment by lauraponce** [comment]
All of these relate to removing the 'Not applicable' option which I don't see anything about adding it in (correct me if I'm wrong though!):

- [ ] Add an "I don't know" option for the first question of the investigating agency and remove the 'Not applicable' button under the free text

- [ ] For the date the investigation was completed, the 'Not applicable' button should be an "I don't know" option instead

- [ ] For providing the date clearance/eligibility/access was granted, the 'Not applicable' button should be an "I don't know" option instead

- [ ] For the last question on the section about level of clearance, the 'Not applicable' button should not be there

**Comment by bmallred** [comment]
@lauraponce those just happen to be the same component that we use... "Not applicable" is the default text. I'll update it to say "I don't know" though!

The IDK on the last question was talked through with @Jay-Neighbours-I72 and we decided to reuse the `NotApplicable` component so it is similar to the rest of the section. We can change this if need be though.

**Comment by bmallred** [comment]
Does this look right?

---
![idk-agency](https://user-images.githubusercontent.com/697855/27083169-99ea30b6-5015-11e7-944b-9e2f0405e517.png)

---
![idk-completed](https://user-images.githubusercontent.com/697855/27083171-9d6322a2-5015-11e7-98fd-7aea680734f5.png)

---
![idk-eligibility](https://user-images.githubusercontent.com/697855/27083173-a1b64c6c-5015-11e7-9bf1-a2e586e04e74.png)

---
![idk-clearance](https://user-images.githubusercontent.com/697855/27083197-a77b6a1a-5015-11e7-9634-d9987ef3c698.png)


cc: @lauraponce @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Those look good to me!

**Comment by billy22g** [comment]
LGTM
