### ISSUE TITLE
Applicant Investigation History Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#925]
As an eApp applicant I want to see a summary listing of all previous background investigations, reopen and edit specific investigation entries, or remove an entry.

Acceptance Criteria
- Summary of investigations
  - [ ] Shown only if investigation entries have been provided
  - [ ] Listing of each investigation entry the applicant has entered
  - [ ] For each investigation entry show the following summary fields: 
    - [ ] Agency: Read-Only label 
    - [ ] Level: Read-Only label
    - [ ] Date Granted: Read-Only label  (if available)
    - [ ] Actions:
      - [ ] Edit - click on item to go to investigation entry section
      - [ ] Delete - Removes the investigation information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good! Just noting for tracking purposes that the acceptance criteria says to include level, but there doesn't appear to be enough room for that so the summary with the agency name and date granted as it is now seems like the best fit.

![screen shot 2017-06-16 at 3 01 36 pm](https://user-images.githubusercontent.com/21222704/27240963-b6278756-52a4-11e7-8f28-a94a156f60d3.png)
