### ISSUE TITLE
Applicant Security Clearance Revocation

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#926]
As an eApp applicant I want to provide information regarding any instances where I have had my security clearance eligibility/access authorization denied, suspended, or revoked so that my investigator can review the circumstances surrounding the revocation of my clearance.

Acceptance Criteria
- Fields
  - [ ] Have you EVER had a security clearance eligibility/access authorization denied, suspended, or revoked? (Note: An administrative downgrade or administrative termination of a security clearance is not a revocation.)
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date security clearance...
  - You responded ‘Yes’ to having EVER had a security clearance eligibility/access authorization denied, suspended, or revoked.
  - Provide the date security clearance eligibility/access authorization was denied, suspended or revoked.
    - [ ] Date (Estimated)
  - Provide the name of the agency that took the action.
    - [ ] Free Text
  - Provide an explanation of the circumstances of the denial, suspension or revocation action.
    - [ ] Free Text
  - Do you have another denied, revoked or suspended security clearance eligibility/access authorization to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![clearancedenied](https://cloud.githubusercontent.com/assets/12962390/26505937/a44f4ede-4218-11e7-8e3a-819fd3d14eda.png)

**Comment by bmallred** [comment]
## Preview
![investigations-revoked](https://cloud.githubusercontent.com/assets/697855/26697720/0d70df82-46e1-11e7-92d0-aed9b1f28d44.gif)

**Comment by lauraponce** [comment]
Looks good!
