### ISSUE TITLE
Applicant Security Clearance Revocation Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#927]
As an eApp applicant I want to see a summary listing of all instances where my security clearance has been revoked, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of security clearance revocations
  - [ ] Shown only if security clearance revocation entries have been provided
  - [ ] Listing of each security clearance revocations entry the applicant has entered
  - [ ] For each security clearance revocations entry show the following summary fields: 
    - [ ] Agency: Read-Only label 
    - [ ] Date Revoked: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to investigation entry section
      - [ ] Delete - Removes the investigation information entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
