### ISSUE TITLE
Applicant Debarred From Government Employment

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#928]
As an eApp applicant I want to provide information regarding any time I was debarred from government employment so that my investigator can review the circumstances of when I was debarred from government employment. 

Acceptance Criteria
- Fields
  - [ ] Have you EVER been debarred from government employment?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the name of the government...
  - You responded ‘Yes’ to having EVER been debarred from government employment.
  - Provide the name of the government agency taking debarment action.
    - [ ] Free Text
  - Provide the date the debarment occurred.
    - [ ] Date (Estimated)
  - Provide an explanation of the circumstances of the debarment.
    - [ ] Free text
  - Do you have another Government debarment to enter?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![clearancedebarred](https://cloud.githubusercontent.com/assets/12962390/26505949/ae080088-4218-11e7-9394-25f6da40bcb8.png)

**Comment by bmallred** [comment]
## Preview
![investigations-debarred](https://cloud.githubusercontent.com/assets/697855/26697775/40760d30-46e1-11e7-9f21-2350095a2a9f.gif)

**Comment by lauraponce** [comment]
Looks great!
