### ISSUE TITLE
Applicant Debarred From Government Employment Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#929]
As an eApp applicant I want to see a summary listing of all instances where I have been debarred from government employment so that I can, reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of debarment from government employment
  - [ ] Shown only if debarment from government employment entries have been provided
  - [ ] Listing of each debarment from government employment entry the applicant has entered
  - [ ] For each debarment from government employment entry show the following summary fields: 
    - [ ] Agency: Read-Only label 
    - [ ] Date: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to debarment from government employment entry section
      - [ ] Delete - Removes the debarment from government employment information entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
