### ISSUE TITLE
Applicant IT Systems Unauthorized Access

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#930]
As an eApp applicant I want to provide information regarding any instance where I have illegally or without proper authorization accessed or attempted to access any information technology system in the past seven years so that my investigator can review the incident details.

Acceptance Criteria
- [ ] Section Help: We note, with reference to this section, that neither your truthful responses nor information derived from your responses to this section will be used as evidence against you in a subsequent criminal proceeding. As to this particular section, this applies whether or not you are currently employed by the Federal government. The following questions ask about your use of information technology systems. Information technology systems include all related computer hardware, software, firmware, and data used for the communication, transmission, processing, manipulation, storage or protection of information.
- Fields
  - [ ] **In the last seven (7) years** have you illegally or without proper authorization accessed or attempted to access any information technology system?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date of the incident
  - You responded ‘Yes’ to having **in the last seven (7) years** illegally or without proper authorization entered or attempted to enter into any information technology system.
  - Provide the date of the incident.
    - [ ] Date (Estimated)
  - Provide a description of the nature of the incident or offense.
    - [ ] Free Text
  - Provide the location where the incident took place.
    - [ ] Address Block (with country)
  - Provide a description of the action (administrative, criminal or other) taken as a result of this incident.
    - [ ] Free Text
  - Are there any other incidents to report?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![infotechillegalaccess](https://user-images.githubusercontent.com/12962390/26860432-e8a7e176-4b0b-11e7-9837-d53c6fe8a278.png)

**Comment by bmallred** [comment]
## Preview
![legal-tech-unauthorized](https://user-images.githubusercontent.com/697855/26941932-461cc090-4c4e-11e7-9378-c39da8ef5ed0.gif)

**Comment by lauraponce** [comment]
Looks good!
