### ISSUE TITLE
Applicant IT Systems Manipulating Access

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#932]
As an eApp applicant I want to provide information regarding any instance where I have illegally or without authorization, modified, destroyed, manipulated, or denied others access to information residing on an information technology system in the last seven years so that my investigator can review the incident details.

Acceptance Criteria
- Fields
  - [ ] **In the last seven (7) years** have you illegally or without authorization, modified, destroyed, manipulated, or denied others access to information residing on an information technology system or attempted any of the above?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date of the incident
  - You responded ‘Yes’ to having **in the last seven (7) years** illegally or without authorization, modified, destroyed, manipulated, or denied others access to information residing on an information technology system or attempted any of the above.
  - Provide the date of the incident.
    - [ ] Date (Estimated)
  - Provide a description of the nature of the incident or offense.
    - [ ] Free Text
  - Provide the location where the incident took place.
    - [ ] Address block (with country)
  - Provide a description of the action (administrative, criminal or other) taken as a result of this incident.
    - [ ] Free Text
  - Are there any other incidents to report?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![infotechmanipulateaccess](https://user-images.githubusercontent.com/12962390/26860463-0c7e324e-4b0c-11e7-8832-2affcd5ab7e4.png)

**Comment by bmallred** [comment]
## Preview 
![legal-tech-manipulating](https://user-images.githubusercontent.com/697855/26942056-af9a3b06-4c4e-11e7-8511-fbdd633f558a.gif)

**Comment by lauraponce** [comment]
Looks good!
