### ISSUE TITLE
Applicant IT Systems Manipulating Access Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#933]
As an eApp applicant I want to see a summary listing of all instances where I have attempted to unlawfully manipulate access or data in an information technology system so that I can reopen and edit specific unlawfully access/data manipulation entries, or remove an entry.

Acceptance Criteria
- Summary of unlawful IT systems access/data manipulation
  - [ ] Shown only if unlawful IT systems access/data manipulation have been provided
  - [ ] Listing of each unlawful IT systems access/data manipulation entry the applicant has entered
  - [ ] For each unlawful IT systems access/data manipulation entry show the following summary fields: 
    - [ ] Date: Read-Only label
    - [ ] Description: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to unlawful IT systems access/data manipulation entry section
      - [ ] Delete - Removes the unlawful IT systems access/data manipulation data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
