### ISSUE TITLE
Applicant IT Systems Unlawful Use

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#934]
As an eApp applicant I want to provide information regarding any instance where I introduced, removed, or used hardware, software, or media in connection with any information technology system without authorization in the last seven years so that my investigator can review the incident details.

Acceptance Criteria
- Fields
  - [ ] **In the last seven (7) years** have you introduced, removed, or used hardware, software, or media in connection with any information technology system without authorization, when specifically prohibited by rules, procedures, guidelines, or regulations or attempted any of the above?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date of the incident
  - You responded ‘Yes’ to having **in the last seven (7) years** introduced, removed, or used hardware, software, or media in connection with any information technology system without authorization, when specifically prohibited by rules, procedures, guidelines, or regulations or attempted any of the above.
  - Provide the date of the incident.
    - [ ] Date (Estimated)
  - Provide a description of the nature of the incident or offense.
    - [ ] Free Text
  - Provide the location where the incident took place.
    - [ ] Address block (with country)
  - Provide a description of the action (administrative, criminal or other) taken as a result of this incident.
    - [ ] Free Text
  - Are there any other incidents to report?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![infotechunlawfuluse](https://user-images.githubusercontent.com/12962390/26860486-2d720232-4b0c-11e7-8c5d-08d0ba00ef1a.png)

**Comment by bmallred** [comment]
## Preview
![legal-tech-unlawful](https://user-images.githubusercontent.com/697855/26942291-80f59d08-4c4f-11e7-9856-5d4087661a25.gif)

**Comment by lauraponce** [comment]
Looks good!
