### ISSUE TITLE
Applicant IT Systems Unlawful Use Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#935]
As an eApp applicant I want to see a summary listing of all instances where I have attempted to unlawfully add or remove software or hardware so that I can reopen and edit specific instances of unlawful hardware/software change entries, or remove an entry.

Acceptance Criteria
- Summary of unlawful IT systems use
  - [ ] Shown only if unlawful IT systems uses have been provided
  - [ ] Listing of each unlawful IT systems use the applicant has entered
  - [ ] For each unlawful IT systems use entry show the following summary fields: 
    - [ ] Date: Read-Only label
    - [ ] Description: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to unlawful IT systems use entry section
      - [ ] Delete - Removes the unlawful IT systems use data entry
- Easily toggle between high-level summary data and detail data

**Comment by lauraponce** [comment]
Looks good!
