### ISSUE TITLE
Applicant Non-Criminal Court

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#936]
As an eApp applicant I want to provide information regarding any instance where I have been a party to any public record civil court action in the last ten years so that my investigator can review the court action details.

Acceptance Criteria
- Fields
  - [ ] **In the last ten (10) years**, have you been a party to any public record civil court action not listed elsewhere on this form?
    - [ ] Yes/No Option
    - [ ] **Branch** 
      - [ ] No - move on to the next form section
      - [ ] Yes - An entry is created in the summary section, go to: Provide the date of the civil action
  - You responded ‘Yes’ to having been a party to any public record civil court action(s) not listed elsewhere on this form **in the last ten (10) years**.
  - Provide the date of the civil action
    - [ ] Date (Estimated)
  - Provide the court name
    - [ ] Free Text
  - Provide the address of the court.
    - [ ] Address block (with country)
  - Provide details of the nature of the action.
    - [ ] Free Text
  - Provide a description of the results of the action.
    - [ ] Free Text
  - Provide the name(s) of the principal parties involved in the court action.
    - [ ] Free Text
  - Are there any other civil court actions **in the last ten (10) years** to report?
    - [ ] Yes/No Option
    - [ ] **Branch**
      - [ ] If yes, another entry is added to the summary accordion
      - [ ] If no, user continues to next form section

**Comment by pjsumm** [comment]
![noncriminalcourtaction](https://user-images.githubusercontent.com/12962390/26860541-55151536-4b0c-11e7-9ebd-625d6e4e2095.png)

**Comment by billy22g** [comment]
LGTM
