### ISSUE TITLE
Applicant Non-Criminal Court Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#937]
As an eApp applicant I want to see a summary listing of all instances where I have been a party to public record civil court action so that I can reopen and edit specific public court action entries, or remove an entry.

Acceptance Criteria
- Summary of non-criminal court actions
  - [ ] Shown only if non-criminal court actions have been provided
  - [ ] Listing of each non-criminal court action the applicant has entered
  - [ ] For each non-criminal court action entry show the following summary fields: 
    - [ ] Date: Read-Only label
    - [ ] Court: Read-Only label
    - [ ] Actions:
      - [ ] Edit - click on item to go to non-criminal court action entry section
      - [ ] Delete - Removes the non-criminal court action data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
