### ISSUE TITLE
Applicant Terrorist Organization Membership

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#938]
As an eApp applicant I want to provide information regarding any instance where I have been a member of an organization dedicated to terrorism, either with an awareness of the organization’s dedication to that end, or with the specific intent to further such activities so that my investigator is aware of my association with such organizations.

Acceptance Criteria
- [x] Section Help: The following pertain to your associations. You are required to answer the questions fully and truthfully, and your failure to do so could be grounds for an adverse employment, security, or credentialing decision. For the purpose of this question, terrorism is defined as any criminal acts that involve violence or are dangerous to human life and appear to be intended to intimidate or coerce a civilian population to influence the policy of a government by intimidation or coercion or to affect the conduct of a government by mass destruction, assassination or kidnapping.
- Fields
  - [x] Are you now or have you **EVER** been a member of an organization dedicated to terrorism, either with an awareness of the organization’s dedication to that end, or with the specific intent to further such activities?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the full name of the organization.
  - You responded ‘Yes’ to being or **EVER** having been a member of an organization dedicated to terrorism, either with an awareness of the organization’s dedication to that end, or with the specific intent to further such activities.
  - Provide the full name of the organization.
    - [x] Free Text
  - Provide the address/location of the organization.
    - [x] Address block (with Country)
  - Provide the dates of your involvement with the organization.
    - [x] Date Range (Estimated/Present)
  - Provide all positions held in the organization, if any. 
    - [x] Check: No positions held
    - [x] Free Text
  - Provide all contributions made to the organization, if any. 
    - [x] Check: No contributions made
    - [x] Free Text
  - Provide a description of the nature of and reasons for your involvement with the organization.
    - [x] Free Text
  - Do you have any other instances of being a member of an organization dedicated to terrorism, either with an awareness of the organization’s dedication to that end, or with the specific intent to further such activities to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![associationrecord](https://user-images.githubusercontent.com/12962390/26860566-76b7af96-4b0c-11e7-805f-8bc87f1e476e.png)

**Comment by bmallred** [comment]
![legal-associations-terrorist-organization](https://user-images.githubusercontent.com/697855/27034189-7f386c9a-4f4a-11e7-8f1f-33a011081a00.gif)

**Comment by lauraponce** [comment]
Looks good!
