### ISSUE TITLE
Applicant Terrorist Organization Membership Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#939]
As an eApp applicant I want to see a summary listing of all instances where I have been a member of an organization dedicated to terrorism so that I can reopen and edit specific organization entries, or remove an entry.

Acceptance Criteria
- Summary of terrorist organization memberships
  - [x] Shown only if terrorist organization memberships have been provided
  - [x] Listing of each terrorist organization membership the applicant has entered
  - [x] For each terrorist organization membership entry show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] Organization Name: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to terrorist organization membership entry section
      - [x] Delete - Removes the terrorist organization membership data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
