### ISSUE TITLE
Applicant Acts of Terrorism

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#940]
As an eApp applicant I want to provide information regarding any time I knowingly engaged in any acts of terrorism so that my investigator has the details of the terrorist act.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** knowingly engaged in any acts of terrorism?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Describe the nature and reasons...
  - You responded ‘Yes’ to **EVER** having knowingly engaged in any acts of terrorism.
  - Describe the nature and reasons for the activity.
    - [x] Free Text
  - Provide the dates for any such activities.
    - [x] Date Range (Estimated/Present)
  - Do you have any other instances of knowingly engaging in acts of terrorism to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![actsofterrorism](https://user-images.githubusercontent.com/12962390/26860583-92b7ce60-4b0c-11e7-85f8-a7462194f67f.png)

**Comment by bmallred** [comment]
![legal-associations-engaged](https://user-images.githubusercontent.com/697855/27034249-bc455954-4f4a-11e7-9058-7c1459ba6a03.gif)

**Comment by lauraponce** [comment]
Looks good!
