### ISSUE TITLE
Applicant Acts of Terrorism Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#941]
As an eApp applicant I want to see a summary listing of all instances where I knowingly engaged in any acts of terrorism so that I can reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of terrorist acts
  - [x] Shown only if terrorist acts have been provided
  - [x] Listing of each terrorist act the applicant has entered
  - [x] For each terrorist act entry show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] ~~Organization Name: Read-Only label~~
    - [x] Actions:
      - [x] Edit - click on item to go to terrorist act entry section
      - [x] Delete - Removes the terrorist act data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
