### ISSUE TITLE
Applicant Advocate Acts of Terrorism

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#942]
As an eApp applicant I want to provide information regarding any instance where I advocated acts of terrorism or activities designed to overthrow the U.S. Government by force so that my investigator has the details surrounding my past history with advocating terrorism.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** advocated any acts of terrorism or activities designed to overthrow the U.S. Government by force?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the reason(s) for advocating acts of terrorism
  - You responded ‘Yes’ to having **EVER** advocated any acts of terrorism or activities designed to overthrow the U.S. Government by force.
  - Provide the reason(s) for advocating acts of terrorism.
    - [x] Free Text
  - Provide the dates of advocating acts of terrorism.
    - [x] Date Range (Estimated/Present)
  - Do you have any other instances of advocating acts of terrorism or activities designed to overthrow the U.S. Government by force to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![advocatedactsofterrorism](https://user-images.githubusercontent.com/12962390/26860597-b4777d5c-4b0c-11e7-9cb2-9f316dfaba51.png)

**Comment by bmallred** [comment]
![legal-associations-advocating](https://user-images.githubusercontent.com/697855/27034285-f2c0bf64-4f4a-11e7-91bd-7c301fc2f58f.gif)

**Comment by billy22g** [comment]
LGTM
