### ISSUE TITLE
Applicant Advocate Acts of Terrorism Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#943]
As an eApp applicant I want to see a summary listing of all instances where I advocated acts of terrorism or activities designed to overthrow the U.S. Government by force so that I can reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of advocated terrorism
  - [x] Shown only if advocated terrorism has been provided
  - [x] Listing of each time the applicant advocated terrorism  
  - [x] For each time the applicant advocated terrorism show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] Reason: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to advocated terrorist act entry section
      - [x] Delete - Removes the advocated terrorist act data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
