### ISSUE TITLE
Applicant Subversive Organization Membership

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#944]
As an eApp applicant I want to provide information regarding any membership I have had to an organization dedicated to the use of violence or force to overthrow the United States Government so that my investigator is aware of my association with such organizations.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** been a member of an organization dedicated to the use of violence or force to overthrow the United States Government, and which engaged in activities to that end with an awareness of the organization’s dedication to that end or with the specific intent to further such activities?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the full name of the organization
  - You responded ‘Yes’ to having **EVER** been a member of an organization dedicated to the use of violence or force to overthrow the United States Government, and which engaged in activities to that end with an awareness of the organization’s dedication to that end or with the specific intent to further such activities.
  - Provide the full name of the organization.
    - [x] Free Text
  - Provide the address/location of the organization.
    - [x] Address block (with country)
  - Provide the dates of your involvement with the organization.
    - [x] Date Range (Estimated/Present)
  - Provide all positions held in the organization, if any.
    - [x] Check: No positions held
    - [x] Free Text
  - Provide all contributions made to the organization, if any. 
    - [x] Check: No contributions made
    - [x] Free Text
  - Provide a description of the nature of and reasons for your involvement with the organization.
    - [x] Free Text
  - Do you have any other instances of being a member of an organization dedicated to the use of violence or force to overthrow the United States Government, which engaged in activities to that end with an awareness of the organization’s dedication to that end or with the specific intent to further such activities to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![memberofviolentoverthrow](https://user-images.githubusercontent.com/12962390/26860620-d146c0fa-4b0c-11e7-9cf8-d378c2fcac3b.png)

**Comment by bmallred** [comment]
![legal-associations-membership-overthrow](https://user-images.githubusercontent.com/697855/27034328-35184a44-4f4b-11e7-9dbd-b19932e45f45.gif)

**Comment by lauraponce** [comment]
Looks good! (Same question as on #946 but if modified, it would resolve the same thing here, so no need to keep this one open).
