### ISSUE TITLE
Applicant Subversive Organization Membership Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#945]
As an eApp applicant I want to see a summary listing of all instances where I have membership with an organization dedicated to the use of violence or force to overthrow the United States Government so that I can reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of subversive organizations
  - [x] Shown only if subversive organizations have been provided
  - [x] Listing of each subversive organization has entered
  - [x] For each subversive organization entry show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] Organization Name: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to subversive organization entry section
      - [x] Delete - Removes the subversive organization data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
