### ISSUE TITLE
Applicant Coercive Organization Membership

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#946]
As an eApp applicant I want to provide information regarding any membership I have had to an organization advocating or practicing commission of acts of force or violence to discourage others from exercising their rights under the U.S. Constitution or any state of the United States so that my investigator is aware of my association with such organizations.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** been a member of an organization that advocates or practices commission of acts of force or violence to discourage others from exercising their rights under the U.S. Constitution or any state of the United States with the specific intent to further such action?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Provide the full name of the organization
  - You responded ‘Yes’ to being or **EVER** having been a member of an organization that advocates or practices commission of acts of force or violence to discourage others from exercising their rights under the U.S. Constitution or that of any state of the U.S. with the specific intent to further such action.
  - Provide the full name of the organization.
    - [x] Free Text
  - Provide the address/location of the organization.
    - [x] Address block (with country)
  - Provide the dates of your involvement with the organization.
    - [x] Date Range (Estimated/Present)
  - Provide all positions held in the organization, if any. 
    - [x] Check: No positions held
    - [x] Free Text
  - Provide all contributions (in U.S. dollars) made to the organization, if any.
    - [x] Check: No contributions made
    - [x] Free Text
  - Provide a description of the nature of and reasons for your involvement with the organization.
    - [x] Free Text
  - Do you have any other instances of being a member of an organization that advocates or practices commission of acts of force or violence to discourage others from exercising their rights under the U.S. Constitution or any state of the United States with the specific intent to further such action to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![memberoforgsactsofforce](https://user-images.githubusercontent.com/12962390/26860649-f5e07064-4b0c-11e7-9939-7219be6fc2b4.png)

**Comment by bmallred** [comment]
![legal-associations-membership-violence](https://user-images.githubusercontent.com/697855/27034620-5d217168-4f4c-11e7-90a4-1e84feed0e7a.gif)

**Comment by lauraponce** [comment]
- [ ] Minor tweak to the main question text to match the form: the second "United States" should be "U.S." and "under the U.S. Constitution or any state" should be "...Constitution or that of any state" (note this applies to the follow up question at the end too)

- Question about the address/location for this section. The placeholder text in the address input field is "Enter mailing address" but in this case, the question is asking for the location of the organization, which could potentially be different than it's mailing address. Should we modify the placeholder text to be more generic so that it could be either location or mailing? @billy22g @Jay-Neighbours-I72 

![screen shot 2017-06-15 at 1 08 48 pm](https://user-images.githubusercontent.com/21222704/27193208-09a52a8e-51cc-11e7-8691-3d6b8a5f9524.png)

**Comment by bmallred** [comment]
@lauraponce the text for the initial question appears to be inline with the one on the form...

![quuestion](https://user-images.githubusercontent.com/697855/27197833-c247e00c-51dd-11e7-8eba-eb8a0abbe748.png)

**Comment by lauraponce** [comment]
You are correct! I was mistakenly reading the one under it. Please ignore my comment :) @bmallred

**Comment by billy22g** [comment]
I wonder if we shouldn't just have that "Enter mailing address" be "Enter street address" to disambiguate that in all cases @lauraponce?

**Comment by bmallred** [comment]
I _kind of_ remember a conversation about this. The concern I believe was if we said to enter the street address people may think they can enter only one. Our address block only has one form element for it an using "mailing address" may have been an attempt to state you can have more than one.

Either way I agree it is confusing!

@lauraponce @billy22g any objections on creating another issue to track this and move this two issues along?

**Comment by lauraponce** [comment]
👍  @bmallred #1448 has been entered, closing this one out.

**Comment by bmallred** [comment]
Thanks @lauraponce!
