### ISSUE TITLE
Applicant Coercive Organization Membership Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#947]
As an eApp applicant I want to see a summary listing of all instances where I have membership to an organization advocating or practicing commission of acts of force or violence to discourage others from exercising their rights under the U.S. Constitution so that I can reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of coercive organizations
  - [x] Shown only if coercive organizations have been provided
  - [x] Listing of each coercive organization has entered
  - [x] For each coercive organization entry show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] Organization Name: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to coercive organization entry section
      - [x] Delete - Removes the coercive organization data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
