### ISSUE TITLE
Applicant Subversive Behavior

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#948]
As an eApp applicant I want to provide information regarding any activities I have knowingly engaged in designed to overthrow the U.S. Government by force so that my investigator is aware of my activities against the U.S. Government.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** knowingly engaged in activities designed to overthrow the U.S. Government by force?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Describe the nature and reasons for the activity
  - You responded ‘Yes’ to having **EVER** knowingly engaged in activities designed to overthrow the U.S. Government by force.
  - Describe the nature and reasons for the activity.
    - [x] Free Text
  - Provide the dates of such activities.
    - [x] Date Range (Estimated/Present)
  - Do you have any other instances of having knowingly engaged in activities designed to overthrow the U.S. Government by force to report?
    - [x] Yes/No Option
    - [x] **Branch**
      - [x] If yes, another entry is added to the summary accordion
      - [x] If no, user continues to next form section

**Comment by pjsumm** [comment]
![engagedtooverthrowusgov](https://user-images.githubusercontent.com/12962390/26860655-0d88d918-4b0d-11e7-84fa-8fbc37946712.png)

**Comment by bmallred** [comment]
![legal-associations-activities](https://user-images.githubusercontent.com/697855/27034674-9579eda6-4f4c-11e7-922a-6d152a7df68d.gif)

**Comment by billy22g** [comment]
LGTM
