### ISSUE TITLE
Applicant Subversive Behavior Summary

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#949]
As an eApp applicant I want to see a summary listing of all instances where I have knowingly engaged in activities designed to overthrow the U.S. Government by force so that I can reopen and edit specific entries, or remove an entry.

Acceptance Criteria
- Summary of subversive behavior
  - [x] Shown only if subversive behaviors have been provided
  - [x] Listing of each subversive behavior has entered
  - [x] For each subversive behavior entry show the following summary fields: 
    - [x] Date Range: Read-Only label
    - [x] Actions:
      - [x] Edit - click on item to go to subversive behavior entry section
      - [x] Delete - Removes the subversive behavior data entry
- Easily toggle between high-level summary data and detail data

**Comment by billy22g** [comment]
LGTM
