### ISSUE TITLE
Applicant Terrorism Association

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#950]
As an eApp applicant I want to provide information regarding times I have associated with anyone involved in activities to further terrorism so that my investigator is aware of my association with terrorists.

Acceptance Criteria
- Fields
  - [x] Have you **EVER** associated with anyone involved in activities to further terrorism?
    - [x] Yes/No Option
    - [x] **Branch** 
      - [x] No - move on to the next form section
      - [x] Yes - An entry is created in the summary section, go to: Terrorism Association Detail
  - Terrorism Association Detail
    - [x] Free Text

**Comment by pjsumm** [comment]
![involvedwithterrorist](https://user-images.githubusercontent.com/12962390/26860669-27a22ac0-4b0d-11e7-9df3-9b9f03bb2b29.png)

**Comment by bmallred** [comment]
![legal-associations-terrorism](https://user-images.githubusercontent.com/697855/27034728-cd79511a-4f4c-11e7-9113-495abf72b2e6.gif)

**Comment by billy22g** [comment]
LGTM
