### ISSUE TITLE
Evaluate breakpoints

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#959]
As an eApp applicant I want to be able to utilize any device I am comfortable from hand-held to desktop so that I can complete my SF86 form. 

Acceptance Criteria
- [x] Evaluate breakpoints form wide
- [x] Test on tablet
- [x] Test on laptop
- [x] Test on mobile

**Comment by Jay-Neighbours-I72** [comment]
Issue with ipad/iphone #1875 . Once that is resolved I can test.

Proposed breakpoints:
- 1250px - switch from form max width to 100%. (All form elements should be fluid here, inputs adjust, buttons stack, etc.)

- 1000px - switch to mobile style

cc @lauraponce 

@bmallred @floresj There are a few other tweaks that need to be made here, I'm thinking a hangout/walkthrough would be best.

**Comment by Jay-Neighbours-I72** [comment]
Bugs added for tablet and phone issues

**Comment by billy22g** [comment]
LGTM

**Comment by billy22g** [comment]
Oops, moved this from the wrong column. Sorry @Jay-Neighbours-I72. Reopening.

**Comment by Jay-Neighbours-I72** [comment]
Nope this one was my fault. It should have been in Review/QA. I'll drag it to complete.
